<?php
  // Set up page title:
  $pageTitle = 'ReservationList::Create New Reservation List';
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('reservationlist-addlist') . '">' . $this->transEsc('ReservationList::Add List') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<form class="form-edit-list" method="post" name="FinnaResourceList">
  <input type="hidden" name="recordId" value="<?=$this->escapeHtmlAttr($this->recordId)?>">
  <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->source)?>">
  <input type="hidden" name="organisation" value="<?=$this->escapeHtmlAttr($this->organisation)?>">
  <input type="hidden" name="listIdentifier" value="<?=$this->escapeHtmlAttr($this->listIdentifier)?>">
  <input type="hidden" name="state" value="saveList">
  <div class="form-group">
    <label class="control-label" for="list_title"><?=$this->transEsc('ReservationList::Reservation List Name'); ?>*:</label>
    <input id="list_title" class="form-control" type="text" name="title" value="">
  </div>
  <div class="form-group">
    <label class="control-label" for="list_desc"><?=$this->transEsc('ReservationList::Description') ?></label>
    <textarea id="list_desc" class="form-control" name="desc" rows="3"></textarea>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('ReservationList::Create New Reservation List') ?>">
  </div>
</form>
