<?php
  // Set up page title:
  $pageTitle = empty($this->list->id) ? 'Create a Reservation List' : 'Edit Reservation List';
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<form class="form-edit-list" method="post" name="reservationList">
  <input type="hidden" name="id" value="<?=empty($this->list->id) ? 'NEW' : $this->escapeHtmlAttr($this->list->id) ?>">
  <input type="hidden" name="recordId" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueID())?>">
  <input type="hidden" name="action" value="<?=$this->escapeHtmlAttr($this->action)?>">
  <div class="form-group">
    <label class="control-label" for="list_title"><?=$this->transEsc('List'); ?>:</label>
    <input id="list_title" class="form-control" type="text" name="title" value="<?=isset($this->list['title']) ? $this->escapeHtmlAttr($this->list['title']) : ''?>">
  </div>
  <div class="form-group">
    <label class="control-label" for="list_desc"><?=$this->transEsc('Description') ?></label>
    <textarea id="list_desc" class="form-control" name="desc" rows="3"><?=isset($this->list['description']) ? $this->escapeHtml($this->list['description']) : ''?></textarea>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('Save') ?>">
  </div>
</form>
