<?php
  // Set up page title:
  $this->headTitle($this->translate('reservation_list_add_list'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<form class="form-edit-list" method="post" name="reservationList">
  <input type="hidden" name="recordId" value="<?=$this->escapeHtmlAttr($this->recordId)?>">
  <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->source)?>">
  <input type="hidden" name="state" value="saveList">
  <div class="form-group">
    <label class="control-label" for="list_title"><?=$this->transEsc('reservation_list_title'); ?>:</label>
    <input id="list_title" class="form-control" type="text" name="title" value="<?=isset($this->list['title']) ? $this->escapeHtmlAttr($this->list['title']) : ''?>">
  </div>
  <div class="form-group">
    <label class="control-label" for="list_desc"><?=$this->transEsc('reservation_list_description') ?></label>
    <textarea id="list_desc" class="form-control" name="desc" rows="3"><?=isset($this->list['description']) ? $this->escapeHtml($this->list['description']) : ''?></textarea>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('reservation_list_save') ?>">
  </div>
</form>
