<?php
  // Set up page title:
  $pageTitle = 'ReservationList::Create New Reservation List';
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li class="breadcrumb-item"><a href="' . $this->url('reservationlist-createlist') . '">' . $this->transEsc('ReservationList::Add List') . '</a></li>'
    . '<li class="breadcrumb-item active">' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<form class="form-edit-list" method="post" name="CreateReservationList" action="<?=$this->url('reservationlist-createlist'); ?>">
  <?= $this->component('finna-hidden-form-fields.phtml', [
      'fields' => [
        \Finna\ReservationList\Form\Form::LIST_RECORD_KEY => $this->recordId,
        \Finna\ReservationList\Form\Form::SOURCE_KEY => $this->source,
        \Finna\ReservationList\Form\Form::LIST_IDENTIFIER_KEY => $this->listIdentifier,
        \Finna\ReservationList\Form\Form::INSTITUTION_KEY => $this->institution,
        'csrf' => $this->auth()->getManager()->getCsrfHash(),
      ],
    ]); ?>
  <div class="form-group">
    <label class="control-label" for="list_title"><?=$this->transEsc('ReservationList::Reservation List Name'); ?>*:</label>
    <input id="list_title" class="form-control" type="text" name="title" value="" required>
  </div>
  <div class="form-group">
    <label class="control-label" for="list_desc"><?=$this->transEsc('ReservationList::Description') ?></label>
    <textarea id="list_desc" class="form-control" name="desc" rows="3"></textarea>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="list_created" value="<?=$this->transEscAttr('ReservationList::Create New Reservation List') ?>">
  </div>
</form>
