<?php
  // Set up page title:
  $pageTitle = 'Delete list %%%%';
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('reservationlist-home', ['id' => $this->id]) . '">' . $this->transEsc('Poista lista') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>

<h2><?=$this->transEsc($pageTitle); ?></h2>
<form method="post" name="delete" data-lightbox-onclose="VuFind.refreshPage">
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->id)?>">
  <button type="submit" class="btn btn-primary" value="1">Kyllä</button>
  <button class="btn btn-primary" data-dismiss="modal" aria-label="sulje" value="0">Ei</button>
</form>
