<!-- START of: finna - reservationlist/home.phtml -->
<?php
  $title = $this->transEsc('ReservationList::All Lists');
  // Set up page title:
  $this->headTitle($title);

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('reservationlist-home') . '">' . $title . '</a></li> <li class="active">' . $this->transEsc('ReservationList::Reservation List') . '</li>';
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'reservationlist']); ?>


<div class="<?=$this->layoutClass('mainbody-myresearch')?> reservation-list-body">
  <h2><?=$title ?></h2>
  <?= $this->flashmessages() ?>
  <ul class="reservations-list-home-ul">
    <?php foreach ($this->lists ?? [] as $wrapper): ?>
      <?php
        $list = $wrapper['list_entity'];
        $details = $wrapper['details_entity'];
        $listTranslations = $this->reservationList()->getListTranslationKeys($details->getInstitution(), ['Identifier' => $details->getListConfigIdentifier()]);
      ?>
      <li class="reservations-list-home-li">
        <div class="reservation-list-header">
          <div>
            <a href="<?= $this->url('reservationlist-list', ['id' => $list['id']])?>"><?= $this->escapeHtml($list['title']) ?></a>
          </div>
          <div class="pull-right">
            <a href="<?= $this->url('reservationlist-delete', ['id' => $list['id']])?>" data-lightbox=""><?= $this->transEsc('ReservationList::Delete List') ?></a>
          </div>
        </div>
        <div class="reservation-list-info">
          <div><?= $this->transEsc(['ReservationList', $listTranslations['title']]); ?></div>
          <?php if ($details->getOrdered()): ?>
            <div class="list-ordered list-info">
              <?= $this->transEsc('ReservationList::list_ordered', ['%%date%%' => $details->getOrdered()->format('d.m.Y')])?>
            </div>
          <?php endif; ?>
        </div>
      </li>
      <?php endforeach; ?>
  </ul>
</div>
<div class="mylist-mobile mobile-navigation visible-xs visible-sm hidden-print">
  <ul>
    <li class="sidebar-navigation"><?=$this->icon('sidebar-expand') ?> <?=$this->transEsc('Your Lists')?></li>
  </ul>
</div>
<!-- END of: finna - reservationlist/home.phtml -->
