<!-- START of: finna - myresearch/reservationlist.phtml -->
<?php
  // Set up page title:
  $this->headTitle($this->translate('Library Cards'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Library Cards') . '</li>';

  // Additional translations
  $this->jsTranslations()->addStrings(['new_password_success' => 'new_password_success']);

  $user = $this->auth()->isLoggedIn();
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'reservationList']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content">
    <div class="menu-flex">
      <?php if (!empty($this->lists)): ?>
        <div class="select-group">
          <label>Listat:</label>
          <select>
            <?php foreach ($this->lists ?? [] as $list): ?>
              <option value="<?=$this->escapeHtmlAttr($list['id'])?>" <?php if ($this->activeId === $list['id']): ?>selected="selected"<?php endif; ?>><?= $this->escapeHtml($list['title']) ?></option>
            <?php endforeach; ?>
          </select>
        </div>
      <?php endif; ?>
      <div class="sorting-stuff">
        <!-- Do Later, order list, delete list, creation of a list happens at the same time with adding an item to a list -->
      </div>
    </div>
    <div class="useraccount-header">
      <h2><?=$this->transEsc('Reservation List') ?> (<?=count($this->recordList ?? []);?>)</h2>
    </div>
  </div>
</div>
<!-- END of: finna - myresearch/reservationlist.phtml -->
