<?php
  $pageTitle = 'FinnaResourceList::Send Reservation List to Research Room';
  // Set up page title:
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<?=$this->flashmessages()?>


<form class="form-edit-list" method="post" name="order" data-lightbox-onclose="VuFind.refreshPage">
  <input type="hidden" name="list-id" value="<?= $this->escapeHtmlAttr($this->listId); ?>"/>
  <p><?=$this->transEsc('FinnaResourceList::Reservable Material')?>:</p>
  <ul>
    <?php foreach ($this->results->getResults() as $result): ?>
      <li><?= $result->getTitle(); ?></li>
    <?php endforeach; ?>
  </ul>
  <div class="form-group">
    <h3><?=$this->transEsc('FinnaResourceList::Organisations Research Room Office')?>:</h3>
    <?= $this->transEsc($this->organisationInfo['name'] ?? ''); ?><br/>
    <?= $this->transEsc($this->organisationInfo['address'] ?? ''); ?><br/>
    <?= $this->transEsc($this->organisationInfo['postal'] ?? ''); ?> <?= $this->transEsc($this->organisationInfo['city'] ?? ''); ?>
  </div>
  <!-- need current date and -->
  <div class="form-group">
    <label for="reservation_pickup_date"><?=$this->transEsc('FinnaResourceList::Delivery Time Request to Organisations Research Room')?>:</label><br>
    <input id="reservation_pickup_date" name="order-pickup-date" value="<?= $this->escapeHtmlAttr($this->earliestPickup); ?>" min="<?= $this->escapeHtmlAttr($this->earliestPickup); ?>" type="date"/>
  </div>
  <div class="form-group">
    <label for="reservation_email"><?=$this->transEsc('FinnaResourceList::Email')?>:</label><br>
    <input id="reservation_email" type="email" name="order-email" value="test@viiadolorosa.com">
  </div>
  <div class="form-group">
    <label for="reservation_phone"><?=$this->transEsc('FinnaResourceList::Phonenumber')?>:</label><br>
    <input id="reservation_phone" type="phone" name="order-phone" value="0401231234">
  </div>
  <div class="form-group">
    <label for="reservation_message"><?=$this->transEsc('FinnaResourceList::Message')?>:</label><br>
    <textarea id="reservation_message"></textarea>
  </div>
  <div class="form-group">
    <button class="btn btn-primary" type="submit"><?=$this->transEsc('FinnaResourceList::Send Reservation Request')?></button>
  </div>
</form>
