<?php
  $pageTitle = 'Lähetä varauslista (luku- tai tutkijasaliin)';
  // Set up page title:
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<p>Varauspyynnöllä voit tiedustella aineiston käyttöä tovottuna ajankohtana organisaation luku- tai tutkijasalissa. <b>Varaous on voimassa vasta kun organisaatio on hyväksynyt pyynnön ja vahvistanut sen</b></p>

<form class="form-edit-list" method="post" name="order">
  <p>Varauksen aineistot:</p>
  <ul>
    <?php foreach ($this->results->getResults() as $result): ?>
      <li><?= $result->getTitle(); ?></li>
    <?php endforeach; ?>
  </ul>
  <div class="form-group">
    <p>Organisaation luku-tai tutkijasalin toimipiste:</p>
  </div>
  <!-- need current date and -->
  <div class="form-group">
    <p>Toimitusaikatoive XX-organisaation luku- tai tutkijasalissa:</p>
    <input name="order-pickup-date" value="<?= $this->escapeHtmlAttr($this->earliestPickup); ?>" min="<?= $this->escapeHtmlAttr($this->earliestPickup); ?>" type="date"/>
  </div>
  <div class="form-group">
  <input type="email" name="order-email" value="test@viiadolorosa.com">
  </div>
  <div class="form-group">
  <p>Viesti:</p>
  <textarea>
    Tähän kommentti sit joo
  </textarea>
  </div>
  <div class="form-group">
  <button class="btn btn-primary" type="submit">Tilaa lista</button>
  </div>
</form>
