<?php
  $pageTitleEsc = $this->transEscWithPrefix('ReservationList::reserve_to_', $this->listHandler->getListType());
  // Set up page title:
  $this->headTitle($pageTitleEsc);
  $user = $this->auth()->getUserObject();

  // Set up breadcrumbs:
  $this->breadcrumbs()->set(...$this->recordLinker()->getBreadcrumbParams($this->driver))
    ->add($pageTitleEsc, active: true);
  $params = [
    'source' => $this->source,
    'recordId' => $this->recordId,
    'institution' => $this->listHandler->getInstitution(),
    'listIdentifier' => $this->listHandler->getIdentifier(),
  ];
?>
<h2><?= $pageTitleEsc; ?></h2>
<div>
  <div>
    <label for="resource_name"><?=$this->transEsc('ReservationList::Resource')?>:</label>
    <p id="resource_name"><?=$this->transEsc($this->recordId)?></p>
  </div>
  <div>
    <label for="resource_institution"><?=$this->transEsc('ReservationList::Resource Institution')?>:</label>
    <p id="resource_institution"><?=$this->transEscWithPrefix('source_', $this->listHandler->getInstitution());?></p>
  </div>
</div>
<?php if ($this->reservationList()->singleOrderEnabled()): ?>
  <div class="btn-group">
    <a class="btn btn-primary" href="<?=$this->url('reservationlist-placesingleorder', ['id' => \Finna\ReservationList\Form\Form::RESERVATION_LIST_REQUEST], ['query' => $params])?>"><?=$this->transEsc('ReservationList::Reserve only this item')?></a>
  </div>
<?php endif; ?>
<div class="btn-group">
  <a class="btn btn-primary" href="<?=$this->url('reservationlist-additemtolist', [], ['query' => $params])?>"><?=$this->transEsc('ReservationList::Add To Reservation List')?></a>
</div>
