<?php
  $pageTitleEsc = $this->transEscWithPrefix('ReservationList::reserve_to_', $this->listHandler->getListType());
  // Set up page title:
  $this->headTitle($pageTitleEsc);
  $user = $this->auth()->getUserObject();

  // Set up breadcrumbs:
  $this->breadcrumbs()->set(...$this->recordLinker()->getBreadcrumbParams($this->driver))
    ->add($pageTitleEsc, active: true);
?>

<h2><?= $pageTitleEsc ?></h2>

<p><?=$this->transEsc('ReservationList::resource_added_to_reservation_list', ['%%resource%%' => $this->driver->getTitle(), '%%list%%' => $this->listEntity->getTitle()]);?></p>

<div class="btn-group">
  <a class="btn btn-primary" href="<?=$this->url('reservationlist-displaylist', ['listId' => $this->listEntity->getId()])?>" data-lightbox-ignore><?=$this->transEsc('ReservationList::Continue to book')?></a>
</div>
<div class="btn-group">
  <button class="btn btn-primary lightbox-only" data-bs-dismiss="modal"><?=$this->transEsc('close') ?></button>
</div>
