<!-- START of: finna - reservationlist/reservationlist-navi.phtml -->
<?php
  $numOfResources = $user->getNumOfResources();
  $currentLimit = 20; // default limit for favorites
  if (isset($this->results)) {
     $limitList = $this->results->getParams()->getLimitList();
     foreach ($limitList as $limitVal => $limitData) {
        if ($limitData['selected']) {
          $currentLimit = $limitVal;
          break;
        }
     }
  }
?>
<ul class="dropdown-menu subtabs collapse in" role="presentation">
  <li><h1 class="visible-xs visible-sm"><?=$this->icon('sidebar-collapse') ?> <?=$this->transEsc('Your Lists')?></h1></li>
  <?php foreach ($lists as $list): ?>
    <?php $active = ($list['id'] === $activeId); ?>
    <li role="none" class="favorites-menulist-item">
      <a role="menuitem" href="<?= $active ? '#' : $this->url('reservationlist-home', ['id' => $list['id']])?>?limit=<?=$currentLimit;?>" class="<?=$list && $active ? ' active' : ''?>" aria-current="<?=$active ? 'page' : 'false' ?>">
        <div class="favorite-list-holder">
          <div class="pull-left favorite-list-title"><?=$this->escapeHtml($list['title'])?></div>
          <?php if ($active): ?>
            <button class="pull-right remove-favorite-list remove"><?=$this->icon('list-remove') ?></button>
          <?php endif; ?>
        </div>
      </a>
    </li>
  <?php endforeach; ?>
  <li class="add-new-list-holder favorites-menulist-item hidden">
    <div class="list-group-item add-new-list">
      <input type="text" class="new-list-input" placeholder="<?=$this->transEsc('Create a List') ?>">
      <?=$this->icon('list-add', 'list-add-icon') ?>
    </div>
  </li>
</ul>
<!-- END of: finna - reservationlist/reservationlist-navi.phtml -->
