<!-- START of: finna - FinnaResourceList/FinnaResourceList-navi.phtml -->
<?php
  $numOfResources = $user->getNumOfResources();
  $currentLimit = 20; // default limit for favorites
  if (isset($this->results)) {
     $limitList = $this->results->getParams()->getLimitList();
     foreach ($limitList as $limitVal => $limitData) {
        if ($limitData['selected']) {
          $currentLimit = $limitVal;
          break;
        }
     }
  }
?>
<ul class="dropdown-menu subtabs collapse in" role="presentation">
  <li><h1 class="visible-xs visible-sm"><?=$this->icon('sidebar-collapse') ?> <?=$this->transEsc('Your Lists')?></h1></li>
  <?php $active = empty($activeId); ?>
  <li>
    <a class="<?=$active ? ' active' : ''?>" role="menuitem" href="<?= $active ? '#' : $this->url('reservationlist-home') ?>" aria-current="<?=$active ? 'page' : 'false'?>"><?= $this->transEsc('ReservationList::All Lists') ?></a>
  </li>
  <?php foreach ($lists as $index => $list): ?>
    <?php
      $active = ($list->getId() === $activeId);
      $details = $this->reservationList()->getListDetails($list->getId());
    ?>
    <li role="none" class="favorites-menulist-item">
      <a role="menuitem" href="<?= $active ? '#' : $this->url('reservationlist-list', ['id' => $list->getId()])?>?limit=<?=$currentLimit;?>" class="<?=$list && $active ? ' active' : ''?>" aria-current="<?=$active ? 'page' : 'false' ?>">
        <div class="favorite-list-holder">
          <div class="pull-left favorite-list-title"><?=$this->escapeHtml($list->getTitle())?></div><?php if ($details->getOrdered()): ?><div>(<?= $this->transEsc('ReservationList::Ordered')?>)</div><?php endif; ?>
        </div>
      </a>
    </li>
  <?php endforeach; ?>
</ul>
<!-- END of: finna - FinnaResourceList/FinnaResourceList-navi.phtml -->
