<?php
  $pageTitle = 'ReservationList::Add To Reservation List';
  // Set up page title:
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('reservationlist-additemtolist') . '">' . $this->transEsc('ReservationList::Add To Reservation List') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
  $listConfiguration = $this->reservationList($this->auth()->getUserObject())->getListConfiguration($this->institution, $this->listIdentifier, $driver);
  $listTranslations = $this->reservationList()->getListTranslationKeys($this->institution, $listConfiguration);
?>

<h2><?= $this->transEsc($pageTitle); ?></h2>
<strong><?= $this->transEsc(['ReservationList', $listTranslations['title']]) ?> </strong>
<p><?= $this->transEsc(['ReservationList', $listTranslations['description']]) ?> </p>
<div>
  <?php if (!empty($this->lists)): ?>
    <form method="post" name="FinnaResourceListAdd" data-lightbox-onclose="VuFind.refreshPage">
      <input type="hidden" name="state" value="saveItem">
      <label class="control-label" for="save_list"><?=$this->transEsc('ReservationList::Choose a List') ?></label>
      <div class="form-group">
        <select class="form-control" id="save_list" name="list">
          <?php foreach ($this->lists as $list): ?>
            <?php
              if ($list->getOrdered()) {
                continue;
              }
            ?>
            <option value="<?=$this->escapeHtmlAttr($list->getId())?>"><?=$this->escapeHtml($list->getTitle())?></option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group">
        <label class="control-label" for="add_notes"><?=$this->transEsc('ReservationList::Description') ?></label>
        <textarea class="form-control" id="add_notes" name="desc" rows="3"></textarea>
      </div>
      <div class="form-group">
        <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('ReservationList::Add To Reservation List') ?>">
      </div>
    </form>
  <?php else: ?>
    <?= $this->transEsc('ReservationList::No Lists Found') ?>
  <?php endif; ?>
  <a class="btn btn-link" id="make-list" href="<?=$this->url('reservationlist-additemtolist', [], ['query' => ['institution' => $this->institution, 'listIdentifier' => $this->listIdentifier, 'newList' => '1', 'recordId' => urlencode($this->driver->getUniqueId()), 'source' => urlencode($this->driver->getSourceIdentifier())]])?>"><?=$this->transEsc('ReservationList::Create New Reservation List')?></a>
</div>
