<div>
  <?php if (!empty($this->lists)): ?>
  <form method="post" name="reservationListAdd" data-lightbox-onclose="VuFind.refreshPage">
    <input type="hidden" name="state" value="saveItem">
    <label class="control-label" for="save_list"><?=$this->transEsc('reservation_list_choose_a_list') ?></label>
    <div class="form-group">
      <select class="form-control" id="save_list" name="list">
        <?php foreach ($this->lists as $list): ?>
          <option value="<?=$this->escapeHtmlAttr($list['id'])?>"><?=$this->escapeHtml($list['title'])?></option>
        <?php endforeach; ?>
      </select>
    </div>
    <div class="form-group">
      <label class="control-label" for="add_notes"><?=$this->transEsc('reservation_list_add_note') ?></label>
      <textarea class="form-control" id="add_notes" name="desc" rows="3"></textarea>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('reservation_list_save') ?>">
    </div>
  </form>
  <?php else: ?>
    <?= $this->transEsc('reservation_lists_no_lists_found') ?>
  <?php endif; ?>
  <a class="btn btn-link" id="make-list" href="<?=$this->url('reservationlist-additem', [], ['query' => ['newList' => '1', 'recordId' => urlencode($this->driver->getUniqueId()), 'source' => urlencode($this->driver->getSourceIdentifier())]])?>"><?=$this->transEsc('reservation_list_create_new_list')?></a>
</div>
