<?php
  $pageTitle = 'FinnaResourceList::Add To Reservation List';
  // Set up page title:
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('reservationlist-additem') . '">' . $this->transEsc('FinnaResourceList::Add To Reservation List') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<div>
  <?php if (!empty($this->lists)): ?>
  <form method="post" name="FinnaResourceListAdd" data-lightbox-onclose="VuFind.refreshPage">
    <input type="hidden" name="state" value="saveItem">
    <label class="control-label" for="save_list"><?=$this->transEsc('FinnaResourceList::Choose a List') ?></label>
    <div class="form-group">
      <select class="form-control" id="save_list" name="list">
        <?php foreach ($this->lists as $list): ?>
          <option value="<?=$this->escapeHtmlAttr($list['id'])?>"><?=$this->escapeHtml($list['title'])?></option>
        <?php endforeach; ?>
      </select>
    </div>
    <div class="form-group">
      <label class="control-label" for="add_notes"><?=$this->transEsc('FinnaResourceList::Description') ?></label>
      <textarea class="form-control" id="add_notes" name="desc" rows="3"></textarea>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('FinnaResourceList::Add To Reservation List') ?>">
    </div>
  </form>
  <?php else: ?>
    <?= $this->transEsc('FinnaResourceList::No Lists Found') ?>
  <?php endif; ?>
  <a class="btn btn-link" id="make-list" href="<?=$this->url('reservationlist-additem', [], ['query' => ['newList' => '1', 'recordId' => urlencode($this->driver->getUniqueId()), 'source' => urlencode($this->driver->getSourceIdentifier())]])?>"><?=$this->transEsc('FinnaResourceList::Create New Reservation List')?></a>
</div>
