<!-- START of: finna - myresearch/borrowing-block.phtml -->
<?php if (!empty($blocks)): ?>
  <div class="borrowing-block-container alert alert-info">
    <?php foreach ($blocks as $block): ?>
      <p class="borrowing-block"><?=substr($block, -5) === '_html' ? $this->translate($block) : str_replace("\n", '<br>', $this->transEsc($block))?></p>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
<!-- END of: finna - myresearch/borrowing-block.phtml -->
