<!-- START of: finna - myresearch/bulk-action-buttons.phtml -->
<?php if ($list): ?>
  <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->getId())?>">
  <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->getTitle())?>">
  <input type="hidden" name="listDescription" value="<?=$this->escapeHtmlAttr($list->getDescription() ?? '')?>">
<?php endif; ?>
<?php
  $user = $this->auth()->getUserObject();
  $canDelete = $this->canDelete ?? false;
  $cartEnabled = $this->cartEnabled ?? $this->cart()->isActive();
  $lists = $this->lists ?? [];
  $email = $this->email ?? true;
  $export = $this->export ?? (count($this->export()->getActiveFormats('bulk')) > 0);
  $displayBulkCheckboxes = $canDelete || $cartEnabled || $lists || $email || $export;
?>
<div class="finna-bulk-action-buttons bulk-action-buttons-row hidden-print">
  <?php
  $socialConfig = $this->config()->get('config')['Social'];
  $multiPageSelection = $socialConfig['multi_page_favorites_selection'] ?? true;
  $checkboxSelectAllType = $socialConfig['checkbox_select_all_favorites_type'] ?? 'both';
  ?>
  <div class="bulkActionButtons bulk-action-buttons-col">
    <div class="mylist-functions btn-group">
      <span class="visually-hidden"><?=$this->transEsc('bulk_noitems_advice')?></span>
      <?php if ($email): ?>
        <button id="button_email" class="btn btn-primary js-bulk-action" type="submit" name="email" value="<?=$this->transEscAttr('Email')?>" title="<?=$this->transEscAttr('bulk_email')?>" disabled<?php if ($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Email')?></button>
      <?php endif; ?>
      <?php if ($export): ?>
        <button class="btn btn-primary js-bulk-action" type="submit" name="export" value="<?=$this->transEscAttr('Export')?>" title="<?=$this->transEscAttr('bulk_export')?>" disabled<?php if ($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Export')?></button>
      <?php endif; ?>
      <?php if ($canDelete): ?>
        <button class="btn btn-primary js-bulk-action" id="<?=$this->idPrefix?>delete_list_items_<?=null !== $this->list ? $this->escapeHtmlAttr($this->list->getId()) : ''?>" type="submit" name="delete" value="<?=$this->transEscAttr('Delete')?>" title="<?=$this->transEsc('delete_selected')?>" disabled<?php if ($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Delete')?></button>
      <?php endif; ?>
      <?php if ($lists): ?>
        <button class="btn btn-primary js-bulk-action" id="<?=$this->idPrefix?>addToList" type="submit" name="addToList" title="<?=$this->transEsc('Add to List')?>" disabled<?php if ($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('List') ?></button>
      <?php endif; ?>
      <?php if ($cartEnabled): ?>
        <button class="btn btn-primary js-bulk-action" id="<?=$this->idPrefix?>updateCart" type="submit" name="add" title="<?=$this->transEsc('Add to Book Bag')?>" disabled<?php if ($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Bag') ?></button>
      <?php endif; ?>
    </div>
    <?php if ($lists): ?>
        <span id="add-to-list-spinner" class="hidden"><?=$this->icon('spinner') ?></span>
    <?php endif; ?>
  </div>
  <ul class="selection-controls-bar checkbox-container">
    <?php if ($displayBulkCheckboxes): ?>
      <?php if (in_array($checkboxSelectAllType, ['on_page', 'both'])): ?>
        <li class="bulk-checkbox">
          <input type="checkbox" name="selectAll" class="checkbox-select-all" id="myresearchCheckAll">
          <label for="myresearchCheckAll"><?=$this->transEsc('select_all_on_page')?></label>
        </li>
      <?php endif; ?>
      <?php if ($multiPageSelection && in_array($checkboxSelectAllType, ['global', 'both'])): ?>
        <li class="bulk-checkbox">
          <div class="select-all-global hidden">
            <input type="checkbox" name="selectAllGlobal" class="checkbox-select-all-global" id="myresearchCheckAllGlobal">
            <label for="myresearchCheckAllGlobal"><?=$this->transEsc('select_all')?></label>
          </div>
        </li>
      <?php endif; ?>
      <?php if ($multiPageSelection): ?>
        <li>
          <button type="button" class="clear-selection hidden"></button>
        </li>
      <?php endif; ?>
    <?php endif; ?>
  </ul>
  <div class="clearfix"></div>
</div>
<!-- END of: finna - myresearch/bulk-action-buttons.phtml -->

<?php
  $js = <<<JS
      finna.scriptLoader.load(
        {'finna-bulk-action-buttons': 'components/finna-bulk-action-buttons.js'},
        () => {
          finna.bulkActionButtons.init('.finna-bulk-action-buttons');
        }
      );
      JS;
    echo $this->assetManager()->outputInlineScriptString($js);
?>