<!-- START of: finna - myresearch/menu.phtml -->
<?php
    $capabilityParams = [];
    $user = $this->auth()->isLoggedIn();
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $capabilityParams = $patron ? ['patron' => $patron] : [];
    $showLibraryTabs = $this->ils()->loginAvailable();
    $ilsOffline = 'ils-none' === $this->ils()->getOfflineMode();
    $listOpen = $this->active == 'favorites' || substr($this->active, 0, 4) == 'list';
    //Get the data for vertical menu to show lists on correct site
    if ($listOpen) {
      $list = $this->results->getListObject();
      $activeId = $list['id'];
      $activeUrl = $this->serverUrl() . $this->url('home') . 'List/' . $activeId;
      $activePublic = $list['public'];
      $isDefaultList = !isset($list);
      $lists = $user ? $user->getLists() : null;
    }

    $menuListItems = [];
    if ($showLibraryTabs && !$ilsOffline) {
      $menuListItems = [
        'menu-loans' => [
          'active' => $this->active === 'checkedout',
          'url' => $this->url('myresearch-checkedout'),
          'translation' => $this->transEsc('Checked Out Items')
        ],
        'menu-historic-loans' => [
          'active' => $this->active === 'historicLoans',
          'url' => $this->url('myresearch-historicloans'),
          'translation' => $this->transEsc('Loan History'),
          'show' => $this->ils()->checkCapability('getMyTransactionHistory', $capabilityParams)
        ],
        'menu-holds' => [
          'active' => $this->active === 'holds',
          'url' => $this->url('myresearch-holds'),
          'translation' => $this->transEsc('Holds and Recalls')
        ],
        'menu-storage-retrieval-requests' => [
          'active' => $this->active === 'storageRetrievalRequests',
          'url' => $this->url('myresearch-storageretrievalrequests'),
          'translation' => $this->transEsc('Storage Retrieval Requests'),
          'show' => $this->ils()->checkFunction('storageRetrievalRequests', $capabilityParams)
        ],
        'menu-ill-requests' => [
          'active' => $this->active === 'ILLRequests',
          'url' => $this->url('myresearch-illrequests'),
          'translation' => $this->transEsc('Interlibrary Loan Requests'),
          'show' => $this->ils()->checkFunction('ILLRequests', $capabilityParams)
        ],
        'menu-fines' => [
          'active' => $this->active === 'Fines',
          'url' => $this->url('myresearch-fines'),
          'translation' => $this->transEsc('Fines')
        ],
        'menu-library-cards' => [
          'active' => $this->active === 'librarycards',
          'url' => $this->url('librarycards-home'),
          'translation' => $this->transEsc('Library Cards'),
          'show' => $user && $user->libraryCardsEnabled()
        ]
      ];
    }

    $nonLibraryItems = [
      'menu-profile' => [
        'active' => $this->active === 'profile',
        'url' => $this->url('myresearch-profile'),
        'translation' => $this->transEsc('Profile'),
        'show' => !$ilsOffline && $this->ils()->checkCapability('getMyProfile')
      ],
      'menu-history' => [
        'active' => $this->active === 'history',
        'url' => $this->url('search-history') . "?require_login",
        'translation' => $this->transEsc('history_saved_searches')
      ],
      'menu-favorites' => [
        'active' => $listOpen,
        'url' => $this->url('myresearch-favorites'),
        'translation' => $this->transEsc('Favorites'),
        'show' => $this->userlist()->getMode() !== 'disabled'
      ],
      'menu-logout' => [
        'active' => false,
        'url' => $this->url('myresearch-logout'),
        'translation' => $this->transEsc('Log Out'),
        'iconClass' => 'pull-right fa fa-sign-out fa-lg',
        'desktopOnly' => true
      ]
    ];

    $menuListItems = array_merge($menuListItems, $nonLibraryItems);

    $desktopList = [
      'open-loans' => [
        'active' => $this->active == 'checkedout' || $this->active == 'historicLoans' || $this->active == 'holds' || $this->active == 'storageRetrievalRequests' || $this->active == 'ILLRequests',
        'url' => $this->url('myresearch-checkedout'),
        'translation' => $this->transEsc('Checked Out Header'),
        'dropdown' => true,
        'ulId' => 'myLoans',
        'show' => !$ilsOffline && $showLibraryTabs,
        'children' => [
          'menu-loans',
          'menu-historic-loans',
          'menu-holds',
          'menu-storage-retrieval-requests',
          'menu-ill-requests'
        ]
      ],
      'menu-fines',
      'menu-library-cards',
      'menu-profile',
      'menu-history',
      'open-list' => [
        'active' => $listOpen,
        'url' => $this->url('myresearch-favorites'),
        'translation' => $this->transEsc('Favorites'),
        'show' => $this->userlist()->getMode() !== 'disabled',
        'partial' => [
          'url' => 'myresearch/mylist-navi.phtml',
          'wrapperClass' => 'mylist-bar',
          'params' => [
            'user' => $user ?? '',
            'isDefaultList' => $isDefaultList ?? '',
            'activeId' => $activeId ?? '',
            'activePublic' => $activePublic ?? '',
            'lists' => $lists ?? '',
            'results' => $this->results ?? ''
          ]
        ]
      ],
      'menu-logout'
    ];
    $activeMobileTab = 'none';
?>
<?php ob_start(); ?>
<?php foreach ($menuListItems as $id => $listItem) : ?>
  <?php if (isset($listItem['desktopOnly']) && $listItem['desktopOnly']) { continue; } ?>
  <?php if (!isset($listItem['show']) || $listItem['show'] !== false): ?>
    <?php
      if ($activeMobileTab === 'none' && $listItem['active']) {
        $activeMobileTab = $listItem['translation'];
      }
    ?>
    <li role="menuitem" class="<?=$id?><?= $listItem['active'] ? ' active' : ''?>">
      <a href="<?=$listItem['url']?>" class="list-group-item">
      <?=$listItem['translation']?>
      </a>
    </li>
  <?php endif; ?>
<?php endforeach; ?>
<?php $menuEntriesMobile = ob_get_clean(); ?>
<?php ob_start(); ?>

<li class="menu-header hidden-xs hidden-sm">
  <h1>
    <?= $this->transEsc('Your Account') ?>
    <?php if (!$this->translationEmpty('tooltip_myaccount_html')): ?>
      <span class="tooltip-myaccount" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="<?= $this->transEsc("tooltip_myaccount_html") ?>"><i class="fa fa-info-big"></i></span>
    <?php endif; ?>
  </h1>
</li>
<?php foreach ($desktopList as $id => $value) : ?>
<?php
  $isArray = is_array($value);
  $listItem = $isArray ? $value : $menuListItems[$value];
  if (isset($listItem['show']) && !$listItem['show']) {
    continue;
  }
  $name = $isArray ? $id : $value;
  $hasChildren = $listItem['children'] ?? false;
  $hasPartial = $listItem['partial'] ?? false;
  $showSpinner = $listItem['showSpinner'] ?? false;
?>
  <?php if ($hasChildren || $hasPartial): ?>
    <li role="menuitem" class="dropdown hidden-xs hidden-sm <?= $listItem['active'] ? ' active' : ''?>">
      <a href="<?=$listItem['url']?>" id="<?=$id?>" class=" list-group-item <?= !$listItem['active'] ? 'collapsed' : '' ?>" >
        <?=$listItem['translation']?>
        <?php if ($showSpinner) : ?>
          <i class="hidden fa fa-spinner fa-spin"></i><span class="ajax-error hidden"><small> <?=$this->translate('An error has occurred'); ?></small></span>
        <?php endif; ?>
        <span class="caret"></span>
      </a>
      <?php if ($hasPartial) : ?>
        <div class="<?= $value['partial']['wrapperClass'] ?? 'ajax-wrapper'?>">
          <?php if ($listItem['active']): ?>
            <?= $this->partial($value['partial']['url'], $value['partial']['params']); ?>
          <?php endif; ?>
        </div>
      <?php else: ?>
        <ul id="<?=$listItem['ulId']?>" role="presentation" class="dropdown-menu subtabs collapse <?= $listItem['active'] ? ' in' : ''?>">
          <?php foreach ($listItem['children'] as $childKey) : ?>
            <?php
              $childItem = $menuListItems[$childKey] ?? ['show' => false];
              if (isset($childItem['show']) && !$childItem['show']) { continue; }
            ?>
              <li role="menuitem" class="<?=$childKey?>  <?=$childItem['active'] ? ' active' : ''?>">
                <a href="<?=$childItem['url']?>" class="list-group-item" aria-current="<?= $childItem['active'] ? 'page' : 'false' ?>">
                  <?=$childItem['translation']?>
                </a>
              </li>
          <?php endforeach; ?>
        </ul>
      <?php endif; ?>
    </li>
  <?php else: ?>
    <li role="menuitem" class="<?=$name?> <?=$listItem['active'] ? ' active' : ''?>">
      <a href="<?=$listItem['url']?>" class="list-group-item" aria-current="<?= $listItem['active'] ? 'page' : 'false' ?>">
        <?=$listItem['translation']?>
        <?php if (isset($listItem['iconClass'])): ?>
          <i class="<?=$listItem['iconClass']?>" aria-hidden="true"></i>
        <?php endif; ?>
      </a>
    </li>
  <?php endif; ?>
<?php endforeach; ?>

<?php $menuEntries = ob_get_clean(); ?>
<div class="mobile-main-tabs visible-xs visible-sm">
  <div class="dropdown useraccount-nav-mobile" role="menu">
    <div class="dropdown-toggle" data-toggle="dropdown">
      <div class="tab-title">
        <?= $activeMobileTab !== 'none' ? $activeMobileTab : $this->transEsc('Your Account'); ?>
      </div>
      <div class="more"><?= $this->transEsc('Your Account') ?><b class="caret"></b></div>
    </div>
    <ul class="dropdown-menu">
      <?=$menuEntriesMobile?>
    </ul>
  </div>
</div>
<ul class="<?=$this->layoutClass('sidebar-myresearch')?> <?= $listOpen ? '' : 'move-list' ?> nav-tabs-personal list-group useraccount-nav nav-tabs" role="menu">
  <?=$menuEntries?>
</ul>

<script>
    finna.menu.init();
</script>


<!-- END of: finna - myresearch/menu.phtml -->
