<!-- START of: finna - myresearch/menu.phtml -->
<?php
    $capabilityParams = [];
    $user = $this->auth()->isLoggedIn();
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $capabilityParams = $patron ? ['patron' => $patron] : [];
    if ($user) {
        $this->layout()->finnaMainHeader .= '<div>' . $this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'label' => 'Library Card']) . '</div>';
    }
    $this->layout()->finnaMainHeader;

    $showLibraryTabs = $this->ils()->loginAvailable();

    //Get the data for vertical menu to show lists on correct site
    if($this->active == 'favorites' || substr($this->active, 0, 4) == 'list'){
      $list = $this->results->getListObject();
      $activeId = $list['id'];
      $activeUrl = $this->serverUrl() . $this->url('home') . 'List/' . $activeId;
      $activePublic = $list['public'];
      $isDefaultList = !isset($list);
      $lists = $user ? $user->getLists() : null;
    }
?>
<?php ob_start(); ?>
<?php if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
  <?php if ($this->ils()->checkCapability('getMyProfile')): ?>
    <li class="menu-profile<?=$this->active == 'profile' ? ' active' : ''?>">
      <a href="<?=$this->url('myresearch-profile')?>" class="list-group-item">
        <?=$this->transEsc('Profile')?>
      </a>
    </li>
  <?php endif; ?>
  <?php if ($showLibraryTabs): ?>
    <li class="menu-loans <?=$this->active == 'checkedout' ? ' active' : ''?>">
      <a href="<?=$this->url('myresearch-checkedout')?>" class="list-group-item">
        <?=$this->transEsc('Checked Out Items')?>
      </a>
    </li>
    <?php if ($this->ils()->checkCapability('getMyTransactionHistory', $capabilityParams)): ?>
      <li class="menu-historic-loans <?=$this->active == 'historicLoans' ? ' active' : ''?>">
        <a href="<?=$this->url('myresearch-historicloans')?>" class="list-group-item">
          <?=$this->transEsc('Loan History')?>
        </a
      ></li>
    <?php endif; ?>
    <li class="menu-holds <?=$this->active == 'holds' ? ' active' : ''?>">
      <a href="<?=$this->url('myresearch-holds')?>" class="list-group-item">
        <?=$this->transEsc('Holds and Recalls')?>
      </a>
    </li>
    <?php if ($this->ils()->checkCapability('getMyStorageRetrievalRequests', $capabilityParams)): ?>
      <li class="menu-storage-retrieval-requests <?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
        <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="list-group-item">
          <?=$this->transEsc('Storage Retrieval Requests')?>
        </a>
      </li>
    <?php endif; ?>
    <?php if ($this->ils()->checkCapability('getMyILLRequests', $capabilityParams)): ?>
      <li class="menu-ill-requests <?=$this->active == 'ILLRequests' ? ' active' : ''?>">
        <a href="<?=$this->url('myresearch-illrequests')?>" class="list-group-item">
          <?=$this->transEsc('Interlibrary Loan Requests')?>
        </a>
      </li>
    <?php endif; ?>
    <li class="menu-fines <?=$this->active == 'fines' ? ' active' : ''?>">
      <a href="<?=$this->url('myresearch-fines')?>" class="list-group-item">
        <?=$this->transEsc('Fines')?>
      </a>
    </li>
    <?php if ($user && $user->libraryCardsEnabled()): ?>
      <li class="menu-library-cards <?=$this->active == 'librarycards' ? ' active' : ''?>">
        <a href="<?=$this->url('librarycards-home')?>" class="list-group-item">
          <?=$this->transEsc('Library Cards')?>
        </a>
      </li>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php if ($this->userlist()->getMode() !== 'disabled'): ?>
  <li class="menu-favorites <?=$this->active == 'favorites' || substr($this->active, 0, 4) == 'list' ? ' active' : ''?>">
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item">
      <?=$this->transEsc('Favorites')?>
    </a>
  </li>
<?php endif; ?>
<li class="menu-history <?=$this->active == 'history' ? ' active' : ''?>">
  <a href="<?=$this->url('search-history')?>?require_login" class="list-group-item">
    <?=$this->transEsc('history_saved_searches')?>
  </a>
</li>
<?php $menuEntriesMobile = ob_get_clean(); ?>
<?php ob_start(); ?>
<?php if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
  <?php if ($showLibraryTabs): ?>
    <li class="menu-header hidden-xs hidden-sm">
      <h4><?= $this->transEsc('Your Account') ?><i class="fa fa-question-circle-big pull-right"></i></h4>
    </li>
    <li role="menuitem" class="dropdown hidden-xs hidden-sm <?=$this->active == 'checkedout' || $this->active == 'historicLoans' || $this->active == 'holds' || $this->active == 'storageRetrievalRequests' || $this->active == 'ILLRequests' ? ' active' : ''?>">
      <a href="#" class="dropdown-toggle list-group-item collapsed" data-toggle="collapse" data-target="#myLoans" aria-expanded="false">
        <?=$this->transEsc('Checked Out Items')?> / <?=$this->transEsc('Holds and Recalls')?> <b class="caret"></b>
      </a>
      <ul id="myLoans" role="presentation" class="dropdown-menu subtabs collapse <?=$this->active == 'checkedout' || $this->active == 'historicLoans' || $this->active == 'holds' || $this->active == 'storageRetrievalRequests' || $this->active == 'ILLRequests' ? ' in' : ''?>">
        <li role="menuitem" class="menu-loans <?=$this->active == 'checkedout' ? ' active' : ''?>">
          <a href="<?=$this->url('myresearch-checkedout')?>" class="list-group-item">
            <?=$this->transEsc('Checked Out Items')?>
          </a>
        </li>
      <?php if ($this->ils()->checkCapability('getMyTransactionHistory', $capabilityParams)): ?>
        <li role="menuitem" class="menu-historic-loans <?=$this->active == 'historicLoans' ? ' active' : ''?>">
          <a href="<?=$this->url('myresearch-historicloans')?>" class="list-group-item">
            <?=$this->transEsc('Loan History')?>
          </a>
        </li>
      <?php endif; ?>
        <li role="menuitem" class="menu-holds <?=$this->active == 'holds' ? ' active' : ''?>">
          <a href="<?=$this->url('myresearch-holds')?>" class="list-group-item">
            <?=$this->transEsc('Holds and Recalls')?>
          </a>
        </li>
      <?php if ($this->ils()->checkCapability('getMyStorageRetrievalRequests', $capabilityParams)): ?>
        <li role="menuitem" class="menu-storage-retrieval-requests <?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
          <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="list-group-item">
            <?=$this->transEsc('Storage Retrieval Requests')?>
          </a>
        </li>
      <?php endif; ?>
      <?php if ($this->ils()->checkCapability('getMyILLRequests', $capabilityParams)): ?>
        <li role="menuitem" class="menu-ill-requests <?=$this->active == 'ILLRequests' ? ' active' : ''?>">
          <a href="<?=$this->url('myresearch-illrequests')?>" class="list-group-item">
            <?=$this->transEsc('Interlibrary Loan Requests')?>
          </a>
        </li>
      <?php endif; ?>
      </ul>
    </li>
    <li class="menu-fines hidden-xs hidden-sm <?=$this->active == 'fines' ? ' active' : ''?>">
      <a href="<?=$this->url('myresearch-fines')?>" class="list-group-item">
        <?=$this->transEsc('Fines')?>
      </a>
    </li>
    <?php if ($user && $user->libraryCardsEnabled()): ?>
      <li class="menu-library-cards hidden-xs hidden-sm<?=$this->active == 'librarycards' ? ' active' : ''?>">
        <a href="<?=$this->url('librarycards-home')?>" class="list-group-item">
          <?=$this->transEsc('Library Cards')?>
        </a>
      </li>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php if ($this->userlist()->getMode() !== 'disabled'): ?>
  <li class="menu-favorites mylist-menu-favorites <?=$this->active == 'favorites' || substr($this->active, 0, 4) == 'list' ? ' active collapsed' : ''?>">
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item hidden-xs hidden-sm">
      <?=$this->transEsc('Favorites')?>
    </a>
    <?php if($this->active == 'favorites' || substr($this->active, 0, 4) == 'list') : ?>
    <div class="mylist-bar">
      <?= $this->partial('myresearch/mylist-navi.phtml', ['user' => $user, 'isDefaultList' => $isDefaultList, 'activeId' => $activeId, 'activePublic' => $activePublic, 'lists' => $lists, 'results' => $this->results]);  ?>
    </div>
    <?php endif; ?>
  </li>
<?php endif; ?>
<li class="menu-history hidden-xs hidden-sm <?=$this->active == 'history' ? ' active' : ''?>">
  <a href="<?=$this->url('search-history')?>?require_login" class="list-group-item">
    <?=$this->transEsc('history_saved_searches')?>
  </a>
</li>
<?php if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
  <?php if ($this->ils()->checkCapability('getMyProfile')): ?>
    <li class="menu-profile  hidden-xs hidden-sm<?=$this->active == 'profile' ? ' active' : ''?>">
      <a href="<?=$this->url('myresearch-profile')?>" class="list-group-item">
        <?=$this->transEsc('Profile')?>
      </a>
    </li>
  <?php endif; ?>
<?php endif; ?>
<?php $menuEntries = ob_get_clean(); ?>

  <div class="mobile-main-tabs visible-xs visible-sm">
    <div class="dropdown useraccount-nav-mobile" role="menu">
      <div class="dropdown-toggle" data-toggle="dropdown">
        <div class="tab-title">
          <?php
            switch ($this->active) {
            case 'profile': echo $this->transEsc('Profile'); break;
            case 'checkedout': echo $this->transEsc('Checked Out Items'); break;
            case 'historicLoans': echo $this->transEsc('Loan History'); break;
            case 'holds': echo $this->transEsc('Holds and Recalls'); break;
            case 'storageRetrievalRequests': echo $this->transEsc('Storage Retrieval Requests'); break;
            case 'ILLRequests': echo $this->transEsc('Interlibrary Loan Requests'); break;
            case 'fines': echo $this->transEsc('Fines'); break;
            case 'librarycards': echo $this->transEsc('Library Cards'); break;
            case 'favorites': echo $this->transEsc('Favorites'); break;
            case 'history': echo $this->transEsc('history_saved_searches'); break;
            default:
                if (substr($this->active, 0, 4) == 'list') {
                    echo $this->transEsc('Favorites');
                    break;
                }
                echo $this->transEsc('Your Account');
                break;
            }
          ?>
        </div>
        <div class="more"><?= $this->transEsc('Your Account') ?><b class="caret"></b></div>
      </div>
      <ul class="dropdown-menu">
        <?=$menuEntriesMobile?>
      </ul>
    </div>
  </div>
  <ul class="<?=$this->layoutClass('sidebar')?> nav-tabs-personal list-group useraccount-nav nav-tabs" role="menu">
    <?=$menuEntries?>
  </ul>

<!-- END of: finna - myresearch/menu.phtml -->
