<!-- START of: finna - myresearch/menu.phtml -->
<?php
    $capabilityParams = [];
    $user = $this->auth()->isLoggedIn();
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $capabilityParams = $patron ? ['patron' => $patron] : [];
    $showLibraryTabs = $this->ils()->loginAvailable();
    $ilsOffline = 'ils-none' === $this->ils()->getOfflineMode();
    $listOpen = $this->active == 'favorites' || substr($this->active, 0, 4) == 'list';
    $activeToLower = strtolower($this->active ?? '');
    //Get the data for vertical menu to show lists on correct site
    if ($listOpen) {
      $list = $this->results->getListObject();
      $listParams = [
        'activeId' => $list['id'],
        'activeUrl' => $this->serverUrl() . $this->url('home') . 'List/' . $list['id'],
        'activePublic' => $list['public'],
        'isDefaultList' => !isset($list),
        'lists' => $user ? $user->getLists() : null,
        'results' => $this->results,
        'user' => $user
      ];
    }

    $menuListItems = [];
    if ($showLibraryTabs && !$ilsOffline) {
      $menuListItems = [
        'checkedout' => [
          'url' => $this->url('myresearch-checkedout'),
          'translation' => $this->transEsc('Checked Out Items')
        ],
        'historicloans' => [
          'url' => $this->url('myresearch-historicloans'),
          'translation' => $this->transEsc('Loan History'),
          'show' => $this->ils()->checkCapability('getMyTransactionHistory', $capabilityParams)
        ],
        'holds' => [
          'active' => $this->active === 'holds',
          'url' => $this->url('myresearch-holds'),
          'translation' => $this->transEsc('Holds and Recalls')
        ],
        'storageretrievalrequests' => [
          'url' => $this->url('myresearch-storageretrievalrequests'),
          'translation' => $this->transEsc('Storage Retrieval Requests'),
          'show' => $this->ils()->checkFunction('storageRetrievalRequests', $capabilityParams)
        ],
        'illrequests' => [
          'url' => $this->url('myresearch-illrequests'),
          'translation' => $this->transEsc('Interlibrary Loan Requests'),
          'show' => $this->ils()->checkFunction('ILLRequests', $capabilityParams)
        ],
        'fines' => [
          'url' => $this->url('myresearch-fines'),
          'translation' => $this->transEsc('Fines')
        ],
        'librarycards' => [
          'url' => $this->url('librarycards-home'),
          'translation' => $this->transEsc('Library Cards'),
          'show' => $user && $user->libraryCardsEnabled()
        ]
      ];
    }

    $nonLibraryItems = [
      'profile' => [
        'url' => $this->url('myresearch-profile'),
        'translation' => $this->transEsc('Profile'),
        'show' => !$ilsOffline && $this->ils()->checkCapability('getMyProfile')
      ],
      'history' => [
        'url' => $this->url('search-history') . "?require_login",
        'translation' => $this->transEsc('history_saved_searches')
      ],
      'favorites' => [
        'url' => $this->url('myresearch-favorites'),
        'translation' => $this->transEsc('Favorites'),
        'show' => $this->userlist()->getMode() !== 'disabled'
      ],
      'logout' => [
        'url' => $this->url('myresearch-logout'),
        'translation' => $this->transEsc('Log Out'),
        'iconClass' => 'pull-right fa fa-sign-out fa-lg',
        'desktopOnly' => true
      ]
    ];
    $menuListItems = array_merge($menuListItems, $nonLibraryItems);

    $desktopList = [
      'open-loans' => [
        'active' => in_array($activeToLower, ['checkedout', 'historicloans', 'holds', 'storageretrievalrequests', 'illrequests']),
        'url' => $this->url('myresearch-checkedout'),
        'translation' => $this->transEsc('Checked Out Header'),
        'dropdown' => true,
        'ulId' => 'myLoans',
        'show' => !$ilsOffline && $showLibraryTabs,
        'children' => [
          'checkedout',
          'historicloans',
          'holds',
          'storageretrievalrequests',
          'illrequests'
        ]
      ],
      'fines',
      'librarycards',
      'profile',
      'history',
      'open-list' => [
        'active' => $listOpen,
        'url' => $this->url('myresearch-favorites'),
        'translation' => $this->transEsc('Favorites'),
        'show' => $this->userlist()->getMode() !== 'disabled',
        'partial' => [
          'url' => 'myresearch/mylist-navi.phtml',
          'wrapperClass' => 'mylist-bar',
          'params' => $listParams ?? []
        ]
      ],
      'logout'
    ];

    $headerKey = substr($activeToLower, 0, 4) === 'list' ? 'favorites' : $activeToLower;
    $activeMobileTab = $menuListItems[$headerKey]['translation'] ?? $this->transEsc('Your Account');
?>

<div class="mobile-main-tabs visible-xs visible-sm">
  <div class="dropdown useraccount-nav-mobile" role="menu">
    <div class="dropdown-toggle" data-toggle="dropdown">
      <div class="tab-title">
        <?=$activeMobileTab?>
      </div>
      <div class="more"><?= $this->transEsc('Your Account') ?><b class="caret"></b></div>
    </div>
    <ul class="dropdown-menu">
      <?php foreach ($menuListItems as $id => $listItem) : ?>
        <?php if (isset($listItem['desktopOnly']) && $listItem['desktopOnly']) { continue; } ?>
        <?php if (!isset($listItem['show']) || $listItem['show'] !== false): ?>
          <li role="menuitem" class="<?=$id?><?= $activeToLower === $id ? ' active' : ''?>">
            <a href="<?=$listItem['url']?>" class="list-group-item" <?=$activeToLower === $id ? 'aria-current="page"' : ''?>>
            <?=$listItem['translation']?>
            </a>
          </li>
        <?php endif; ?>
      <?php endforeach; ?>
    </ul>
  </div>
</div>

<ul class="<?=$this->layoutClass('sidebar-myresearch')?> <?= $listOpen ? '' : 'move-list' ?> nav-tabs-personal list-group useraccount-nav nav-tabs" role="menu">
  <li class="menu-header hidden-xs hidden-sm">
    <h1>
      <?= $this->transEsc('Your Account') ?>
      <?php if (!$this->translationEmpty('tooltip_myaccount_html')): ?>
        <span class="tooltip-myaccount" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="<?= $this->transEsc("tooltip_myaccount_html") ?>"><i class="fa fa-info-big"></i></span>
      <?php endif; ?>
    </h1>
  </li>
  <?php foreach ($desktopList as $id => $value) : ?>
  <?php
    $isArray = is_array($value);
    $listItem = $isArray ? $value : $menuListItems[$value];
    if (isset($listItem['show']) && !$listItem['show']) {
      continue;
    }
    $name = $isArray ? $id : $value;
    $hasChildren = $listItem['children'] ?? false;
    $hasPartial = $listItem['partial'] ?? false;
    $showSpinner = $listItem['showSpinner'] ?? false;
  ?>
    <?php if ($hasChildren || $hasPartial): ?>
      <li role="menuitem" class="dropdown <?= $listItem['active'] ? ' active' : ''?>">
        <a href="<?=$listItem['url']?>" id="<?=$id?>" class="hidden-xs hidden-sm list-group-item <?= !$listItem['active'] ? 'collapsed' : '' ?>" >
          <?=$listItem['translation']?>
          <?php if ($showSpinner) : ?>
            <i class="hidden fa fa-spinner fa-spin"></i><span class="ajax-error hidden"><small> <?=$this->translate('An error has occurred'); ?></small></span>
          <?php endif; ?>
          <span class="caret"></span>
        </a>
        <?php if ($hasPartial) : ?>
          <div class="<?= $value['partial']['wrapperClass'] ?? 'ajax-wrapper'?>">
            <?php if ($listItem['active']): ?>
              <?= $this->partial($value['partial']['url'], $value['partial']['params']); ?>
            <?php endif; ?>
          </div>
        <?php else: ?>
          <ul id="<?=$listItem['ulId']?>" role="presentation" class="dropdown-menu subtabs collapse <?= $listItem['active'] ? ' in' : ''?>">
            <?php foreach ($listItem['children'] as $childKey) : ?>
              <?php
                $childItem = $menuListItems[$childKey] ?? ['show' => false];
                if (isset($childItem['show']) && !$childItem['show']) { continue; }
              ?>
                <li role="menuitem" class="<?="menu-$name"?>  <?=$activeToLower === $childKey ? ' active' : ''?>">
                  <a href="<?=$childItem['url']?>" class="list-group-item" <?=$activeToLower === $childKey ? 'aria-current="page"' : ''?>>
                    <?=$childItem['translation']?>
                  </a>
                </li>
            <?php endforeach; ?>
          </ul>
        <?php endif; ?>
      </li>
    <?php else: ?>
      <li role="menuitem" class="hidden-xs hidden-sm <?="menu-$name"?> <?=$activeToLower === $name ? ' active' : ''?>">
        <a href="<?=$listItem['url']?>" class="list-group-item" <?=$activeToLower === $name ? 'aria-current="page"' : ''?>>
          <?=$listItem['translation']?>
          <?php if (isset($listItem['iconClass'])): ?>
            <i class="<?=$listItem['iconClass']?>" aria-hidden="true"></i>
          <?php endif; ?>
        </a>
      </li>
    <?php endif; ?>
  <?php endforeach; ?>
</ul>

<script>
    finna.menu.init();
</script>

<!-- END of: finna - myresearch/menu.phtml -->
