<!-- START of: finna - myresearch/mylist-navi.phtml -->
<?php
  $currentLimit = 20; // default limit for favorites
  if (isset($this->results)) {
     $limitList = $this->results->getParams()->getLimitList();
     foreach ($limitList as $limitVal => $limitData) {
        if ($limitData['selected']) {
          $currentLimit = $limitVal;
          break;
        }
     }
  }
?>
<ul class="dropdown-menu subtabs collapse show" role="presentation">
  <?php foreach ($lists as $current): ?>
    <?php
      // Back-compatibility:
      $list = $current['list_entity'] ?? $current;
    ?>
    <?php $active = ($list && $list->getId() === $activeId); ?>
    <li role="none" class="favorites-menulist-item">
      <a role="menuitem" data-lightbox-ignore href="<?= $active ? '#' : $this->url('userList', ['id' => $list->getId()])?>?limit=<?=$currentLimit;?>" class="dropdown-item<?=$list && $active ? ' active' : ''?>" aria-current="<?=$active ? 'page' : 'false' ?>">
        <div class="favorite-list-holder">
          <div class="float-start favorite-list-title"><?=$this->escapeHtml($list->getTitle())?></div>
          <?php if ($list->isPublic()): ?>
            <?=$this->icon('public') ?>
          <?php endif; ?>
          <div class="float-end">(<?=$current['count']?>)</div>
        </div>
      </a>
    </li>
  <?php endforeach; ?>
  <li class="add-new-list-holder favorites-menulist-item">
    <form method="POST" action="<?=$this->url('editList') ?>" data-lightbox-ignore class="d-flex align-items-center flex-wrap">
      <input type="hidden" name="id" value="NEW">
      <input type="text" name="title" class="form-control mt-2" placeholder="<?=$this->transEscAttr('Create a new list') ?>">
      <input type="submit" name="submitButton" class="btn btn-primary btn-sm mt-2" value="<?=$this->transEscAttr('Create a List') ?>">
    </form>
  </li>
</ul>
<!-- END of: finna - myresearch/mylist-navi.phtml -->
