<p><?=$this->transEsc('list-tags-count', ['%%count%%' => count($this->tags)])?></p>
<ul>
  <?php foreach ($this->tags as $tag): ?>
    <li class="tag"><span class="text"><?= !$this->translationEmpty("tag_{$tag->tag}") ? $this->transEsc("tag_{$tag->tag}") : $tag->tag ?></span> <button class="delete-tag" aria-label="<?=$this->transEsc('Delete')?>"><i class="fa fa-button fa-times"></i></button></li>
  <?php endforeach ?>
</ul>
