<!-- START of: finna - myresearch/mylist.phtml -->
<?php
  // Grab list object from search results (if applicable):
  $list = $this->results->getListObject();

  $this->layout()->finnaUserAccountHeading = 'useraccount-content-heading';

  // Set up breadcrumbs:
  $currPage = isset($list) ? 'List' : 'saved_items';
  $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
    ->add($this->translate($currPage), active: true);

  // Load Javascript dependencies into header:
  $this->assetManager()->appendScriptLink('check_item_statuses.js');

  // Load Javascript only if list view parameter is NOT full:
  if ($this->params->getOptions()->getListViewOption() != 'full') {
    $this->assetManager()->appendScriptLink('record.js');
    $this->assetManager()->appendScriptLink('embedded_record.js');
  }

  $recordTotal = $this->results->getResultTotal();

  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->getUserObject();

  $lists = $user ? $this->userlist()->getUserListsAndCountsByUser($user) : null;

  $this->jsTranslations()->addStrings(['add_list_description' => 'Add list description', 'loading' => 'Loading']);
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => $list ? ('list' . $list->getId()) : 'favorites']); ?>


<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="mylist-error hidden"><?=$this->translate('An error has occurred'); ?></div>
  <?php if ($list): ?>
    <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->getId())?>">
    <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->getTitle())?>">
  <?php endif; ?>
  <div class="clearfix mylist-header hidden-print" tabindex="0">
    <div>
      <?=$this->flashmessages()?>
    </div>
    <div id="useraccount-content-heading" class="useraccount-header visually-hidden">
      <?=$this->component('page-title', ['title' => $this->translate('saved_items'), 'headTitle' => $this->translate('saved_items')])?>
    </div>
  </div>
  <div class="useraccount-content">
    <?= $this->component('finna-mobile-navigation-btn', ['label' => $this->translate('Favourite lists'), 'target' => '.mylist-bar.mobile-sidebar-container']) ?>
    <?php if ($list && $this->userlist()->userCanEditList($user, $list)): ?>
      <?php $listUrl = $this->url('list-page', ['lid' => $list->getId()], ['force_canonical' => true]) ?>
      <div>
        <h3><?=$this->escapeHtml($list->getTitle())?></h3>
      </div>
      <?php $markdown = $list ? $this->markdown()->replaceDeprecatedTags($list->getDescription() ?? '') : ''; ?>
      <?=$this->markdown()->toHtml($markdown, false);?>
      <?php $listTags = $this->tags()->getListTags($list, $user); ?>
      <?php if ($this->usertags()->getListMode() === 'enabled' && $listTags): ?>
        <?= $this->component('finna-tag-list', ['items' => array_map(fn ($tag) => $tag['tag'], $listTags), 'title' => $this->transEsc('Tags'), 'translateItems' => false]) ?>
      <?php endif; ?>
      <?php if ($list->isPublic()): ?>
        <div class="d-flex flex-column">
          <strong><?=$this->icon('list-public') ?> <?=$this->transEsc('public_list_indicator') ?></strong>
          <div class="list-url d-flex flex-column">
            <a href="<?= $this->url('list-page', ['lid' => $list->getId()], ['force_canonical' => true], ['query' => ['view' => 'rss']]) ?>" class="feed"><?= $this->transEsc('Get RSS Feed') ?></a>
            <a href="<?= $this->url('list-page', ['lid' => $list->getId()], ['force_canonical' => true]) ?>"><?= $this->translate('Public List URL'); ?></a>
          </div>
        </div>
      <?php endif; ?>
      <div class="d-flex justify-content-end mt-4 mb-2 flex-row">
        <a href="<?=$this->url('editList', ['id' => $list->getId()], ['query' => ['ignoreLightbox' => true]]) ?>" class="btn btn-link btn-sm" aria-haspopup="true" data-lightbox="">
          <?=$this->icon('user-list-edit', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('edit_list')?></span>
        </a>
        <?=
          $this->component(
              'confirm-button',
              [
                'buttonLink' => $this->url('myresearch-deletelist', [], ['query' => ['listID' => $list->getId()]]),
                'buttonLabel' => 'delete_list',
                'buttonClass' => 'btn btn-link btn-sm',
                'buttonIcon' => 'user-list-delete',
                'confirmLink' => $this->url('myresearch-deletelist', [], ['query' => ['listID' => $list->getId(), 'confirm' => 1]]),
                'header' => 'confirm_delete_list_text',
              ]
          );
        ?>
      </div>
    <?php endif; ?>
    <?php if ($template = $this->content()->findTemplateForLng('content/Additions/myresearch-favorites')): ?>
      <div class="myresearch-favorites">
        <?=$this->render($template)?>
      </div>
    <?php endif; ?>
    <div class="mylist-header">
      <?php if ($recordTotal > 0): ?>
        <div class="mylist-controls search-controls">
          <div class="pagination-container">
            <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', ['results' => $this->results])?>
          </div>
          <div class="control-container hidden-print">
            <?php if ($list): ?>
              <a class="btn btn-sm btn-primary btn-sort-order" href="<?=$this->url('sortList', ['id' => $list->getId()]) ?>" data-backdrop=”static” data-lightbox><span class="fa fa-sort" aria-hidden="true"></span> <span class="hidden-xs"><?=$this->transEsc('Sort manually');?></span></a>
            <?php endif; ?>
            <?=$this->render('search/controls/sort.phtml')?>
            <?=$this->render('search/controls/limit.phtml')?>
          </div>
        </div>
        <?php $multiPageSelection = ($this->config()->get('config')['Social']['multi_page_favorites_selection'] ?? true) ? ' multi-page-selection' : ''; ?>
        <form class="form<?= $multiPageSelection ?>" id="form-favorites<?= ($list && null !== $list->getId()) ? '-' . $list->getId() : ''?>" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>" data-lightbox data-lightbox-onsubmit="bulkFormHandler">
          <input class="hidden all-ids-global" type="text" name="all_ids_global" value="<?= $this->escapeHtmlAttr(json_encode($this->results->getAllIds())) ?>">
          <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', [
            'idPrefix' => '',
            'list' => $list ?? null,
            'account' => $this->account,
            'lists' => $lists,
            'canDelete' => (null !== $this->list && $this->list->editAllowed($user)) || (null === $this->list && $user),
          ])?>
          <?php foreach ($this->results->getResults() as $i => $current): ?>
            <?=$this->record($current)->getListEntry($list, $user)?>
          <?php endforeach; ?>
        </form>
      <?php else: ?>
        <div class="useraccount-header">
          <h3><?=$this->transEsc('You do not have any saved resources')?></h3>
        </div>
      <?php endif; ?>
    </div>
    <?php if ($recordTotal > 0): ?>
      <div>
        <div class="text-center">
          <hr>
          <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', ['results' => $this->results])?>
        </div>
      </div>
    <?php endif;?>
  </div>
  </div>

<!-- END of: finna - myresearch/mylist.phtml -->
