<!-- START of: finna - myresearch/change-messaging-settings.phtml -->
<?php if (empty($profile['email'])): ?>
  <div class="alert alert-danger">
    <?=$this->transEsc('no_email_address')?>
    <?=$this->transEsc('no_email_address_text')?>
  </div>
<?php else: ?>
    <div class="tab-content">
        <?php foreach($this->profile['messagingServices'] as $service => $data): ?>
            <form method="post" class="messaging-settings-form profile-form">
                <input type="hidden" name="changeMessagingSetting" value="<?=$data['name']?>">
                <div class="my-profile-col profile-title"><?=$this->escapeHtml($data['type'])?></div>
                <div>
                    <select name="option" class="form-control messaging-settings-select">
                        <?php foreach($data['sendMethods'] as $method => $methodData): ?>
                            <?php if (isset($methodData['options'])): ?>
                                <?php foreach($methodData['options'] as $option): ?>
                                    <option value="<?=$this->escapeHtmlAttr($option['value']) ?? ''?>"<?php if($option['selected']): ?> selected<?php endif;?>><?=$this->escapeHtml($option['name'])?></option>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <option value="<?=$this->escapeHtmlAttr($methodData['type']) ?? ''?>"<?php if($methodData['selected'] === 'yes'): ?> selected<?php endif;?>><?=$this->escapeHtml($methodData['method'])?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </div>
            </form>
        <?php endforeach; ?>
    </div>
<?php endif;?>
<script>
    $(document).ready(function () {
        $('.messaging-settings-select').change(function submitForm() {
            $(this).closest('form').submit();
        });
    });
</script>
<!-- END of: finna - myresearch/change-messaging-settings.phtml -->