<!-- START of: finna - content/help-comments-ratings_fi.phtml -->
<?php $this->headTitle($this->translate('tabs_help-comments-ratings'))?>

<?php if ($this->resolver('content/help-tabs.phtml')): ?>
    <?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help-comments-ratings'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <div id="commentsratings" class="content-section">
    <h2>Kommentit ja arviot</h2>
    <p>Finnassa voit kommentoida kaikkia sieltä löytyviä aineistoja. Lisäksi joihinkin aineistoihin, kuten kirjoihin, voit lisätä arvion eli 1-5 tähteä.</p>
    <p>Kommentoimiseen ja arvioimiseen tarvitset Finna-tilin. Ohjeet Finna-tilin luomiseen löydät <a href="https://finna.fi/Content/help-account">täältä</a>.</p>
    <p>Aineistoja hallinnoivat organisaatiot seuraavat omiin aineistoihinsa liittyviä kommentteja ja ovat velvoitettuja tarvittaessa moderoimaan niitä. Tämä tarkoittaa, että organisaatiot voivat piilottaa sopimattomia tai tarpeettomia kommentteja. Voit myös itse ilmiantaa sopimattomia kommentteja aineiston Kommentit-välilehdellä.</p>
    <p>Moderoija noudattaa moderointiperiaatteita, kun hän päättää kommentin piilottamisesta. Erityisesti muiden käyttäjien ilmiantamat kommentit tarkistetaan erikseen. Ota tarvittaessa yhteyttä aineiston tarjoavaan organisaatioon. Organisaatioiden perustelut kommentoinnin moderointiin löydät Finnan kommentointiperiaatteet -ohjeesta.</p>
    <p>Näet omat kommenttisi ja arviosi Oma tili -valikon Kommentit ja arviot -osioista. Näet sieltä myös mahdollisesti moderoijan piilottamat kommenttisi. Kommenteistasi löydät linkin tietuesivuun, josta pääset muokkaamaan tai poistamaan kommenttisi.</p>
  </div>
  <div id="commentguidelines" class="content-section">
    <h2>Finna kommenterenprinsihpat</h2>
    <p>Čuovo buriid dábiid ja lága, ja gudnejahte eará geavaheaddjiid. Čuovvovaš kommeanttat čihkkojuvvojit:</p>
    <ul class="list-bullets">
      <li>Lágavuostásaš kommeanttat</li>
      <li>Heivemeahttun kommeanttat</li>
      <li>Áššái laktáskeahtes dahje buori dábi vuostásaš kommeanttat</li>
    </ul>
    <p>Finnas máinnusteapmi dahje liŋkkaid lasiheapmi ii leat lobálaš. Čuovvovaš kommeanttat čihkkojuvvojit:</p>
    <ul class="list-bullets">
      <li>Liŋkkaid sisdoalli kommeanttat. Kommeanttain eai galggašedje leat liŋkkat olggobealat siidduide diehtodorvoriskka dihte.</li>
      <li>Kommeanttat, maid ulbmilin lea gávppálaččat láidet geavaheaddji ovdamearkka dihte kommenterejeaddji iežas bloggii dahje eará bálvalussii. Máinnusteapmi Finnas ii leat lobálaš.</li>
    </ul>
    <p>
      Vaikko livččii sierra oaivilis duoji dahkkiiguin, ii galgga fallehit kommeanttain olbmo vuostá. Oažžu leat eahpideaddji dahje kritihkalaš, muhto kommeanttat galggašedje bissut áššálažžan, eaige mannat persovnnalaš áššiide. Finnas almmustahtton govvamateriálas sáhttá dovdat oahpes olbmuid. Jus jearaldagas lea vejolaččat ealli olmmoš, gii ii leat almmusvuođas, dán olbmo dieđuid ii oaččo almmustahttit almmolaš bálvalusas.
    </p>
    <p> Čuovvovaš prinsihpaid vuostásaš kommeanttat čihkkojuvvojit:</p>
    <ul class="list-bullets">
      <li><a href="https://commission.europa.eu/law/law-topic/data-protection/rules-business-and-organisations/legal-grounds-processing-data/sensitive-data/what-personal-data-considered-sensitive_fi">Árgalunddolaš heaggadieđuid</a> dahje geange priváhtaeallimii gullevaš áššiid sisdoalli kommeanttat. Suodjalit earáid priváhtavuođa.</li>
      <li>Vejolaččat ealli, ovttaskas olbmo namaheapmi ii leat lobálaš jus dat ii boađe ovdan juo materiála oktavuođas dahje jearaldagas ii leat dovddus almmolašvuođa olmmoš.</li>
      <li>Dahkki dahje materiála eará olbmuid sohkabeallái, ahkái, sohkaduogážii, gillii, oskkoldahkii dahje eará persovnnalaš iešvuhtii laktáseaddji loavkideaddji kommeanttat. Kommeantta sisdoallu galggašii laktásit materiálii.</li>
    </ul>

    <p>Doallat dan lassin gitta čuovvovaš prinsihpain, vai kommeanttagieddi bálvalivččii nu bures go vejolaš.</p>
    <ul class="list-bullets">
      <li>Fiktiivvalaš materiála, nugo girjjiid ja ealligovaid jutnii laktáseaddji kommeanttaid galggašii guođđit eret kommeanttain.</li>
      <li>Jearaldagat materiála fáladeaddjái ja geavahanváttisvuođat sáddejuvvojit váldoáššis daidda dárkkuhuvvon skoviiguin.</li>
    </ul>
    <p>Sáhtát maiddái dárbbu mielde hábmet dahje sihkkut iežat kommeanttaid.</p>
    <p>Du kommeanttat almmustahttojuvvojit du namain dahje nammamearkkain buot Finna-ohcanbálvalusain ja -neahttagirjerájuin, main materiála lea oidnosis. Buot kommeanttat leat almmolaččat. Sáhtát váldit nammamearkka geavahussii ja molsut dan <a href="<?=$this->url('myresearch-profile')?>">dáppe.</p>
  </div>
</div>
<!-- END of: finna - content/help-comments-ratings_fi.phtml -->
