<!-- START of: finna - content/help_advanced_fi.phtml -->
<? if ($this->resolver('Content/help-tabs.phtml')): ?>
    <?=$this->render('Content/help-tabs.phtml', ['activeTab' =>  'help-advanced'])?>
<? endif; ?>
<div>
  <div class="sidebar left">
    <div class="content-navigation-menu">
    </div>
  </div>
  <div class="mainbody right">
      <? if ($this->resolver('Content/Additions/helpBegin.phtml')): ?>
          <?=$this->render('Content/Additions/helpBegin.phtml')?>
      <? endif; ?>
      <p><a href="<?=$this->url('search-advanced')?>">Tarkennettuun hakuun</a> pääsee etusivulta hakupalkin alapuolella olevasta linkistä.</p>
    <div class="content-section">
      <h2>Hakuehdot</h2>
      <p>Tarkennetussa haussa kohdassa Hakuehdot on useita hakukenttiä, joihin voi kirjoittaa hakusanoja ja -lausekkeita.</p>
      <p>Jokaisen hakukentän vieressä on alasvetovalikko, josta voi valita, mihin tietueen kenttään haku kohdistetaan (kaikki kentät, nimeke, tekijä, aihe jne.).</p>
      <p>Useita hakusanoja yhdistelevä haku onnistuu käyttämällä useampaa hakukenttää samanaikaisesti. Hakukenttien vieressä oleva Hae-alasvetovalikko määrittelee, miten useita hakukenttiä sisältävä kysely käsitellään:</p>
      <ul class="list-bullets">
        <li><strong>Kaikilla hakusanoilla (AND)</strong> – Tuottaa hakutuloksia, jotka täsmäävät kaikkien hakukenttien sisältöön.</li>
        <li><strong>Millä tahansa hakusanalla (OR)</strong> – Tuottaa hakutuloksia, jotka täsmäävät yhden tai useamman hakukentän sisältöön.</li>
        <li><strong>Ei millään hakusanoista (NOT)</strong> – Tuottaa hakutuloksia, joissa ei esiinny yhdenkään hakukentän sisältöä. Tätä kannattaa käyttää, jos ei halua jonkin tietyn hakusanan sisältyvän lainkaan hakuun.</li>
      </ul>
      <ul class="list-bullets">
        <li><strong>Lisää hakukenttä</strong> –painikkeella lomakkeelle pystyy lisäämään uuden hakukentän.</li>
        <li><strong>Lisää hakuryhmä)</strong> –painike lisää uuden ryhmän hakukenttiä. Poista hakuryhmä –painikkeella kyseisiä ryhmiä voidaan poistaa.</li>
        <li>Hakuryhmien välisiä suhteita määritellään käyttäen <strong>Kaikki ryhmät (AND) ja Mitkä tahansa ryhmät (OR)</strong> –hakuoperaattoreita.</li>
      </ul>
    </div>
    <div id="limits" class="content-section">
      <h2>Rajaukset</h2>
      <p>Tarkennettua hakua voi rajata sisältämään aineistoa tietyllä kielellä, aineistotyypin sekä valmistusvuoden mukaan.</p>
      <p>Kieliä ja aineistotyyppejä voi olla useampia samassa haussa.</p>
    </div>
    <div id="geo" class="content-section">
      <h2>Maantieteellinen alue</h2>
      <p>Suomen kartalta voi valita tietyn alueen, miltä aineistoa haluaa hakuun tulevan. Karttaa voi zoomata lähemmäksi tai loitontaa sen mukaan, kuinka laajalle alueelle haluaa laittaa rajauksen.</p>
    </div>
      <? if ($this->resolver('Content/Additions/helpEnd.phtml')): ?>
          <?=$this->render('Content/Additions/helpEnd.phtml')?>
      <? endif; ?>
  </div>
</div>
<!-- END of: finna - content/help_advanced_fi.phtml -->
