<?php
  $__attributes = $this->htmlAttributes($attributes ?? []);
  $__headingTag = 'h3';
?>
<section<?= $__attributes->add('class', 'finna-educational-level-data') ?>>
  <?php if (!empty($studyContents)): ?>
    <section>
      <<?= $__headingTag ?>><?= $this->escapeHtml($studyContentsTitle ?? '') ?></<?= $__headingTag ?>>
      <ul>
        <?php foreach ($studyContents ?? [] as $__subject => $__values): ?>
          <li>
            <dl>
              <dt><?= $this->escapeHtml($__subject) ?>:</dt>
              <?php foreach ($__values as $__value): ?>
                <dd><?= $this->escapeHtml($__value) ?></dd>
              <?php endforeach; ?>
            </dl>
          </li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (!empty($studyObjectives)): ?>
    <section>
      <<?= $__headingTag ?>><?= $this->escapeHtml($studyObjectivesTitle ?? '') ?></<?= $__headingTag ?>>
      <ul>
        <?php foreach ($studyObjectives ?? [] as $__subject => $__values): ?>
          <li>
            <dl>
              <dt><?= $this->escapeHtml($__subject) ?>:</dt>
              <?php foreach ($__values as $__value): ?>
                <dd><?= $this->escapeHtml($__value) ?></dd>
              <?php endforeach; ?>
            </dl>
          </li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (!empty($transversalCompetences)): ?>
    <section>
      <<?= $__headingTag ?>><?= $this->escapeHtml($transversalCompetencesTitle ?? '') ?></<?= $__headingTag ?>>
      <ul>
        <?php foreach ($transversalCompetences as $__transversalCompetence): ?>
          <li><?= $this->escapeHtml($__transversalCompetence) ?></li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (!empty($vocationalUnits)): ?>
    <section>
      <<?= $__headingTag ?>><?= $this->escapeHtml($vocationalUnitsTitle ?? '') ?></<?= $__headingTag ?>>
      <ul>
        <?php foreach ($vocationalUnits ?? [] as $__subject => $__values): ?>
          <li>
            <dl>
              <dt><?= $this->escapeHtml($__subject) ?>:</dt>
              <?php foreach ($__values as $__value): ?>
                <dd><?= $this->escapeHtml($__value) ?></dd>
              <?php endforeach; ?>
            </dl>
          </li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (!empty($vocationalCommonUnits)): ?>
    <section>
      <<?= $__headingTag ?>><?= $this->escapeHtml($vocationalCommonUnitsTitle ?? '') ?></<?= $__headingTag ?>>
      <ul>
        <?php foreach ($vocationalCommonUnits as $__vocationalCommonUnit): ?>
          <li><?= $this->escapeHtml($__vocationalCommonUnit) ?></li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (isset($objective)): ?>
    <section class="finna-educational-level-objective">
      <<?= $__headingTag ?>><?= $this->escapeHtml($objectiveTitle ?? '') ?></<?= $__headingTag ?>>
      <p><?= $this->escapeHtml($objective) ?></p>
    </section>
  <?php endif; ?>
</section>
