<?php
  $lastItem = end($items);
  $hasImg = !empty($item['image']['url']);
?>
<?php if ($element != $lastItem['id']): ?>
  <h3 class="next-articles-header"><?=$this->translate('Read next')?></h3>
<?php endif ?>
<?php $cnt = $from = $to = 0; ?>
<div class="next-articles-grid">
<?php foreach ($this->items as $item): ?>
  <?php
    $hasImg = !empty($item['image']['url']);
    $selected = $numeric
      ? $element === $cnt
      : $element === $item['id'];

    $link = $item['link'];
    if ($this->feedUrl) {
      $link .= strpos($item['link'], '?') === false ? '?' : '&';
      $link .= 'feedUrl=' . urlencode($this->feedUrl);
    }
    if ($selected) {
      $from = $cnt;
      $to = $selected + $nextArticles;
    }
    if (!$selected && $to === 0) {
      continue;
    }
    if ($cnt === $to && $cnt !== 0) {
      break;
    }
  ?>
  <?= !$selected ? ( '<div class="article">' . ($hasImg ? '<div class="article-image">' . '<a href="' . $this->escapeHtmlAttr($link) . '">' . '<img src="' . $item['image']['url'] . '"' . 'alt="" />' . '</a></div>': '</a>') . '<div class="article-details">' .'<span class="publish-date">' . $this->transEsc('Published') . ' ' . $this->escapeHtml($item['dateFull'])) . '</span>' . '<span class="article-title">' . '<a href="' . $this->escapeHtmlAttr($link) . '">' . $this->escapeHtml($item['title']) . '</a>' .'</span>' . '</div>' . '</div>' : null ?>
  <?php ++$cnt; ?>
<?php endforeach;?>
</div>
