<?
  $this->headLink()->appendStylesheet('vendor/leaflet.css');
  $this->headLink()->appendStylesheet('vendor/leaflet.draw.css');
  $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/leaflet.js');
  $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/leaflet.draw.js');
  $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'finna-map-facet.js');

  $this->jsTranslations()->addStrings(
    [
      'radiusPrefix' => 'Radius',
      'circleCaption' => 'Select Area',
      'clearCaption' => 'Clear Selections',
      'removeCaption' => 'Clear',
      'map_zoom_in' => 'map_zoom_in',
      'map_zoom_out' => 'map_zoom_out'
    ]);
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<?=$this->headLink()?>
<?
  $geoFilters = $this->params->getGeographicFilters($this->params->getFilterList());
  $mapPopupUrl = $this->url('search-mapfacet') . $results->getUrlQuery()->getParams(false);
?>

<div class="geographic-facet">
  <? if(empty($geoFilters)):?>
    <a class="btn" href="<?=$mapPopupUrl ?>" data-lightbox>TODO: Rajaa karttasijainnilla</a>
  <? else: ?>
    <div class="map" style="height: 200px"></div>
    <div class="street-map-controls text-center">
      <a class="btn map-control" href="<?=$mapPopupUrl?>" data-lightbox><span>TODO: Valitse alue</span></a>
    </div>
  <? endif; ?>
</div>
<div class="list-group-item facet-info">
  <i class="fa fa-info-big-2"></i><div class="info"><?=$this->transEsc('geographic_facet_info')?></div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    var options = {
      items: []
    };
    <? foreach ($geoFilters as $filter): ?>
      <? foreach (preg_split('/\s+OR\s+/', $filter) as $item): ?>
        options.items.push('<?=$this->escapeJs($item) ?>');
      <? endforeach; ?>
    <? endforeach; ?>
    finna.MapFacet.initFacetMap(options);
  });
</script>