<?
$this->headLink()->appendStylesheet('vendor/leaflet.css');
$this->headLink()->appendStylesheet('vendor/leaflet.draw.css');
$this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/leaflet.js');
$this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/leaflet.draw.js');
$this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'finna-map-facet.js');
echo $this->inlineScript();
?>
<?=$this->headLink()?>
<?
$geoFilters = $this->params->getGeographicFilters($this->params->getFilterList());
?>

<div class="geographic-facet">
  <? if(empty($geoFilters)):?>
    <div class="btn open-map-popup">TODO: Rajaa karttasijainnilla</div>
  <? else: ?>
    <div class="map" style="height: 200px"></div>
    <div class="street-map-controls text-center">
      <a class="btn map-control" href="<?=$this->url('search-streetsearch')?>?go=1"><i class="fa fa-crosshairs"></i> <span><?=$this->transEsc('street_search_refresh')?></span></a>
      <a class="btn map-control open-map-popup" href="#"><span>TODO: Valitse alue</span></a>
    </div>
  <? endif; ?>
</div>
<div class="list-group-item facet-info">
  <i class="fa fa-info-big-2"></i><div class="info"><?=$this->transEsc('geographic_facet_info')?></div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    var options = {
      items: []
    };
    <? foreach ($geoFilters as $filter): ?>
      <? foreach (preg_split('/\s+OR\s+/', $filter) as $item): ?>
        options.items.push('<?=$this->escapeJs($item) ?>');
      <? endforeach; ?>
    <? endforeach; ?>
    finna.MapFacet.init(options);
  });
</script>