<!-- START of: finna2 - Recommend/SideFacets/usage-rights-facet-info.phtml -->
<div class="list-group-item facet-info">
  <i class="fa fa-info3"></i><div class="info"><?=$this->transEsc('usage_rights_info')?></div><a class="more-info" href="<?=$this->url('content-page', ['page' => 'terms'])?>#terms"><?=$this->transEsc('usage_rights_info_more')?></a>
</div>
<?php if (!$this->translationEmpty('usage_rights_details')): ?>
  <div class="list-group-item facet-info">
    <i class="fa fa-info3"></i><div class="info"><?=$this->transEsc('usage_rights_details')?></div>
  </div>
<?php endif; ?>
<!-- END of: finna2 - Recommend/SideFacets/usage-rights-facet-info.phtml -->
