<!-- START of: finna - RecordDriver/SolrLido/core.phtml -->
<?php
  $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
  $img = $this->recordImage($this->record($this->driver));
  $images = $img->getAllImagesAsCoverLinks(
      $this->layout()->userLang, $params
  );

  $urls = $this->record($this->driver)->getLinkDetails();
  if (!empty($urls)){
      $videoUrls = [];
      $audioUrls = [];
      $otherUrls = [];
      foreach ($urls as $url){
          if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLink()->getEmbeddedVideo($url['url']) == 'data-embed-iframe'){
            array_push($videoUrls, $url);
          } elseif (!empty($url['embed']) && $url['embed'] == 'audio') {
            array_push($audioUrls, $url);
          } else {
            array_push($otherUrls, $url);
          }
      }
  }

  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
  ob_start(); ?>
  <div class="media-<?=$thumbnailAlignment ?>">

    <div class="image-information">
      <div class="cover-wrapper">
        <?php /* Display thumbnail if appropriate: */ ?>
        <?php if ($img): ?>
          <?=$img->render('record', ['small' => ['w' => 50, 'h' => 50], 'medium' => ['w' => 1200, 'h' => 1200]]) ?>
        <?php endif;?>
        <?php /* Display qrcode if appropriate: */ ?>
        <?php $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
        <?php if ($QRCode): ?>
          <div class="visible-print inline-block"><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/></div>
        <?php endif; ?>
      </div>
      <?php // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?=$this->record($this->driver)->getPreviews()?>
    </div>

    <?php if (!empty($videoUrls)): ?>
      <?=$this->record($this->driver)->renderTemplate('record-video-player.phtml', ['videoUrls' => $videoUrls, 'type' => 'SolrLido']);?>
    <?php endif; ?>

    <?php if (!empty($audioUrls)): ?>
      <?=$this->record($this->driver)->renderTemplate('record-audio-player.phtml', ['audioUrls' => $audioUrls]);?>
    <?php endif; ?>

    <?php if ($this->resolver('record/record-organisation-menu.phtml') && $this->driver->getSourceIdentifier() == 'Solr'): ?>
      <div class="organisation-menu">
          <?=$this->render('record/record-organisation-menu.phtml') ?>
      </div>
    <?php endif; ?>

    <div class="record-rating text-left">
      <div class="rating-stars">
        <div onclick="$('a.usercomments').click();">
          <?=$this->record($this->driver)->getRating()?>
        </div>
      </div>
    </div>
    <?php if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-toolbar")): ?>
    <div class="record-post-toolbar">
      <?=$this->render($template)?>
    </div>
    <?php endif; ?>
  </div>
  <?php $thumbnail = ob_get_contents(); ?>
  <?php ob_end_clean(); ?>
  <?php $this->headScript()->appendFile("finna-record.js"); ?>
  <div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
    <?php
    $mediaTitle = $this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection());
    ?>
    <h1 property="name" class="record-title visible-xs"><?=$mediaTitle?></h1>
    <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>
      <div class="media-body record-information">
        <h3 property="name" class="record-title hidden-xs"><?=$mediaTitle?></h3>
        <?php if ($results = $this->driver->getAlternativeTitles()): ?>
          <div class="recordAltTitles record-alt-titles">
            <?=implode('<br>', array_map([$this, 'escapeHtml'], $results))?>
          </div>
        <?php endif; ?>

        <div class="record-core-metadata">
          <?php if ($results = $this->driver->getNonPresenterAuthors()): ?>
            <div class="truncate-field">
            <?php foreach($results as $index => $author): ?>
                <?php
                $mark = $index > 0 ? '; ' : '';
                $authorLink = $this->record($this->driver)->getLink('author', $author['name']);
                $authorName = $this->escapeHtml($author['name']);

                if (!empty($author['date'])) {
                  $authorDate = ', ' . $author['date'];
                }
                if (!empty($author['role'])) {
                  $authorRole = ', ' . mb_strtolower($this->transEsc('CreatorRoles::' . $author['role']), 'UTF-8');
                }
                ?>
                <?=$mark?><a href="<?=$authorLink?>"><?=$authorName?></a><?php if (!empty($author['date'])): ?><span class="author-date"><?=$authorDate?></span><?php endif; ?><?php if (!empty($author['role'])): ?><span class="author-role"><?=$authorRole?></span><?php endif; ?>
              <?php endforeach; ?>
              <?php if ($dates = $this->driver->getResultDateRange()): ?>
                <?=$this->escapeHtml($dates[0]);?><?php if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><?php endif; ?>
              <?php endif; ?>
              <?php if (($results = $this->driver->getSubjectDates()) && !isset($dates[0])): ?>
                <?=implode('<br/>', array_map([$this, 'escapeHtml'], $results))?>
              <?php endif; ?>
            </div>
          <?php endif; ?>
        </div>

        <?php $summary = $this->driver->getSummary(); $summary = $summary[0] ?? false; ?>
        <?php if ($summary): ?>
          <div class="truncate-field wide recordSummary">
            <p class="summary"><?=preg_replace('/&lt;br\/?&gt;/', '<br>', $this->escapeHtml($summary)); /* Allow <br> tag */ ?></p>
          </div>
        <?php endif; ?>

        <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
          <?php /* Display the lists that this record is saved to */ ?>
          <div class="savedLists" id="savedLists">
            <strong><?=$this->transEsc("Saved in")?>:</strong>
          </div>
        <?php endif; ?>

        <?/* Display Main Details */?>
        <?php
          $formatter = $this->recordDataFormatter();
          $coreFields = $formatter->getData(
              $driver, $formatter->filterLidoFields($formatter->getDefaults('core'))
          );
        ?>
        <?php if (!empty($coreFields)): ?>
          <table class="table table-finna-record record-details">
            <?=$this->record($this->driver)->renderTemplate('core-fields.phtml', ['coreFields' => $coreFields]);?>
          </table>
        <?php endif; ?>
        <?/* End Main Details */?>

        <?php if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
        <div>
          <?=$this->render($template)?>
        </div>
        <?php endif; ?>
      </div>
    <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>
</div>
<!-- END of: finna - RecordDriver/SolrLido/core.phtml -->
