<?php //Don't add START and END comments ?>
<div class="truncate-field" data-rows="2">
    <?php foreach ($data as $url): ?>
        <?php
            $displayValue = $url['value'] ?? $url['url'];
            if (!empty($url['label'])) {
                $displayValue .= " ({$url['label']})";
            }
        ?>
        <div class="detailed-url">
            <a href="<?=$this->escapeHtmlAttr($url['url'])?>" target="_blank"><?=$this->escapeHtml($displayValue)?></a>
            <?php if (!empty($url['afterUrl'])): ?>
                <div><?=$this->escapeHtml($url['afterUrl'])?></div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
