<?php //Don't add START and END comments ?>
<div class="truncate-field" data-rows="2">
<?php foreach ($data as $url): ?>
    <?php
        $displayValue = $url['value'] ?? $url['url'];
        if (!empty($url['desc'])) {
            $displayValue .= " ({$url['desc']})";
        }
    ?>
    <div class="detailed-url">
        <a href="<?=$this->escapeHtmlAttr($url['url'])?>" target="_blank"><?=$this->escapeHtml($displayValue)?></a>
        <?php if (!empty($url['info'])): ?>
            <div><?=$this->escapeHtml($url['info'])?></div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
