<?php $showDownloadLinks ??= true; ?>
<?php foreach (array_values($documents) as $i => $document): ?>
    <?php
        $language = $this->layout()->userLang;
        $description = ($document['description'] ?? $document['desc'] ?? null) ?: $this->translate('Download the file');
        $rights = $document['rights'] ?? [];
        $copyright = $rights['copyright'] ?? '';
        $link = $rights['link'] ?? '';
        $rightsDescription = $rights['description'] ?? [];
        $format = $document['format'] ?? null;
    ?>
    <?php ob_start(); ?>
    <?php if ($showDownloadLinks): ?>
        <?php $aAttrs = [
            'download' => '',
            'rel' => 'nofollow',
        ]; ?>
        <a href="<?=$this->url('record-downloadfile', [], ['query' => ['id' => $this->driver->getUniqueID(), 'index' => $i, 'format' => $document['format'], 'type' => 'document']])?>" <?=$this->htmlAttributes($aAttrs)?>>
            <?=$this->icon('download')?>
            <?=$this->escapeHtml($description)?>
        </a>
    <?php else: ?>
        <?php $aAttrs = [
            'href' => $this->proxyUrl($document['url']),
            'target' => '_blank',
            'aria-label' => $this->translate('external_online_link'),
        ];
        if ($posterUrl = $document['posterUrl'] ?? null) {
            $aAttrs['data-poster-url'] = $posterUrl;
        }
        if ($downloadOnly = $document['downloadOnly'] ?? null) {
            $aAttrs['download'] = $downloadOnly;
        } ?>
        <a <?=$this->htmlAttributes($aAttrs)?>>
            <?=$this->icon('external-link')?>
            <?=$this->transEscWithPrefix('link_', $description)?>
        </a>
    <?php endif; ?>
    <?php $linkToResource = trim(ob_get_clean()); ?>
    <?php ob_start(); ?>
    <button class="show-hide-button show-info more-link collapsed" data-toggle="collapse" data-target="#cc_info_<?= $i ?>" aria-expanded="false">
        <?=$this->transEsc('copyright_info_show')?> <?=$this->icon('truncate-more')?>
    </button><span>)</span>
    <?php $ccbutton = trim(ob_get_clean());?>
    <li class="fulltextField">
        <div class="lido-link-wrapper <?php if ($rightsDescription):?> additional-info<?php endif; ?>">
            <span class="resource-link"><?=$linkToResource ?></span>
            <?php if ($format || $copyright):?>
                <div class="copyright-wrapper">
                    <span>(</span><?php if ($format):?><span><?=$this->escapeHtml($format)?></span><?php endif; ?><?php if (!$copyright): ?><span>)</span><?php else: ?><?php if ($format):?><span>: </span><?php endif; ?><span class="copyright-icons"><?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $copyright])?></span>
                    <?php if ($link): ?>
                            <a class="copyright-description" href="<?=$this->escapeHtml($link)?>" target="_blank"><?=$this->escapeHtmlAttr($copyright)?></a><?php if ($rightsDescription): ?><?=$ccbutton?><?php else: ?><span>)</span><?php endif; ?>
                        <?php else: ?>
                            <?=$this->escapeHtml($copyright);?><?php if ($rightsDescription): ?><?=$ccbutton?><?php else: ?><span>)</span><?php endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
        <?php if ($rightsDescription): ?>
            <div id="cc_info_<?= $i ?>" class="cc-info collapse">
                <?php foreach ($rightsDescription as $item): ?>
                    <p class="access-rights"><?=$this->escapeHtml((string)$item);?></p>
                <?php endforeach; ?>
                <button class="hide-info less-link" data-toggle="collapse" data-target="#cc_info_<?= $i ?>" aria-expanded="false">
                    <?=$this->transEsc('copyright_info_hide')?> <?=$this->icon('truncate-less')?>
                </button>
            </div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
