<!-- START of: finna - RecordDriver/DefaultRecord/record-models.phtml -->
<?php $modelScripts = $this->partial('Helpers/modeljs-urls.phtml'); ?>
<div class="model-details truncate-field outer" data-rows="4">
    <h5><?= $this->transEsc('models_header') ?></h5>
    <?php
        $settings = $this->driver->getModelSettings();
        $settings['cubemap'] = [
            'path' => $this->imageSrc()->getImagesDirectoryPath() . '/cubemap/',
            'images' => [
                'px.png', 'nx.png', 'py.png', 'ny.png', 'pz.png', 'nz.png'
            ]
        ];
        $recordId = $this->driver->getUniqueID();
    ?>
    <?php foreach ($this->models as $format => $model): ?>
        <?php
            $modelLoadData = [
                'id' => $recordId,
                'index' => $this->index,
                'format' => $format
            ];
        ?>
        <div class="model-container">
            <a href="#" class="model-trigger" data-modelload="<?=htmlspecialchars(json_encode($modelLoadData ?? []), ENT_QUOTES, 'UTF-8');?>" data-settings="<?=htmlspecialchars(json_encode($settings ?? []), ENT_QUOTES, 'UTF-8');?>" data-scripts="<?=$this->escapeHtmlAttr($modelScripts);?>">
                <span><?= $this->transEsc('model_show', ['%%type%%' => $this->transEsc("model_type_$format")]) ?></span>
            </a>
            <a href="https://google.fi">Lataa malli</a>
        </div>
    <?php endforeach; ?>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-models.phtml -->
