<!-- START of: finna - RecordDriver/DefaultRecord/record-models.phtml -->
<?php
    if (empty($this->models)) {
        return;
    }
    $modelScripts = $this->partial('Helpers/modeljs-urls.phtml');
?>
<div class="model-details">
    <strong><?= $this->transEsc('models_header') ?></strong>
    <?php
        $settings = $this->driver->getModelSettings();
        $settings['cubemap'] = [
            'path' => $this->imageSrc()->getImagesDirectoryPath() . '/cubemap/',
            'images' => [
                'px.png', 'nx.png', 'py.png', 'ny.png', 'pz.png', 'nz.png'
            ]
        ];
        $recordId = $this->driver->getUniqueID();
        $i = 0;
    ?>
    <?php if (!empty($settings['debug'])): ?>
        <div class="model-file-wrapper">
            <input type="file" id="model-file" accept=".glb, .gltf" data-settings="<?=htmlspecialchars(json_encode($settings ?? []), ENT_QUOTES, 'UTF-8');?>" data-scripts="<?=$this->escapeHtmlAttr($modelScripts);?>">
        </div>
    <?php endif; ?>
    <?php foreach ($this->models as $format => $model): ?>
        <?php
            $modelLoadData = [
                'id' => $recordId,
                'index' => $this->index,
                'format' => $format
            ];
        ?>
        <?php if ($model['type'] === 'preview_3d'): ?>
            <div class="model-container open-link">
                <a href="#" class="model-trigger" data-modelload="<?=htmlspecialchars(json_encode($modelLoadData ?? []), ENT_QUOTES, 'UTF-8');?>" data-settings="<?=htmlspecialchars(json_encode($settings ?? []), ENT_QUOTES, 'UTF-8');?>" data-scripts="<?=$this->escapeHtmlAttr($modelScripts);?>">
                    <span><?= $this->transEsc('model_show', ['%%type%%' => $this->transEsc("model_type_$format")]) ?></span>
                </a>
            </div>
        <?php elseif ($model['type'] === 'provided_3d'): ?>
            <div class="model-download open-link">
                <i aria-hidden="true" class="fa fa-download"></i><a href="https://google.fi">Lataa malli</a>
            </div>
        <?php endif; ?>
        <button class="toggle-model-information collapsed" data-toggle="collapse" data-target="#model_details_<?=$this->index?>_<?=$i?>" aria-expanded="false" aria-controls="model_details_<?=$this->index?>_<?=$i?>">
            <span class="show-model-information"><i class="fa fa-arrow-down" aria-hidden="true"></i> <?=$this->transEsc('Show Model Information')?></span>
            <span class="hide-model-information"><i class="fa fa-arrow-up" aria-hidden="true"></i> <?=$this->transEsc('Hide Model Information')?></span>
        </button>
        <div id="model_details_<?=$this->index?>_<?=$i++?>" class="collapse">
            <table class="table-condensed">
                <tr></tr>
            </table>
        </div>
    <?php endforeach; ?>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-models.phtml -->
