<!-- START of: finna - organisationinfo/elements/location-selection.phtml -->
<?php if (!$orgInfo): ?>
  <?= $this->transEsc('organisation_info_no_schedule'); ?>
  <?php return; ?>
<?php endif; ?>
<?php $locationCount = count($orgInfo['list'] ?? []); ?>
<div class="navi-section finna-panel-default" id="consortium-service-point-section">
  <h2 class="panel-heading locations-title"><?= $this->transEsc(1 === $locationCount ? 'organisation_info_navi_service_single' : 'organisation_info_navi_service') ?></h2>
  <div class="location-filters">
    <?php if ($locationCount > 1): ?>
      <div class="location-filter">
        <form class="location-selection">
          <h2 class="visually-hidden"><?= $this->transEscAttr('organisation_info_location_search') ?></h2>
          <label for="location_select"><?= $this->transEscAttr('Search') ?></label>
          <select id="location_select" class="js-location-select form-select">
            <option hidden value=""><?= $this->transEsc('organisation_info_autocomplete', ['%%count%%' => $locationCount]) ?></option>
            <?php foreach ($orgInfo['list'] as $item): ?>
              <?php
              $name = $item['name'];
              $area = $item['address']['area'];
              $city = $item['address']['city'];
              if ($area === $city) {
                $area = '';
              }
              if ('' !== $area && '' !== $city) {
                $name .= ", $area ($city)";
              } elseif ('' !== $area || '' !== $city) {
                $name .= ", $area$city";
              }
              ?>
              <option value="<?= $this->escapeHtmlAttr($item['id']) ?>"><?= $this->escapeHtml($name) ?></option>
            <?php endforeach; ?>
          </select>
          <div class="alert alert-danger js-location-unavailable hidden"><?= $this->transEsc('organisation_info_location_not_available') ?></div>
        </form>
      </div>

      <?php if ($serviceList && count($locationData) >= 2): ?>
        <div class="js-location-search-container">
          <button class="btn btn-default js-location-search-toggle" aria-expanded="false" data-toggle-aria-expanded>
            <?= $this->transEsc('Search for a Service') ?> <?= $this->icon('filter-expand', 'search-expand') ?><?= $this->icon('filter-collapse', 'search-collapse') ?>
          </button>
          <div class="js-location-search">
            <div class="js-location-search-fields">
              <?= $this->render('organisationinfo/elements/location-search-fields.phtml') ?>
            </div>
            <div class="js-results-loader hidden" role="status"><?= $this->icon('spinner') ?> <?= $this->transEsc('loading_ellipsis') ?></div>
            <div class="js-location-search-results"></div>
          </div>
        </div>
      <?php endif; ?>
    <?php endif; ?>
  </div>
  <?php if ($notification = $orgInfo['consortium']['finna']['notification'] ?? ''): ?>
    <div>
      <p class="consortium-notification"><?= $this->cleanHtml($notification) ?></p>
    </div>
  <?php endif; ?>
  <div class="location-information">
    <div role="status" class="js-location-loader hidden">
      <?= $this->icon('spinner') ?> <?= $this->transEsc('loading_ellipsis') ?>
    </div>
    <div class="js-location-quick-information info-element hidden"></div>

    <div class="js-location-info-map hidden" aria-hidden="true">
      <template class="js-map-attribution">
        <span class="map-marker-text">
          <?= $this->icon('map-marker', 'map-marker-icon open') ?>&nbsp;<?= $this->transEsc('organisation_info_is_open_now') ?>
        </span>
        <span class="map-marker-text">
          <?= $this->icon('map-marker', 'map-marker-icon closed') ?>&nbsp;<?= $this->transEsc('organisation_info_is_closed_now') ?>
        </span>
        <span class="map-marker-text">
          <?= $this->icon('map-marker', 'map-marker-icon no-schedule') ?>&nbsp;<?= $this->transEsc('organisation_info_no_schedule') ?>
        </span>
      </template>
      <template class="js-map-bubble-template">
        <div class="map-bubble">
          <h3 class="js-name"></h3>
          <p><span class="js-address"></span></p>
        </div>
      </template>

      <div class="location-map">
        <div class="js-map-controls">
          <?php if ($locationCount > 1): ?>
            <button class="btn btn-link js-show-location" type="button" disabled><?= $this->transEsc('zoom_center') ?></button>
            <button class="btn btn-link js-show-all" type="button"><?= $this->transEsc('organisation_info_page_map_show_all') ?></button>
          <?php endif; ?>
        </div>
        <div class="map" role="presentation">
          <div id="location_map_canvas" class="js-map-widget"></div>
          <div class="js-marker-tooltip hidden"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="js-location-details-container"></div>
  <?php if (!$this->userAgent()->isBot()): ?>
    <div> <!-- map information about open and closed libraries for the screenreaders starts here -->
      <?php
      $openList = [];
      $closedList = [];
      $mobileList = [];
      // categorise organisations - open - closed - mobile
      foreach ($orgInfo['list'] as $item) {
        $name = $item['name'];
        $area = $item['address']['area'];
        $city = $item['address']['city'];
        $isOpen = $item['openNow'];
        $isMobile = $item['mobile'];

        if ($area === $city) {
          $area = '';
        }
        if ('' !== $area && '' !== $city) {
          $name .= ", $area ($city)";
        } elseif ('' !== $area || '' !== $city) {
          $name .= ", $area$city";
        }

        // Add to respective categories with IDs
        if ($isOpen) {
          $openList[] = ['name' => $name, 'id' => $item['id']];
        } elseif ($isMobile) {
          $mobileList[] = ['name' => $name, 'id' => $item['id']];
        } else {
          $closedList[] = ['name' => $name, 'id' => $item['id']];
        }
      }
      ?> <!-- display categorised organisations -->
    <h3 aria-label="<?= $this->transEsc(1 === $locationCount ? 'organisation_info_navi_service_single' : 'organisation_info_navi_service') ?> <?=$this->transEsc('Total') . ' ' . $locationCount ?>"><?= $this->transEsc(1 === $locationCount ? 'organisation_info_navi_service_single' : 'organisation_info_navi_service') ?></h3> <!-- only aria-label will read this without announcing clickable -->
      <?php if ($locationCount > 1): ?>
        <h4><?=$this->transEsc('organisation_info_is_open_now') ?></h4>
        <div class="organisation-info organisation-status-columns">
          <?php foreach ($openList as $item): ?>
            <?php if ($item['name'] != ''): ?>
              <a href="#<?= $this->escapeHtmlAttr($item['id']) ?>"><?= $this->escapeHtml($item['name']) ?></a><br>
            <?php endif; ?>
          <?php endforeach; ?>
        </div>
        <h4><?=$this->transEsc('organisation_info_is_closed_now') ?></h4>
        <div class="organisation-info organisation-status-columns">
          <?php foreach ($closedList as $item): ?>
            <?php if ($item['name'] != ''): ?>
              <a href="#<?= $this->escapeHtmlAttr($item['id']) ?>"><?= $this->escapeHtml($item['name']) ?></a><br>
            <?php endif; ?>
          <?php endforeach; ?>
        </div>
        <h4><?=$this->transEsc('organisation_info_no_schedule') ?></h4>
        <div class="organisation-info organisation-status-columns">
          <?php foreach ($mobileList as $item): ?>
            <?php if ($item['name'] != ''): ?>
              <a href="#<?= $this->escapeHtmlAttr($item['id']) ?>"><?= $this->escapeHtml($item['name']) ?></a><br>
            <?php endif; ?>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>
    </div> <!-- map information about open and closed libraries for the screenreaders ends here -->
  <?php endif; ?>
</div>
<br><hr>
<!-- END of: finna - organisationinfo/elements/location-selection.phtml -->
   