<!-- START of: finna - organisationinfo/elements/location-selection.phtml -->
<div class="navi-section map-ui" id="consortium-service-point-section">
  <div class="locations-title">
    <h2><?=$this->transEsc('organisation_info_navi_service')?></h2>
  </div>
  <div class="location-filters">
    <?php if (count($orgInfo['list'] ?? []) > 1): ?>
      <div class="location-filter">
        <form class="form-inline searchbox-office map-ui">
          <div class="input-group">
            <label for="location_select" class="hidden"><?=$this->transEscAttr('Search')?></label>
            <select id="location_select" class="js-location-select">
                <option value=""><?=$this->transEsc('organisation_info_autocomplete', ['%%count%%' => count($orgInfo['list'])])?></option>
              <?php foreach ($orgInfo['list'] as $item): ?>
                <?php
                  $name = $item['name'];
                  if ($city = $item['address']['city'] ?? null) {
                    $name .= ", $city";
                  }
                ?>
                <option value="<?=$this->escapeHtmlAttr($item['id'])?>"><?=$this->escapeHtml($name)?></option>
              <?php endforeach; ?>
            </select>
            <div class="js-location-unavailable hidden"><?=$this->transEsc('organisation_info_location_not_available')?></div>
          </div>
        </form>
      </div>
    <?php endif; ?>
  </div>
  <?php if ($notification = $orgInfo['consortium']['finna']['notification'] ?? ''): ?>
    <div>
      <p class="consortium-notification"><?=$this->cleanHtml($notification)?></p>
    </div>
  <?php endif; ?>

  <div class="location-information">
    <div class="js-location-loader hidden">
      <?=$this->icon('spinner') ?> <?=$this->transEsc('loading_ellipsis')?>
    </div>
    <div class="js-location-quick-information info-element"></div>

    <div class="js-location-info-map hidden">
      <template class="js-map-attribution">
        <span class="map-marker-text">
          <?=$this->icon('map-marker', 'map-marker-icon open')?>&nbsp;<?=$this->transEsc('organisation_info_is_open')?>
        </span>
        <span class="map-marker-text">
          <?=$this->icon('map-marker', 'map-marker-icon closed')?>&nbsp;<?=$this->transEsc('organisation_info_is_closed')?>
        </span>
        <span class="map-marker-text">
          <?=$this->icon('map-marker', 'map-marker-icon no-schedule')?>&nbsp;<?=$this->transEsc('organisation_info_no_schedule')?>
        </span>
        <span class="js-expand-map map-marker-text marker">
          <?=$this->icon('map-expand')?>&nbsp;<?=$this->transEsc('organisation_info_map_expand')?>
        </span>
        <span class="js-contract-map map-marker-text marker hidden">
          <?=$this->icon('map-collapse')?>&nbsp;<?=$this->transEsc('organisation_info_map_collapse')?>
        </span>
      </template>
      <template class="js-map-bubble-template">
        <div class="map-bubble">
          <h3 class="js-name"></h3>
          <p><span class="js-address"></span></p>
        </div>
      </template>

      <div class="location-map">
        <div class="map-buttons">
          <div class="map-ui map-control-buttons" aria-hidden="true">
            <?php if (count($orgInfo['list']) > 1): ?>
              <span class="js-map-controls">
                <span class="js-show-location"><a href="#"><?=$this->transEsc('zoom_center')?></a></span>
                <span class="js-show-all"><a href="#"><?=$this->transEsc('organisation_info_page_map_show_all')?></a></span>
              </span>
            <?php endif; ?>
          </div>
        </div>
        <div class="map-ui map <?=$this->escapeHtmlAttr($this->mapWidget)?>" aria-hidden="true">
          <div id="location_map_canvas" class="js-map-widget"></div>
          <div class="js-marker-tooltip hidden"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END of: finna - organisationinfo/elements/location-selection.phtml -->
