<!-- START of: national - search/home/home-left_en-gb.phtml -->
<div class="introduction">
 <div class="left-column-content">
    <div class="background-image-overlay">  
        <h2>Finna Street</h2>
        <div class="text-and-action">
            <p>Uncover historical images of where you are!</p>
          <a class="btn btn-primary" href="<?=$this->url('search-streetsearch')?>?go=1"><i class="fa fa-crosshairs"></i> <span><?=$this->transEsc('street_search_button')?></span></a>
        </div>
    </div>  
 </div>
</div>
<!-- END of: national - search/home/home-left_en-gb.phtml -->
