<!-- START of: finna - RecordDriver/SolrQdc/core.phtml -->
<?php
  $recordHelper = $this->record($this->driver);
  $linkDetails = $recordHelper->getLinkDetailsExtended();
  $media = $recordHelper->renderTemplate('media.phtml', $linkDetails);
  $mediaAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
?>

<?php $this->metadata()->generateMetatags($this->driver);?>
<div class="media">
  <h1 class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
  <?php if ($media && $mediaAlignment == 'left'): ?>
    <?=$media ?>
  <?php endif; ?>
  <div class="media-body record-information">
      <h1 class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
      <?php if ($results = $this->driver->getAlternativeTitles()): ?>
        <div class="recordAltTitles record-alt-titles">
          <?=implode('<br>', array_map([$this, 'escapeHtml'], $results))?>
        </div>
      <?php endif; ?>

      <?=$this->record($this->driver)->renderTemplate('cached-record-warning.phtml', ['driver' => $this->driver])?>
      <?=$this->record($this->driver)->getLabelList() ?>

      <?= $media->renderTemplate('urls-container', $linkDetails); ?>

      <div class="record-core-metadata">
        <?php $formats = $this->driver->getFormats();
        if (!empty($formats)): ?>
          <span class="recordFormat"><?=$this->record($this->driver)->getFormatList()?></span>
        <?php endif; ?>

        <?php if ($results = $this->driver->getNonPresenterAuthors()): ?>
        <div class="truncate-field recordAuthors">
          <span>
          <?php foreach ($results as $index => $author): ?>
            <?=($index > 0 ? '; ' : '')?><?=$this->record($this->driver)->getLinkedFieldElement('author', $author['name'], $author, ['date' => true, 'role' => true, 'authorityType' => $author['type'] ?? null])?>
          <?php endforeach; ?>
          </span>
        </div>
        <?php endif; ?>

        <?php if ($publications = $this->driver->getPublicationDetails()): ?>
          <div class="recordPublications">
            <?php foreach ($publications as $field): ?>
              <span>
                <?php if ($pubPlace = $field->getPlace()): ?>
                  <span><?=$this->escapeHtml($pubPlace)?></span>
                <?php endif; ?>
                <?php if ($pubName = $field->getName()): ?>
                  <span><?=$this->escapeHtml($pubName)?></span>
                <?php endif; ?>
                <?php if ($pubDate = $field->getDate()): ?>
                  <span><?=$this->escapeHtml($pubDate)?></span>
                <?php endif; ?>
              </span>
            <?php endforeach; ?>
          </div>
        <?php endif; ?>

        <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
          <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
        <?php endif; ?>
      </div>

      <?php if ($abstracts = $this->driver->getAbstracts()): ?>
        <div class="truncate-field wide summary recordSummary">
          <?= $this->recordFieldMarkdown()->toHTML(implode("\n\n", $abstracts), "\n") ?>
        </div>
      <?php endif; ?>
      <?php if ($descriptions = $this->driver->getDescriptions()): ?>
        <div class="truncate-field wide summary recordSummary">
          <?= $this->recordFieldMarkdown()->toHTML(implode("\n\n", $descriptions), "\n") ?>
        </div>
      <?php endif; ?>

      <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
        <?php /* Display the lists that this record is saved to */ ?>
        <div class="savedLists" id="savedLists">
          <strong><?=$this->transEsc('Saved in')?>:</strong>
        </div>
      <?php endif; ?>

      <?php /* Display Main Details */?>
      <?=
        $this->record($this->driver)->renderTemplate(
            'core-fields.phtml',
            [
              'driver' => $this->driver,
            ]
        );
      ?>
      <?php /* End Main Details */?>

      <?php if ($template = $this->content()->findTemplateForLng('content/Additions/record-post-metadata')): ?>
      <div>
        <?=$this->render($template)?>
      </div>
      <?php endif; ?>
    </div>
  <?php if ($media && $mediaAlignment == 'right'): ?>
    <?=$media ?>
  <?php endif; ?>
</div>
<!-- END of: finna - RecordDriver/SolrQdc/core.phtml -->
