<?php // No ending line feed ?>
<?php if (!$authorityLink): ?>
  <a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?></a><?php if (!empty($author['date'])): ?><span class="author-date">, <?=$this->escapeHtml($author['date']) ?></span><?php endif; ?><?php if (!empty($author['role'])): ?><span class="author-role">, <?=mb_strtolower($this->transEsc('CreatorRoles::' . $author['role']), 'UTF-8') ?></span><?php endif; ?>
<?php elseif ($id && $showInlineInfo): ?>
  <div class="authority ajax-content" data-authority="<?=$this->escapeHtmlAttr($this->id)?>" data-source="<?=$this->escapeHtmlAttr($this->recordSource)?>" data-type="<?=$this->escapeHtmlAttr($this->type)?>">
<?php endif ?>
  <a href="<?=$this->escapeHtmlAttr($this->url)?>"<?= $this->authorityLink ? ' class="authority-link"' : ''?>><?php if ($this->authorityLink && $this->authorityType): ?><i aria-label="<?=$this->escapeHtmlAttr($this->translate('authority_' . $this->authorityType))?>" class="fa fa-authority-<?=$this->escapeHtmlAttr($this->record($this->record)->getFormatClass($this->authorityType))?>"></i> <?php endif; ?><?=$this->escapeHtml($this->label)?></a><?php if (isset($this->date)): ?><span class="author-date">, <?=$this->escapeHtml($this->date) ?></span><?php endif; ?><?php if ($this->role || $this->roleName): ?><span class="author-role">, <?= !empty($this->roleName) ? $this->roleName : $this->transEsc('CreatorRoles::' . $this->role) ?></span><?php endif; ?><?php if ($this->showInlineInfo): ?><a href="#" class="show-info"><?=$this->translate('authority_show_info')?></a>
  <div class="authority-info">
    <div class="content"><i class="fa fa-spin fa-spinner"></i></div>
    <div class="content-btn-holder"><a href="#" class="hide-info btn btn-primary"><?=$this->translate('authority_hide_info')?></a></div>
  </div>
</div>
<?php endif; ?>