<?php if ($id && $showInlineInfo): ?>
<div class="authority ajax-content" data-authority="<?=$this->escapeHtmlAttr($this->id)?>" data-source="<?=$this->escapeHtmlAttr($this->recordSource)?>" data-type="<?=$this->escapeHtmlAttr($this->type)?>">
<?php endif ?>
  <?php
    $linkClasses = $this->classes;
    if ($this->authorityLink) {
      $linkClasses[] = 'authority-link';
    }
    $linkClasses = array_map(
      function ($class) {
        return $this->escapeHtmlAttr($class);
      },
      $linkClasses
    );
  ?>
  <a<?= $this->title ? ' title="' . $this->escapeHtmlAttr($this->title) . '"' : ''?> href="<?=$this->escapeHtmlAttr($this->url)?>"<?= $linkClasses ? ' class="' . implode(',', $linkClasses) . '"': ''?>><?php if ($this->authorityLink && $this->authorityType): ?><i aria-label="<?=$this->escapeHtmlAttr($this->translate('authority_' . $this->authorityType))?>" class="fa fa-authority-<?=$this->escapeHtmlAttr($this->record($this->record)->getFormatClass($this->authorityType))?>"></i> <?php endif; ?><span class="authority-label"><?=$this->escapeHtml($this->label)?></a><?php if (!empty($additionalData)): ?><span class="authority-additional-data"><?= $additionalData ?></span></span><?php endif; ?><?php if ($this->showInlineInfo): ?> <a href="#" class="show-info"><?=$this->translate('authority_show_info')?></a>
  <div class="authority-info">
    <div class="content"><i class="fa fa-spin fa-spinner"></i></div>
    <div class="content-btn-holder"><a href="#" class="hide-info btn btn-primary"><?=$this->translate('authority_hide_info')?></a></div>
  </div>
</div>
<?php endif; ?>
