<?php
    if ($this->driver->isCollection()) {
        if ($this->driver instanceof \Finna\RecordDriver\SolrLido || $this->driver->tryMethod('getArchiveType') === 'collection') {
            $term = 'Collection';
        } else {
            $term = 'Archive';
        }
    } else {
        $term = 'Record';
    }
?>
<h2><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h2>
<a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver))?>">
    <?=$this->transEsc('View Full ' . $term)?>
</a>

<?=
  $this->record($this->driver)->renderTemplate(
      'core-fields.phtml',
      [
        'driver' => $this->driver,
        'defaults' => 'collection-record',
      ]
  );
?>
