<!-- START of: finna - RecordDriver/DefaultRecord/container-links.phtml -->
<?php $this->inRecordInfo ?? false; ?>
<?php $containerTitle = $this->driver->getContainerTitle(); ?>
<?php $hostRecords = $this->driver->tryMethod('getHostRecords'); ?>
<?php if ($containerTitle || $hostRecords): ?>
  <div class="recordContainerReference">
    <?php
      $containerSource = $this->driver->getSourceIdentifier();
      $containerID = $this->driver->getContainerRecordID();
      $linkedItems = [];
      foreach ($hostRecords ?? [] as $hostRecord) {
        if ($hostRecord['relation']) {
          $linkedItems[] = $hostRecord;
        } else {
          $arr[] = $hostRecord;
        }
      }
      $hostRecords = $arr ?? [];
    ?>
    <div class="truncate-field">
      <?php // If doesn't have hostRecords check for links to collections before using hierarchy_parent_id linking ?>
      <?php if ($hostRecords || (!$linkedItems && $containerID)): ?>
        <div class="publishedIn">
          <span class="recordPublished"><?=$this->transEsc('Published in')?>: </span>
          <?php if ($hostRecords): ?>
            <?= $this->record($this->driver)->renderTemplate('host-records.phtml', compact('hostRecords', 'driver')); ?>
          <?php elseif (!$linkedItems): ?>
            <?php $link = $containerID ? $this->recordLinker()->getUrl($containerSource . '|' . $containerID) : $this->record($this->driver)->getLink('title', $containerTitle); ?>
            <a href="<?=$this->escapeHtmlAttr($link)?>"><?=$this->escapeHtml($containerTitle)?></a>
            <?php $ref = $this->driver->getContainerReference();
            if (!empty($ref)) {
              echo $this->escapeHtml($ref);
            } ?>
          <?php endif; ?>
        </div>
      <?php endif; ?>
      <?php if ($linkedItems && !$this->inRecordInfo): ?>
        <div class="includedIn">
          <div class="record-included-in"><?=$this->transEsc('Included in collections')?>: </div>
          <?= $this->record($this->driver)->renderTemplate('host-records.phtml', ['hostRecords' => $linkedItems, 'driver', 'includedIn' => true]); ?>
        </div>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
<!-- END of: finna - RecordDriver/DefaultRecord/container-links.phtml -->
