<?php $containerTitle = $this->driver->getContainerTitle(); ?>
<?php $hostRecords = $this->driver->tryMethod('getHostRecords'); ?>
<?php if ($containerTitle || $hostRecords): ?>
  <div class="recordContainerReference">
    <?php
      $containerSource = $this->driver->getSourceIdentifier();
      $containerID = $this->driver->getContainerRecordID();
      $isLinked = $this->driver->tryMethod('getLinkedParents');
    ?>
    <div class="truncate-field">
      <?php if (empty($data)): ?>
        <div class="recordPublished"><?=$this->transEsc($isLinked ? 'Included in collections' : 'Published in')?>: </div>
      <?php endif; ?>
      <?php if ($hostRecords): ?>
        <?= $this->record($this->driver)->renderTemplate('host-records.phtml', compact('hostRecords', 'driver')); ?>
      <?php else: ?>
        <?php $link = $containerID ? $this->recordLinker()->getUrl($containerSource . '|' . $containerID) : $this->record($this->driver)->getLink('title', $containerTitle); ?>
        <a href="<?=$this->escapeHtmlAttr($link)?>"><?=$this->escapeHtml($containerTitle)?></a>
        <?php $ref = $this->driver->getContainerReference();
        if (!empty($ref)) {
          echo $this->escapeHtml($ref);
        } ?>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
