<!-- START of: finna - RecordDriver/DefaultRecord/core.phtml -->
<?php
  $binding = $this->driver->tryMethod('getBinding');

  $recordHelper = $this->record($this->driver);
  $linkDetails = $recordHelper->getLinkDetailsExtended();
  $media = $recordHelper->renderTemplate('media.phtml', $linkDetails);
  $mediaAlignment = $recordHelper->getThumbnailAlignment('result');
?>

<?php $this->metadata()->generateMetatags($this->driver);?>
<div class="media">
  <h1 class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>

  <?php if (!empty($this->extraControls)): ?>
    <?=$this->extraControls['actionControls'] ?? ''?>
    <?=$this->extraControls['availabilityInfo'] ?? ''?>
  <?php endif; ?>

  <?php if ($media && $mediaAlignment == 'left'): ?>
    <?=$media ?>
  <?php endif; ?>
  <div class="media-body record-information">
    <h1 class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
      <div class="record-title-alt-script">
        <?=$this->escapeHtml($altTitle)?>
      </div>
    <?php endforeach; ?>
    <?php if ($uniformTitles = $this->driver->tryMethod('getUniformTitles')): ?>
      <div class="record-uniform-titles">
        <?php foreach ($uniformTitles as $uniformTitle): ?>
          <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
            <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getVersionsSearchUrl($this->driver))?>" rel="nofollow">
              <?=$this->escapeHtml($uniformTitle) ?>
            </a>
            <br>
          <?php else: ?>
            <?=$this->escapeHtml($uniformTitle) ?><br>
          <?php endif; ?>
        <?php endforeach; ?>
      </div>
    <?php endif; ?>

    <?=$this->record($this->driver)->renderTemplate('cached-record-warning.phtml', ['driver' => $this->driver])?>
    <?=$this->record($this->driver)->getLabelList() ?>

    <?php
      $formats = $this->driver->getFormats();
    ?>

    <?= $recordHelper->renderTemplate('urls-container.phtml', $linkDetails); ?>

    <div class="record-core-metadata">
      <?php $formats = $this->driver->getFormats();
      if (!empty($formats)): ?>
        <div class="recordFormat">
          <?=$this->record($this->driver)->getFormatList()?><?php if (!empty($binding)): ?><span class="iconlabel label-binding"><span class="label-punctuation">, </span><?=$this->transEsc($binding)?></span><?php endif; ?><br>
        </div>
      <?php endif; ?>

      <?php $results = $this->driver->tryMethod('getPrimaryAuthorsExtended') ?? $this->driver->tryMethod('getNonPresenterAuthors') ?? null;?>
      <?php if ($results): ?>
        <div class="recordAuthors">
          <div class="truncate-field">
            <?php foreach ($results as $index => $author): ?>
              <?=($index > 0 ? '; ' : '')?><?=$this->record($this->driver)->getLinkedFieldElement('author', $author['name'], $author, ['date' => true, 'role' => true, 'authorityType' => $author['type'] ?? null])?>
            <?php endforeach; ?>
            <?php $altScriptFound = false; ?>
            <?php foreach ($results as $index => $author): ?>
              <?php if (!empty($author['name_alt'])): ?>
                <?php if (!$altScriptFound): ?><br><?php else: ?>; <?php endif; ?>
                <?=$this->escapeHtml($author['name_alt'])?><?php if (!empty($author['date'])): ?><span class="author-date">, <?=$this->escapeHtml($author['date']) ?></span><?php endif; ?><?php if (!empty($author['role'])): ?><span class="author-role">, <?=mb_strtolower($this->transEsc('CreatorRoles::' . $author['role']), 'UTF-8') ?></span><?php endif; ?>
                <?php $altScriptFound = true; ?>
              <?php endif; ?>
            <?php endforeach; ?>
          </div>
        </div>
      <?php endif; ?>

      <?=$this->record($this->driver)->renderTemplate('container-links.phtml', ['inRecordInfo' => true]); ?>
      <?php $publications = $this->driver->getPublicationDetails();
      if (!empty($publications)): ?>
        <span class="recordPublications">
          <?php foreach ($publications as $field): ?>
            <span>
              <?php $pubName = $field->getName();
              if (!empty($pubName)): ?>
                <span><?=$this->escapeHtml($pubName)?></span>
              <?php endif; ?>
            </span>
            <?php $pubDate = $field->getDate();
            if (!empty($pubDate)): ?>
              <span><?=$this->escapeHtml($pubDate)?></span>
            <?php endif; ?>
          <?php endforeach; ?>
        </span>
      <?php endif; ?>

      <?php $edition = $this->driver->getEdition();
      if (!empty($edition)): ?>
        <span class="recordEdition">
          <span><?=$this->escapeHtml($edition)?></span>
        </span>
      <?php endif; ?>

      <?php if (
          isset($this->tabs['ComponentParts'])
          && $this->driver->tryMethod('getEmbeddedComponentParts')
        ): ?>
        <div class="record-to-componentparts-link">
          <a class="icon-link" href="#componentparts">
            <?=$this->icon('more', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('Show contents')?></span>
          </a>
        </div>
      <?php endif; ?>

      <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
        <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
      <?php endif; ?>
      <?php if (isset($this->tabs['Series'])): ?>
        <div class="record-to-series-link">
          <a class="icon-link" href="#series">
            <?=$this->icon('more', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('series_parts_link')?></span>
          </a>
        </div>
      <?php endif; ?>
    </div> <?php // record-core-metadata ?>

    <div class="description recordSummary">
      <span id="description_text" data-id="<?=$this->escapeHtmlAttr($this->driver->getUniqueID())?>" data-source="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
        <?=$this->icon('spinner') ?>
      </span>
    </div>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists" id="savedLists">
        <strong><?=$this->transEsc('Saved in')?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */?>
    <?=
      $this->record($this->driver)->renderTemplate(
          'core-fields.phtml',
          [
            'driver' => $this->driver,
          ]
      );
    ?>
    <?php /* End Main Details */?>

    <?php if ($template = $this->content()->findTemplateForLng('content/Additions/record-post-metadata')): ?>
    <div>
      <?=$this->render($template)?>
    </div>
    <?php endif; ?>
  </div>
  <?php if ($media && $mediaAlignment == 'right'): ?>
    <?=$media ?>
  <?php endif; ?>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/core.phtml -->
