<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <div class="truncate-field">
    <?php foreach ($data as $keyword): ?>
      <div class="subjectLine" property="keywords">
        <?php if (is_array($keyword)): ?>
          <?php if (array_key_exists('object', $keyword)): ?>
            <?=$this->escapeHtml($keyword['object']) ?> <?php if (array_key_exists('label', $keyword)): ?> (<?=$this->escapeHtml($keyword['label']) ?>)
            <?php elseif (array_key_exists('type', $keyword)): ?>
              (<?=$this->escapeHtml($keyword['type']) ?>)
            <?php endif; ?>
          <?php else: ?>
            <a class="backlink" title="<?=$this->escapeHtmlAttr($keyword['term'])?>" href="<?=$this->record($this->driver)->getLink('keyword', $keyword['term'])?>"><?=$this->escapeHtml($keyword['term']) ?></a><?php if (array_key_exists('label', $keyword)): ?> (<?=$this->escapeHtml($keyword['label']) ?>)<?php endif; ?>
          <?php endif; ?>
        <?php else: ?>
           <a class="backlink" title="<?=$this->escapeHtmlAttr($keyword)?>" href="<?=$this->record($this->driver)->getLink('keyword', $keyword)?>"><?=$this->escapeHtml($keyword) ?></a>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
