<?php //Don't add START and END comments ?>
<? $level = $this->level ?? ['series','subseries'] ?>
<?php if ($data == true && !$fondsOrCollection = in_array('Document/ArchiveFonds', $this->driver->getFormats()) || in_array('Document/ArchiveCollection', $this->driver->getFormats())): ?>
    <?php $parentSource = $this->driver->getSourceIdentifier(); ?>
    <?php $parentIds = $this->driver->getHierarchyParentId($level); $parentTitles = $this->driver->getHierarchyParentTitle($level); ?>
    <?php foreach ($parentIds as $index => $parentId): ?>
      <?php
        try {
          $parentUrl = $this->recordLink()->getUrl("$parentSource|$parentId");
        } catch (\Exception $e) {
          $parentUrl = '';
        }
      ?>
      <?=($index > 0 ? '<br>' : '')?><a href="<?=$this->escapeHtmlAttr($parentUrl)?>"><?=isset($parentTitles[$index]) ? $this->truncate($parentTitles[$index], 180) : ''?></a>
    <?php endforeach; ?>
<?php endif; ?>
