<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <?php
    $allLinks = $data;
    if ($useLinkTitles = isset($data[0]['title'])) {
      $allLinks = [];
      foreach ($data as $link) {
        $allLinks[$link['title']][] = $link;
      }
    }
    $truncate = false;
    if (isset($data[0]['isMapped'])) {
      $class = 'contained-in';
      $truncate = true;
    }
  ?>
  <?php if ($useLinkTitles):?>
    <?php foreach ($allLinks as $title => $links): ?>
      <tr class="recordLinks">
        <th><?=$this->transEsc($title);?></th>
        <td>
          <?php if ($truncate): ?>
            <div class="truncate-field" data-rows="5">
          <?php endif; ?>
          <?php foreach ($links as $link): ?>
            <a class="<?=$class?>" href="<?=$this->escapeHtmlAttr($this->recordLinker()->related($link['link'], $this->driver->getSourceIdentifier()));?>"><?=$this->escapeHtml($link['value'] ?: $this->translate($title));?></a><?php if (isset($link['detail'])): ?> (<?=$this->escapeHtml($link['detail'])?>)<?php endif; ?><?php if (!empty($link['misc'])): ?> / <?=$this->escapeHtml($link['misc'])?><?php endif; ?>
            <br>
          <?php endforeach; ?>
          <?php if ($truncate): ?>
            </div>
          <?php endif; ?>
        </td>
      </tr>
    <?php endforeach; ?>
  <?php else:?>
    <div class="truncate-field">
      <?php foreach ($allLinks as $link): ?>
        <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->related($link['link'], $this->driver->getSourceIdentifier()));?>"><?=$this->escapeHtml($link['value'])?></a><?php if (isset($link['detail'])): ?> (<?=$this->escapeHtml($link['detail'])?>)<?php endif; ?>
        <br>
      <?php endforeach; ?>
    </div>
  <?php endif?>
<?php endif; ?>
