<?php /* Don't add start or end tags */ ?>
<div class="truncate-field" data-rows="5">
    <?php foreach ($data as $obj): ?>
        <?php
            $loopUntil = max(count($obj['urls']), count($obj['terms']));
        ?>
        <?php if (!empty($obj['description'])): ?>
            <div><?=$this->escapeHtml($obj['description'])?></div>
        <?php endif; ?>
        <?php for ($i = 0; $i < $loopUntil; $i++): ?>
            <?php
                $url = $obj['urls'][$i] ?? false;
                $term = $obj['terms'][$i] ?? false;
            ?>
            <?php if (!empty($url)): ?>
                <a title="<?=$this->escapeHtmlAttr($term ?: $obj['description']) ?? $this->transEsc('external_link')?>" target="_blank" href="<?=$this->escapeHtmlAttr($url)?>">
            <?php endif; ?>    
            <?php if (!empty($term)): ?>
                <div><?=$this->escapeHtml($term)?></div>
            <?php elseif (!empty($url)): ?>
                <div><?=$this->escapeHtml($this->truncateUrl($url))?></div>
            <?php endif; ?>
            <?php if (!empty($url)): ?>    
                </a>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endforeach; ?>
</div>
