<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <div class="truncate-field">
    <?php foreach ($data as $term): ?>
      <div class="subjectLine" property="classification">
        <?php $result = explode('::', $term); ?>
        <a class="backlink" title="<?=$this->escapeHtmlAttr($result[0])?>" href="<?=$this->record($this->driver)->getLink('keyword', $result[0])?>"><?=$this->escapeHtml($result[0])?></a><?php if ($result[1]): ?> <?=$this->escapeHtml($result[1])?><?php endif; ?>
      </div>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
