<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <?php if (is_array($data)): ?>
    <?php $data = array_unique($data); ?>
    <div class="truncate-field" data-rows="5">
      <?php foreach ($data as $field): ?>
        <?=$this->transEsc("AccessibilityFeature::$field")?><br>
      <?php endforeach; ?>
    </div>
  <?php else: ?>
    <?=$this->transEsc($data)?>
  <?php endif; ?>
<?php endif; ?>
