<?php /* Don't add start or end tags */ ?>
<div class="truncate-field" data-rows="5">
    <?php foreach ($data as $obj): ?>
        <?php
            $desc = $obj['description'] ?? '';
            $url = $obj['url'] ?? '';
            $term = $obj['term'] ?? '';
        ?>
        <?php if ($desc): ?>
            <div><?=$this->escapeHtml($desc)?></div>
        <?php endif; ?>
        <?php if ($url): ?>
            <a title="<?=$this->escapeHtmlAttr($term ?: $desc)?>" target="_blank" href="<?=$this->escapeHtmlAttr($url)?>">
        <?php endif; ?>    
        <?php if ($term): ?>
            <div><?=$this->escapeHtml($term)?></div>
        <?php elseif ($url): ?>
            <div><?=$this->escapeHtml($this->truncateUrl($url))?></div>
        <?php endif; ?>
        <?php if ($url): ?>    
            </a>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
