<?php // this is used so often that it would pollute the results: <!-- START of: finna - RecordDriver/DefaultRecord/format-list.phtml --> ?>
<?php
  $formatMap = [];
  $formats = (array)$this->driver->tryMethod('getFormats');
  $showLabel = $this->driver->tryMethod('hasModelResources');
  if ($formats) {
    // Take last level of each format main type
    foreach ($formats as $format) {
      $parts = explode('/', $format);
      if (isset($parts[1])) {
        $formatMap[$parts[1]] = $format;
      } else {
        $formatMap['-'] = $format;
      }
    }
  }
?>
<?php foreach ($formatMap as $format): ?>
  <?php
    if ($showLabel) {
      $label = '3D';
    }
  ?>
  <span class="label label-info iconlabel format-<?=$this->record($this->driver)->getFormatClass($format)?>"><?=$this->transEsc($format)?></span> <?php if ($showLabel && !empty($label)): ?><span class="label format-label"><?=$label?></span><?php endif; ?>
<?php endforeach; ?>
<?php // <!-- END of: finna - RecordDriver/DefaultRecord/format-list.phtml --> ?>
