<!-- START of: finna - RecordDriver/DefaultRecord/holdings-deduplicated.phtml -->
<?php
  $recordSource = $this->driver->tryMethod('getDataSource');
  $dedupData = $this->driver->getDedupData();
  $fetchHoldings = $this->record($this->driver)->fetchDedupHoldingsOnLoad();

  if (!$fetchHoldings) {
    $patron = $this->auth()->getILSPatron();
    $preferredRecordSource = $this->cookie()->get('preferredRecordSource');
    if (empty($preferredRecordSource)) {
      $preferredRecordSource = $patron['source'] ?? '';
    }
    $overrideID = !empty($preferredRecordSource) ? $dedupData[$preferredRecordSource]['id'] ?? '' : '';
  }
  $selectID = "{$this->driver->getUniqueID()}-dedup-select";
?>

<div class="holding-details deduplicated">
  <div class="dedupInformation">
    <label for="<?=$this->escapeHtmlAttr($selectID)?>"><?=$this->transEsc('Holdings')?>:</label>
    <select id="<?=$this->escapeHtmlAttr($selectID)?>" class="dedup-select form-control" role="listbox" aria-haspopup="true" title="<?=$this->transEsc('select_dedup_organisation');?>" aria-label="<?=$this->transEsc('select_dedup_organisation');?>" <?php if (!empty($overrideID)):?>data-overrideid="<?=$this->escapeHtmlAttr($overrideID)?>"<?php endif;?>>
      <?php if (empty($overrideID)):?>
        <option class="js-dedup-placeholder" value="" disabled selected><?= $this->transEsc('Choose Library')?></option>
      <?php endif;?>
      <?php foreach ($dedupData as $source => $current): ?>
        <option value="<?=$this->escapeHtmlAttr($current['id']) ?>" class="dedup-data-id" data-source="<?=$this->escapeHtmlAttr($source) ?>" <?php if ($fetchHoldings && $recordSource === $source): ?> selected="selected"<?php endif; ?>><?=$this->transEsc("source_$source", null, $source) ?></option>
      <?php endforeach; ?>
    </select>
  </div>

  <div class="callnumAndLocation ajax-availability hidden">
    <?php if ($this->driver->supportsAjaxStatus()): ?>
      <span class="callnumber ajax-availability hidden"></span>
      <span class="location ajax-availability hidden">
        <i class="fa fa-spinner fa-spin"></i> <?=$this->transEsc('loading_ellipsis')?>
      </span>
      <div class="locationDetails"></div>
    <?php else: ?>
      <?php $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
        <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
      <?php endif; ?>
    <?php endif; ?>
  </div>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/holdings-deduplicated.phtml -->
