<!-- START of: finna - RecordDriver/DefaultRecord/holdings.phtml -->
<div class="holding-details">
  <?php if ($recordSource = $this->driver->tryMethod('getDataSource')): ?>
    <div class="dedupInformation">
      <strong><?=$this->transEsc("source_$recordSource", null, $recordSource) ?></strong>
    </div>
  <?php endif; ?>

  <div class="callnumAndLocation ajax-availability hidden">
    <?php if ($this->driver->supportsAjaxStatus()): ?>
      <span class="callnumber ajax-availability hidden"></span>
      <span class="location ajax-availability hidden">
        <i class="fa fa-spinner fa-spin"></i> <?=$this->transEsc('loading_ellipsis')?>
      </span>
      <div class="locationDetails"></div>
    <?php else: ?>
      <?php $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
        <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
      <?php endif; ?>
    <?php endif; ?>
  </div>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/holdings.phtml -->
