<!-- START of: finna - RecordDriver/DefaultRecord/image-rights.phtml -->
<div class="access-rights">
  <?php if (!empty($rights['copyright']) || !empty($rights['description'])): ?>
    <?php
      $descriptions = $rights['description'] ?? [];
    ?>
    <div class="image-rights">
      <?php $hasLink = !empty($rights['link']); ?>
      <span class="sr-only"><?=$this->transEsc($imageRightsLabel ?? 'Image Rights') ?>: </span>
      <span class="cc-rights">
        <?php if (!empty($rights['copyright'])): ?>
          <?php
            $copyright = $rights['copyright'];
            $labelEsc = $this->record($this->driver)->translateCopyright($copyright);
          ?>
          <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $copyright]);?>
          <?php if ($hasLink): ?>
            <a target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>" href="<?=$this->escapeHtmlAttr($rights['link']) ?>">
              <span class="copyright-label"><?=$labelEsc?></span>
            </a>
          <?php else: ?>
            <span class="copyright-label"><?=$labelEsc?></span>
          <?php endif; ?>
        <?php else: ?>
          <?php foreach ($descriptions as $item): ?>
            <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $item])?>
            <?php if ($hasLink): ?>
              <a target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>" href="<?=$this->escapeHtmlAttr($rights['link']) ?>">
                <?=$this->escapeHtml($item)?></span>
              </a>
            <?php else: ?>
              <span><?=$this->escapeHtml($item)?></span>
            <?php endif; ?>
          <?php endforeach ?>
          <?php $descriptions = []; ?>
        <?php endif; ?>
      </span>
    </div>
    <?php if ($descriptions): ?>
      <?php foreach ($descriptions as $item): ?>
        <div class="copyright-description">
          <button class="btn btn-default toggle-copyright-description collapsed" data-bs-toggle="collapse" data-bs-target="#copyright_collapse" type="button" aria-expanded="false" aria-controls="image_details">
            <span class="show-copyright-description"><?=$this->transEsc('Käyttöoikeustiedot')?> <?=$this->icon('image-information-show') ?></span>
            <span class="hide-copyright-description"><?=$this->transEsc('Käyttöoikeustiedot')?> <?=$this->icon('image-information-hide') ?></span>
          </button>
          <div id="copyright_collapse" class="collapse">
            <?=$this->transEsc($item)?>
          </div>
        </div>
      <?php endforeach ?>
    <?php endif; ?>
  <?php else: ?>
    <p class="image-rights-default">
      <?=$this->transEsc('Image Rights Default') ?>
    </p>
    <p class="hidden-print">
      <a href="<?= $this->url('content-page', ['page' => 'terms']) . '#image_rights' ?>">
        <?= $this->translate('See terms and conditions') ?>
      </a>
    </p>
  <?php endif; ?>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/image-rights.phtml -->
