<!-- START of Finna - RecordDriver/DefaultRecord/image-download.phtml -->
<?php
    if (empty($image['downloadable'])) {
        return;
    }
?>
<div class="image-link hidden-print">
    <?php $urls = $image['urls']; ?>
    <?php if ($hiRes): ?>
        <?=$this->icon('download') ?>
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle download" type="button" id="downloadMenu-<?=$index?>" data-bs-toggle="dropdown" aria-expanded="false">
                <?=$this->transEsc('Download the image')?> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu download" aria-labelledby="downloadMenu-<?=$index?>">
                <?php if (isset($urls['large'])): ?>
                    <li class="display-image"><a href="<?=$this->escapeHtmlAttr($urls['large']['url'] ?? $urls['large'])?>" download target="_blank" rel="nofollow"><?=$this->transEsc('display_image') ?> <span class="image-dimensions"></span> jpg</a></li>
                <?php endif; ?>
                <?php if (!$this->userAgent()->isBot()): ?>
                    <?php foreach ($hiRes as $size => $img): ?>
                        <?php foreach ($img as $key => $info): ?>
                            <?php
                                $imgSize = $info['data']['size'] ?? [];
                                $imageSize = '';
                                if ($imgSize) {
                                    $imageSize = !empty($imgSize['value']) && $imgSize['unit'] === 'byte' ? $this->fileSize($imgSize['value']) : '';
                                }
                                $width = $info['data']['width'] ?? [];
                                $height = $info['data']['height'] ?? [];
                                $dimensions = '';
                                if (!empty($width['value']) && !empty($height['value']) && $height['unit'] === 'pixel' && $width['unit'] === 'pixel') {
                                    $cleanWidth = preg_replace('/[^0-9]/', '', $width['value']);
                                    $cleanHeight = preg_replace('/[^0-9]/', '', $height['value']);
                                    $dimensions = "$cleanWidth x $cleanHeight px";
                                }
                                $imageInfoHtml = '';
                                if ($dimensions) {
                                    $imageInfoHtml = '<span class="image-dimensions">(' . $this->escapeHtml($dimensions);
                                    if ($imageSize) {
                                        $imageInfoHtml .= ', ' . $this->escapeHtml($imageSize) . ')</span>';
                                    } else {
                                        $imageInfoHtml .= ')</span>';
                                    }
                                }
                                if (!$dimensions && $imageSize) {
                                    $imageInfoHtml = '<span class="image-dimensions">(' . $this->escapeHtml($imageSize) . ')</span>';
                                }
                                $downloadName = str_replace('.', '-', $this->driver->getUniqueID()) . '-' . ($info['resourceID'] ?? $index) . '-' . $size;
                            ?>
                            <li><a class="dropdown-item" download="<?=$downloadName?>" href="<?=$this->escapeHtmlAttr($this->url('record-downloadfile', [], ['query' => $info['params']]))?>" rel="nofollow"> <?=$this->transEsc('high_resolution_image')?> <?=$imageInfoHtml?>  <?=$this->escapeHtml($info['format'] ?? '')?></a></li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </div>
    <?php else: ?>
        <?php
            $recordImage = $this->recordImage($this->record($this->driver));
            $originalImage = $recordImage->getMasterImage($index);
            if ($originalImage):
        ?>
            <div class="open-link">
                <a target="_blank" href="<?=$this->escapeHtmlAttr($originalImage) ?>" rel="nofollow" download>
                    <?=$this->icon('download') ?>
                    <span><?=$this->transEsc('Download the image') ?></span>
                </a>
                <span class="image-dimensions"></span>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>
<!-- END of Finna - RecordDriver/DefaultRecord/image-download.phtml -->
