<!-- START of Finna - RecordDriver/DefaultRecord/image-download.phtml -->
<div class="image-link">
    <?php if (isset($rights['copyright']) && $rights['copyright'] !== $this->transEsc('usage_F')): ?>
        <?php
            $urls = $image['urls'];
            $links = [];
        ?>
        <?php if ($hiRes): ?>
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle download" type="button" id="downloadMenu-<?=$index?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?=$this->transEsc('Download the image') ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu download" aira-labelledby="downloadMenu-<?=$index?>">
                    <?php if (isset($urls['large'])): ?>
                        <li class="display-image" ><a href="<?= $this->escapeHtmlAttr($urls['large']['url'] ?? $urls['large'])?>" download target="_blank"><?= $this->transEsc('display_image') ?> <span class="image-dimensions"></span></a></li>
                    <?php endif; ?>
                    <?php foreach ($hiRes ?? [] as $size => $img): ?>
                        <?php if ($size === 'resourceID') { continue; } ?>
                        <?php foreach ($img as $key => $info): ?>
                            <?php
                                $data = $info['data'];
                                $imageSize = '';
                                if (isset($data['size'])) {
                                    $imageSize = "({$data['size']['value']} {$data['size']['unit']})";
                                }
                                $dimensions = '';
                                if (isset($data['width']) && isset($data['height'])) {
                                    $dimensions = "({$data['width']['value']} x {$data['height']['value']} {$data['height']['unit']})";
                                }
                                $format = '.jpg';
                                if (!is_numeric($key)) {
                                    $format = ".$key";
                                }
                                $downloadName =  str_replace('.', '-', $this->driver->getUniqueID()) . '-' . $hiRes['resourceID'] ?? $key . '-' . $size;
                            ?>
                            <li><a download="<?=$downloadName?>" href="<?=$this->escapeHtmlAttr($info['url'])?>"> <?= $this->transEsc('high_resolution_image') ?> <span class="image-dimensions"><?= $dimensions ?></span> <?= $format ?> <?= $imageSize ?></a></li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php else: ?>
            <div class="open-link">
                <a target="_blank" href="<?=$this->escapeHtmlAttr($urls['master'] ?? $urls['large']) ?>" download>
                  <i aria-hidden="true" class="fa fa-download"></i>
                  <span><?=$this->transEsc('Download the image') ?></span>
                </a>
                <span class="image-dimensions"></span>
              </div>
        <?php endif; ?>
    <?php elseif (!isset($rights['copyright']) && !isset($rights['description'])): ?>
        <p class="image-rights-default"><?=$this->transEsc('Image Rights Default') ?></p>
    <?php endif; ?>
</div>
<!-- END of Finna - RecordDriver/DefaultRecord/image-download.phtml -->