<?php // No ending line feed
$searchRoute = $this->searchAction ?: $this->searchOptions($this->driver->getSearchBackendIdentifier())->getSearchAction();
if (!$this->id) {
    echo $this->url($searchRoute, [], ['query' => ['lookfor' => $this->lookfor, 'type' => 'Subject']]);
} else {
    echo $this->url(
        $searchRoute,
        [],
        ['query' => ['lookfor' => sprintf('topic:("%s") OR %s:("%s")^100000', $this->lookfor, \Finna\Search\Solr\AuthorityHelper::TOPIC_ID_FACET, $this->id)]]
    );
}
