<?php
  $searchBackendId = $this->driver->getSearchBackendIdentifier();
  $options = $this->searchOptions($searchBackendId);
  $searchRoute = $this->searchAction ?: $options->getSearchAction();
  if ($this->lookfor && $isbn = $this->isbn) {
    $query = ['lookfor' => sprintf('(%s) OR (%s:("%s")^100000)', $this->lookfor, 'isbn', $isbn)];
  } elseif ($isbn = $this->isbn) {
    $query = ['lookfor' => sprintf('%s:("%s")^100000', 'isbn', $isbn)];
  } else {
    $query = ['lookfor' => $this->lookfor, 'type' => 'AllFields'];
  }
  if (($limit = $this->searchMemory()->getLastLimit($searchBackendId))
    && $limit !== $options->getDefaultLimit()
  ) {
    $query['limit'] = $limit;
  }
  echo $this->url($searchRoute, [], compact('query'));
