<?php
  $__attributes = $this->htmlAttributes(
    [
      'class' => $this->classes,
      'href' => '#',
    ]
  );
  $__attributes->add('class', 'show-info');
  if ($this->title) {
    $__attributes->add('title', $this->title);
  }
  $additionalDataElem = !empty($this->additionalData) ? "<span class=\"field-additional-data\">{$this->additionalDataHtml}</span>" : '';
?>
<span class="ajax-content lateral-link" data-id="<?=$this->escapeHtmlAttr($this->id)?>" data-auth-id="<?=$this->escapeHtmlAttr($this->authId)?>" data-source="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" data-type="<?=$this->escapeHtmlAttr($this->type)?>">
  <a<?=$__attributes?>><span class="field-label"><?=$this->escapeHtml($this->label)?></span></a><?=$additionalDataElem?>
  <div class="field-info lateral-popover">
    <div class="content">
      <h2><?=$this->escapeHtml($this->label)?></h2>
      <?php foreach ($this->fieldLinks as $link): ?>
        <a href="<?=$link['escapedUrl']?>"><?=$this->transEsc($link['linkText'])?></a><br>
      <?php endforeach; ?>
      <?php if ($this->id): ?>
        <div class="dynamic-content">
          <i class="fa fa-spin fa-spinner"></i>
        </div>
        <div class="no-info hide alert alert-info"><?=$this->translate('field_no_info') ?></div>
      <?php endif; ?>
    </div>
    <a href="#" class="hide-info"><span class="link-text"><?=$this->translate('field_hide_info')?> <i class="fa fa-handle-close handle"></i></a>
  </div>
</span>
