<?php
  $img = $this->recordImage($this->record($this->driver));
  $urls = $this->driver->tryMethod('getURLs');

  $hasImages = !empty($this->driver->tryMethod('getAllImages'));

  $hasVideos = !empty(array_filter(
      $this->driver->tryMethod('getURLs') ?? [],
      fn($url) => isset($url['embed']) && in_array($url['embed'], ['video', 'iframe'])
  ));

  $hasAudios = !empty(array_filter(
      $this->driver->tryMethod('getURLs') ?? [],
      fn($url) => isset($url['embed']) && $url['embed'] === 'audio'
  ));

  $hasModels = !empty($this->driver->tryMethod('getModels'));

  $digitalObjects = [$hasImages, $hasVideos, $hasAudios, $hasModels];

  $hasManyDigitalObjects = count(array_filter($digitalObjects, fn($value) => $value === true)) > 1;

  function countVideos(array $urls): int {
    return count(array_filter($urls, static fn($url) => $url['embed'] ?? null === 'video' || $url['embed'] === 'iframe'));
  }

  $videoCount = countVideos($urls);

  function countImages(array $images): int {
    return count($images);
  }

  $images = $this->driver->tryMethod('getAllImages') ?? [];
  $imageCount = countImages($images);
?>

<div class="record-media">
  <?php if ($hasManyDigitalObjects): ?>
    <ul class="nav nav-pills nav-record-media" role="tablist">
      <?php if ($hasVideos): ?><li class="nav-item" role="presentation"><button type="button" role="tab" class="nav-link" data-bs-toggle="pill" href="#video"><?=$this->transEsc('Videot')?> (<?= $videoCount ?>)</button></li><?php endif; ?>
      <?php if ($hasImages): ?><li class="nav-item" role="presentation"><button type="button" role="tab" class="nav-link" data-bs-toggle="pill" href="#image"><?=$this->transEsc('Kuvat')?> (<?= $imageCount ?>)</button></li><?php endif; ?>
      <?php if ($hasModels): ?><li class="nav-item" role="presentation"><button type="button" role="tab" class="nav-link" data-bs-toggle="pill" href="#3d"><?=$this->transEsc('3d')?></button></li><?php endif; ?>
      <?php if ($hasAudios): ?><li class="nav-item" role="presentation"><button type="button" role="tab" class="nav-link" data-bs-toggle="pill" href="#audio"><?=$this->transEsc('Audio')?></button></li><?php endif; ?>
    </ul>
  <?php endif; ?>

  <div class="tab-content tab-content-record-media">
    <?php if ($hasVideos): ?>
        <?php
          $videoUrls = [];
          foreach ($this->record($this->driver)->getLinkDetails() as $url) {
            if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLinker()->getEmbeddedVideo($url['url']) == 'data-embed-iframe') {
              $videoUrls[] = $url;
            }
          }
        ?>
        <div id="video" class="tab-pane">
        <?php if ($this->config()->inlineVideoEnabled()): ?>
    <?php
      $videoUrls = [];
      foreach ($this->record($this->driver)->getLinkDetails() as $url) {
        if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLinker()->getEmbeddedVideo($url['url']) == 'data-embed-iframe') {
          $videoUrls[] = $url;
        }
      }
    ?>
    <?php if (!empty($videoUrls)): ?>
      <div class="inline-video-container">
        <div class="inline-video" id="inline-video"></div>
        <?=$this->record($this->driver)->renderTemplate('record-video-player.phtml', ['videoUrls' => $videoUrls, 'inlineVideo' => true]);?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
        </div>
      <?php endif; ?>
      <?php if ($hasImages): ?>
        <div id="image" class="tab-pane">
          <?=$this->record($this->driver)->renderTemplate('record-image-information.phtml', ['img' => $img]); ?>
        </div>
      <?php endif; ?>
      <?php if ($hasModels): ?>
        <?php
          $modelUrls = [];
          foreach ($this->record($this->driver)->getLinkDetails() as $url) {
            if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLinker()->getEmbeddedVideo($url['url']) == 'data-embed-iframe') {
              $modelUrls[] = $url;
            }
          }
        ?>
        <?php print_r($modelUrls) ?>
        <div id="3d" class="tab-pane">
          <?=$this->record($this->driver)->renderTemplate('record-3d-player.phtml');?>
        </div>
      <?php endif; ?>
      <?php if ($hasAudios): ?>
        <div id="audio" class="tab-pane">
          <h3>Menu 2</h3>
          <p>Some content in menu 2.</p>
        </div>
      <?php endif; ?>
    </div>
</div>

<?php
  $script = <<<JS

  document.addEventListener("DOMContentLoaded", function() {
    var firstTab = document.querySelector('.record-media .nav-record-media li button:first-child');
    var firstTabContent = document.querySelector('.record-media .tab-content .tab-pane:first-child');
    if (firstTab && firstTabContent) {
        firstTab.classList.add('active');
        firstTabContent.classList.add('active');
    }
    if (!firstTab && firstTabContent) {
        firstTabContent.classList.add('active');
    }
    });
JS;

  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
