<!-- START of: finna - RecordDriver/DefaultRecord/record-title-skiplink.phtml -->
    <div role="heading" aria-level="1" id="record-skip-link-target" class="visually-hidden" aria-label="<?=$this->escapeHtml($this->driver->getTitle())?>"></div>
    <h1 class="record-title hidden-xs" aria-hidden="true"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
<!-- END of: finna - RecordDriver/DefaultRecord/record-title-skiplink.phtml  -->
