<!-- START of: finna - RecordDriver/DefaultRecord/record-image-navi.phtml -->
<?php // Don't show the image links for bots except on the record view to avoid bad associations ?>
<?php $paginatedLinks = []; ?>
<?php if ($type === 'record' || !$this->userAgent()->isBot()): ?>
  <div class="recordcovers <?=$type ?><?=count($images) == 1 ? ' hidden' : ''?> <?=$type === 'list' ? ' hidden-xs hidden-sm' : ''?>"<?= $type === 'record' ? ' data-rows="2" data-row-height="35"' : ''?>>
    <?php $ind = 0; ?>
    <?php
      $maxAmount = 20;
      $paginate = is_array($images) && count($images) > 20;
    ?>

    <?php foreach ($images as $img): ?>
      <?php
        $paginatedLinks[] = [
          'small' => $img['urls']['small'],
          'medium' => $img['urls']['medium'],
          'index' => $ind
        ];
        if ($paginate && $ind > 4) {
          $ind++;
          continue;
        }

        $content = null;
        if ($type === 'list' || $type === 'list grid') {
          $content = $ind === 4 ? '&hellip;' : $ind + 1;
        } else {
          $content = '<span data-src="' . $this->escapeHtmlAttr($img['urls']['small']) . '">IMG</span>';
        }
        
        $largeImg = isset($img['urls']['large']) && is_string($img['urls']['large']);
      ?>
      <?php if (!$this->userAgent()->isBot() && ($type === 'list' || $type === 'list grid')): ?>
        <a href="<?= $this->escapeHtmlAttr($img['urls']['medium']) ?>" class="image-popup image-popup-navi<?=($ind > 4) ? ' hide' : '' ?> hidden-print" data-img-index="<?=$ind ?>"><?=$content ?></a>
      <?php elseif($this->userAgent()->isBot()): ?>
        <a href="<?=$this->escapeHtmlAttr($img['urls']['large'] ?? $img['urls']['medium']) ?>"><?=($ind + 1) ?></a>
      <?php endif; ?>
      <?php $ind++; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
<?php if (!isset($isInitialized)) : ?>
  <script>
    $(document).ready(function setPaginatedLinks(){
      finna.imagePaginator.setPaginatedImages(<?= json_encode($paginatedLinks) ?>);
    })
  </script>
  <?php endif; ?>
<!-- END of: finna - RecordDriver/DefaultRecord/record-image-navi.phtml -->
