<div class="video-accordion">
  <?php $i = 0; ?>
  <?php foreach ($videoUrls as $url): ?>
    <div class="video-item">
      <?php 
        $description = $url['desc'] ?? $this->truncateUrl($url['url']);
        $desc = $this->recordLink()->getEmbeddedVideo($url['url']) == 'data-embed-iframe' ? $this->translate('format_Video') : $description;

        $posterImage = isset($url['posterUrl']) && !empty($url['posterUrl']) ? $url['posterUrl'] : '';

        $id = 'video-container-' . $i;
        $first = ($i === 0);
      ?>
      <a class="video-link-title <?=($first) ? '' : 'collapsed'?>" data-toggle="collapse" data-target="#<?=$id?>" aria-expanded="<?($first) ? 'true': 'false'?>">
        <i class="fa fa-play-circle"></i>
        <span><?=$this->escapeHtml($desc)?></span>
        <span class="caret"></span>
      </a>
      <div class="video-link-container <?=($first) ? 'collapse in' : 'collapse'?>" id="<?=$id?>" aria-expanded="<?($first) ? 'true': 'false'?>">
        <a class="videourl fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" title="<?=$this->escapeHtmlAttr($url['url']) ?>"
            <?php if (!empty($url['videoSources'])): ?> 
              data-video-sources="<?= $this->escapeHtmlAttr(json_encode($url['videoSources'])) ?>"
            <?php endif; ?>
            <?= $this->recordLink()->getEmbeddedVideo($url['url']) ?>
            <?=!empty($url['embed']) && $url['embed'] === 'video' ? ' data-embed-video' : '' ?>
            data-poster-image = <?=$posterImage?>
        >
            <div class="video-icon"><i class="fa fa-play-circle"></i></div>
        </a>
      </div>
    </div>
    <?php $i++ ?>
  <?php endforeach; ?>
</div>
<div class="clearfix"></div>
