<!-- record-image-paginator.phtml -->
<?php // Here is a new clean base for our paginated images ?>
<?php if ($type === 'record' || !$this->userAgent()->isBot()): ?>
  <?php
    $ind = 0;
    $paginatedLinks = [];
    $usageRight = [];
  ?>
  <?php foreach ($images as $img): ?>
    <?php
      // We only need essential info about images, no need to create any html
      $obj = [
        'small' => $img['urls']['small'],
        'medium' => $img['urls']['medium'],
        'large' => $img['urls']['large'] ?? $img['urls']['medium'],
        'thmbIndex' => $ind,
        'index' => $ind++,
      ];

      $obj['description'] = $img['description'] ?? '';

      $paginatedLinks[] = $obj;
    ?>
  <?php endforeach; ?>
  <div class="recordcovers <?=$type?>">
  </div>
  <?php if (!$this->userAgent()->isBot()): ?>
      <?php if (!empty($images[0]['urls']['medium']) || !empty($images[0]['urls']['large'])): ?>
        <div class="recordcover-container">
          <a class="image-popup-trigger" href="<?=$this->recordLink()->getUrl($this->driver) ?>#image">
            <?php if (count($images) <= 1): ?>
              <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
            <?php endif; ?>
            <?php if (!empty($images[0]['urls']['large']) && $this->layout()->templateDir == 'record' && $largeImageLayout): ?>
              <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($images[0]['urls']['large']);?>"/>
            <?php else: ?>
              <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($images[0]['urls']['medium']);?>"/>
            <?php endif; ?>
            <?php if (isset($images[0]['large'])): ?>
            <i class="fa fa-magnify hidden-print"></i>
            <?php endif; ?>
          </a>
        </div>
      <?php else: ?>
        <a class="image-popup-paginator-trigger no-image" href="<?=$this->recordLink()->getUrl($this->driver) ?>#image">
          <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
          <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
        </a>
      <?php endif; ?>
    <?php endif; ?>
  <script>
    finna.imagePaginator.setPaginatedImages(<?= json_encode($paginatedLinks) ?>);
  </script>
<?php endif;?>