<?php // Do not output this: <!-- START of: finna - RecordDriver/DefaultRecord/record-image-popup.phtml --> ?>
<?php
  $recordImage = $this->recordImage($this->record($this->driver));
  $recordType = $this->driver->tryMethod('getRecordType');
  $largeImageLayout = in_array($recordType, ['lido', 'forward', 'ead', 'qdc']);
?>

<?php // Do not output this: <!-- END of: finna - RecordDriver/DefaultRecord/record-image-popup.phtml --> ?>
