<!-- START of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
<?php
  if (!$images) {
    return;
  }
  $isList = ($type === 'list' || $type === 'list grid');
  $isBot = $this->userAgent()->isBot();
  if ($isBot && $type !== 'record') {
    return;
  }
?>
<?php if ($isBot): ?>
  <?php foreach ($this->recordImage($this->record($this->driver))->getImagesForBotUser($images) as $image): ?>
    <div>
      <?php if ($image['pdf']): ?>
        <a href="<?=$this->escapeHtmlAttr($image['url'])?>"><?=$this->escapeHtml($image['id']);?></a>
      <?php else: ?>
        <img src="<?=$this->escapeHtmlAttr($image['url'])?>">
      <?php endif;?>
    </div>
    <br>
  <?php
    endforeach;
    // Notice this return statement for bots.
    return;
  ?>
<?php endif; ?>

<?php
  $settings = [
    'recordId' => $this->driver->getUniqueId(),
    'recordType' => $this->driver->tryMethod('getRecordFormat'),
    'recordSource' => $this->driver->tryMethod('getSourceIdentifier'),
    'enableImageRecordZoom' => true,
    'enableImageZoom' => '$this->record($this->driver)->getImagePopupZoom()',
    'maxRows' => 1,
    'triggerClick' => $this->imageClick ?? 'modal',
    'iconlabelClass' => 'format-' . $this->record($this->driver)->getFormatClass(end($formats)),
    'isList' => $type === 'list' || $type === 'list grid',
    'recordCovers' => 'recordcovers',
    'displayIcon' => $displayIcon,
  ];
  if ($this->driver->tryMethod('getModels')) {
    $modelSettings = $this->driver->tryMethod('getModelSettings', [], []);
    $settings['modelTranslations'] = $this->partial('Helpers/modeljs-translations.phtml');
    $settings['viewerDebug'] = $modelSettings['debug'] ?? false;
  }
?>

<div class="recordcover-container">
  <button class="next-image left" type="button"><?=$this->icon('image-previous') ?><span class="sr-only"><?= $this->transEsc('previous_image') ?></span></button>
  <a class="image-trigger init" draggable="false" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver)) ?>" data-images="<?=htmlspecialchars(json_encode($images ?? []), ENT_QUOTES, 'UTF-8');?>" data-settings="<?=htmlspecialchars(json_encode($settings ?? []), ENT_QUOTES, 'UTF-8');?>" tabindex="-1">
    <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
    <img src="<?=$this->imageSrc()->getDataPixel()?>" data-src="<?=$this->url('cover-unavailable')?>" class="recordcover<?= ($images[0]['pdf'] ?? false) ? ' pdf-cover' : ''?>" alt="<?=$this->transEsc('No Cover Image')?>">
    <?php if ($settings['triggerClick'] === 'zoom'): ?>
      <div class="image-controls btn-group" role="group" aria-label="Image controls">
        <button class="btn btn-default zoom-in"><?=$this->icon('image-zoom-in') ?></button>
        <button class="btn btn-default zoom-out"><?=$this->icon('image-zoom-out') ?></button>
        <button class="btn btn-default reset"><?=$this->icon('image-zoom-reset') ?></button>
        <button class="btn btn-default rotate-left"><?=$this->icon('image-rotate-left') ?></button>
        <button class="btn btn-default rotate-right"><?=$this->icon('image-rotate-right') ?></button>
      </div>
      <button class="btn btn-default image-fullscreen"><?=$this->icon('image-fullscreen') ?></button>
      <div class="image-loading-spinner"><?=$this->icon('spinner') ?></div>
      <div id="osd-image"></div>
    <?php endif; ?>
  </a>
  <span class="hidden-trigger" hidden></span>
  <button class="next-image right" type="button"><?=$this->icon('image-next') ?><span class="sr-only"><?= $this->transEsc('next_image') ?></span></button>
</div>

<div class="recordcover-image-detail">
  <p class="image-description"></p>
</div>
<div class="paginator-info"><span class="image-index"></span></div>

<div class="recordcovers <?=$this->escapeHtmlAttr($type)?>">
  <button class="left-button" type="button" title="<?= $this->transEsc('previous_images') ?>"><?=$this->icon('image-previous') ?><span class="sr-only"><?= $this->transEsc('previous_images') ?></span></button>
  <div class="track-holder paginator-mask">
    <div class="finna-element-track"></div>
  </div>
  <button class="right-button" type="button" title="<?= $this->transEsc('next_images') ?>"><?=$this->icon('image-next') ?><span class="sr-only"><?= $this->transEsc('next_images') ?></span></button>
</div>
<?php if ($settings['maxRows'] > 1): ?>
  <div class="recordcovers-more more-area">
    <button type="button" class="show-more-images"><?= $this->transEsc('more') ?> <?=$this->icon('image-more') ?></button>
    <button type="button" class="show-less-images"><?= $this->transEsc('less') ?> <?=$this->icon('image-less') ?></button>
  </div>
<?php endif; ?>

<?php
  $script = <<<JS



JS;

  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>


<!-- END of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
