<!-- record-image-paginator.phtml -->
<?php // Here is a new clean base for our paginated images ?>
<?php
  $isList = ($type === 'list' || $type === 'list grid');
  $enableImageZoom = in_array($this->driver->tryMethod('getRecordType'), ['lido', 'forward', 'ead', 'qdc']);
?>
<?php if ($type === 'record' || !$this->userAgent()->isBot()): ?>
  <?php
    $ind = 0;
    $paginatedLinks = [];
  ?>
  <?php foreach ($images as $img): ?>
    <?php
      // We only need essential info about images, no need to create any html
      $obj = [
        'small' => $img['urls']['small'],
        'medium' => $img['urls']['medium'] ?? $img['urls']['small'],
        'largest' => $img['urls']['large'] ?? $img['urls']['medium'] ?? $img['urls']['small'],
        'index' => $ind++,
        'description' => $img['description'] ?? ''
      ];

      $paginatedLinks[] = $obj;
    ?>
  <?php endforeach; ?>
  <?php if (!$this->userAgent()->isBot()): ?>
    <?php if (!empty($images[0]['urls']['medium']) || !empty($images[0]['urls']['large'])): ?>
      <div class="recordcover-container">
        <a class="image-popup-trigger" href="<?=$this->recordLink()->getUrl($this->driver) ?>#image">
          <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
          <img data-src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
        </a>
      </div>
    <?php else: ?>
      <a class="image-popup-paginator-trigger no-image" href="<?=$this->recordLink()->getUrl($this->driver) ?>#image">
        <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
        <img data-src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      </a>
    <?php endif; ?>
  <?php else: ?>
    <a href="<?=$this->escapeHtmlAttr($img['urls']['large'] ?? $img['urls']['medium']) ?>"><?=($ind + 1) ?></a>
  <?php endif; ?>
  <div class="recordcover-image-detail">
    <p class="image-description">
    </p>
  </div>
  <div class="recordcovers <?=$type?>">
  </div>
  <div class="recordcovers-more more-area">
    <span class="line"></span>
    <button type="button" class="show-more-images more-link"><span class="less-more"></span> <i class="fa fa-arrow-down"></i></button>
    <span class="line"></span>
  </div>
  <?php if (count($paginatedLinks) > 0): ?>
    <script>
      <?php $settings = [
        'recordId' => $this->driver->getUniqueId(),
        'source' => $this->driver->getSourceIdentifier(),
        'recordType' =>  $this->driver->tryMethod('getRecordType'),
        'imagesPerPage' => 8,
        'enableImageZoom' => $enableImageZoom
      ]?>
      <?php if ($type === 'list' || $type === 'list grid'): ?>
        finna.imagePaginator.initMiniPaginator(
          <?= json_encode($paginatedLinks) ?>,
          <?= json_encode($settings) ?>
        );
      <?php else: ?>
        finna.imagePaginator.initPaginator(
          <?= json_encode($paginatedLinks) ?>,
          <?= json_encode($settings) ?>
        );
      <?php endif; ?>
    </script>
  <?php endif; ?>
<?php endif;?>