<!-- START of: finna - RecordDriver/DefaultRecord/reservation-list-entry.phtml -->
<?php
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getSourceIdentifier();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
?>
<!-- start list-entry -->
<div class="result record-container myresearch-row <?=$this->record($this->driver)->getContainerJsClasses()?>">
    <div class="checkboxFilter">
      <div class="checkbox">
        <?php // Request a checkbox with a label (can't add the label here as checkbox template contains more than one field): ?>
        <?=$this->record($this->driver)->getCheckbox('', false, true) ?>
      </div>
    </div>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($id) ?>" class="hiddenId">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($source) ?>" class="hiddenSource">

  <div class="media">
    <div class="media-body">
      <div class="result-body">
        <div class="resultItemLine1">
          <?php $missing = $this->driver instanceof \VuFind\RecordDriver\Missing; ?>
          <?php if (!$missing): ?>
            <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver))?>">
          <?php endif; ?>
          <h3><?=$this->record($this->driver)->getTitleHtml()?></h3>
          <?php if (!$missing): ?>
            <span class="sr-only"> <?=$this->transEsc('To the record')?></span></a>
          <?php endif; ?>
        </div>
        <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
          <div class="title-alt-script">
            <?=$this->escapeHtml($altTitle)?>
          </div>
        <?php endforeach; ?>

        <div class="record-core-metadata">
          <?=$this->record($this->driver)->getFormatList() ?><br>
          <?php if($this->driver->isCollection()): ?>
            <?=implode('<br>', array_map([$this, 'escapeHtml'], $this->driver->getSummary())); ?>
          <?php else: ?>
            <?php $authors = $this->driver->tryMethod('getAuthorsWithRoles');
            if (!empty($authors)): ?>
              <div class="truncate-field" data-rows="1">
                <?php foreach($authors as $index => $author): ?>
                  <?=($index > 0 ? '; ' : '')?><?=$this->record($this->driver)->getLinkedFieldElement('author', $author['name'], $author, ['date' => true, 'role' => true, 'authorityType' => $author['type'] ?? null])?>
                <?php endforeach; ?>
              </div>
            <?php elseif ($authors = $this->driver->getPrimaryAuthors()): ?>
              <div class="truncate-field" data-rows="1">
                <?php foreach($authors as $index => $author): ?>
                  <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?></a>
                <?php endforeach; ?>
              </div>
            <?php endif; ?>

            <?php
              $journalTitle = $this->driver->getContainerTitle();
              $summDate = $this->driver->getPublicationDates();
              $dates = $this->driver->tryMethod('getResultDateRange', []);
            ?>
            <?php if (!empty($journalTitle)): ?>
              <?=!empty($summAuthor) ? '' : ''?>
              <?=/* TODO: handle highlighting more elegantly here */ $this->transEsc('Published in') . ' <a href="' . $this->record($this->driver)->getLink('journaltitle', str_replace(['{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'], '', $journalTitle)) . '">' . $this->highlight($journalTitle) . '</a>';?>
              <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
            <?php elseif (!empty($summDate)): ?>
              <?=!empty($summAuthor) ? '' : ''?>
                <?=$this->escapeHtml($summDate[0])?>
            <?php elseif ($dates): ?>
                <?=$this->escapeHtml($dates[0]);?><?php if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><?php endif; ?>
            <?php endif; ?>
            <?php $summInCollection = $this->driver->getContainingCollections();
            if (false && !empty($summInCollection)): ?>
              <?php foreach ($summInCollection as $collId => $collText): ?>
                <div>
                  <b><?=$this->transEsc('in_collection_label')?></b>
                  <a class="collectionLinkText" href="<?=$this->url('collection', ['id' => $collId])?>?recordID=<?=urlencode($this->driver->getUniqueID())?>">
                    <?=$this->escapeHtml($collText)?>
                  </a>
                </div>
              <?php endforeach; ?>
            <?php endif; ?>
          <?php endif; ?>
        </div>

        <div class="last">
          <?php if(!$this->driver->isCollection()) {
              if ($snippet = $this->driver->getHighlightedSnippet()) {
                if (!empty($snippet['caption'])) {
                  echo '<strong>' . $this->transEsc($snippet['caption']) . ':</strong> ';
                }
                if (!empty($snippet['snippet'])) {
                  echo $this->translate(
                      'highlight_snippet_html',
                      ['%%snippet%%' => $this->highlight($snippet['snippet'])]
                  ) . '<br>';
                }
              }
            } ?>

          <?php
            /** @var \Finna\View\Helper\Root\Record */
            $recordHelper = $this->record($this->driver);
          ?>
          <?=$recordHelper->renderTemplate('holdings.phtml');?>
          <?=$recordHelper->getOnlineUrls('results');?>
          <?=$recordHelper->getPreviews();?>
        </div>
        <div class="myresearch-notes">
        <?php
          if (!empty($notes)):
            $notes = trim(implode('', $notes));
        ?>
          <div class="note-info <?= $notes ? '' : ' hide' ?>"><strong><?=$this->transEsc('Note')?>:</strong></div>
        <?php endif; ?>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/reservation-list-entry.phtml -->
