<!-- START of: finna - myresearch/import-success.phtml -->
<div class="jumbotron success">
    <strong>Lisääminen onnistui</strong>
    <br><br>
    <strong>Omaan tiliin lisättiin:</strong>
    <ul>
        <li><?=$this->lists ?> uutta listaa</li>
        <li><?=$this->resources ?> uutta omaa suosikkia</li>
        <li><?=$this->searches ?> tallennettua hakua</li>
    </ul>
</div>
<!-- END of: finna - myresearch/import-success.phtml -->
