<!-- START of: finna - myresearch/import.phtml -->
<h1><?=$this->transEsc('import_favorites') ?></h1>
<div id="favorites-import-dialog">
    <form id="favorites-import-form" class="form-inline" method="post" enctype="multipart/form-data"  data-lightbox-ignore>
        <input id="filename" type="text" class="form-control col-md-7" readonly>
        <label class="btn btn-primary btn-file">
            <?=$this->transEsc('import_favorites_select_file') ?>
            <input type="file" style="display: none;" name="favorites-file">
        </label>
        <button class="btn btn-primary" onclick="finna.favorites.upload()"><?=$this->transEsc('import_favorites_upload') ?></button>
    </form>
</div>
<?
    echo $this->inlineScript()->appendFile('finna-favorites.js');
?>
<!-- END of: finna - myresearch/import.phtml -->
