<!-- START of: finna - myresearch/import.phtml -->
<h1>Tuo suosikit ja haut tiedostosta</h1>
<div class="favorites-import-dialog">
    <form id="favorites-import-form" class="form-inline" method="post" enctype="multipart/form-data"  data-lightbox-ignore>
        <input id="filename" type="text" class="form-control col-sm-7">
        <label class="btn btn-primary btn-file">
            Valitse tiedosto...
            <input type="file" style="display: none;" name="favorites-file">
        </label>
        <button class="btn btn-primary" onclick="finna.favorites.upload()">Lisää suosikit ja haut</button>
    </form>
</div>
<?
    echo $this->inlineScript()->appendFile('finna-favorites.js');
?>
<!-- END of: finna - myresearch/import.phtml -->
