<!-- START of: finna - myresearch/import-success.phtml -->
<div class="alert alert-info">
    <h4><?=$this->transEsc('import_favorites_success') ?></h4>
    <strong><?=$this->transEsc('import_favorites_results_header') ?>:</strong>
    <ul>
        <li><?=$this->lists ?> <?= $this->transEsc('import_favorites_results_new_lists') ?></li>
        <li><?=$this->resources ?> <?= $this->transEsc('import_favorites_results_new_resources') ?></li>
        <li><?=$this->searches ?> <?= $this->transEsc('import_favorites_results_new_searches') ?></li>
    </ul>
</div>
<!-- END of: finna - myresearch/import-success.phtml -->
