<!-- START of: finna - Auth/Suomifi/login.phtml -->
<?php $account = $this->auth()->getManager(); ?>
<?php $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<div>
  <div class="login-col shibboleth-login suomifi-login">
    <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>" data-lightbox-ignore>
      <img src="<?=$this->imageLink('login_suomifi.png') ?>" alt="<?=$this->transEscAttr('Suomi.fi Login') ?>">
      <span class="sr-only"><?=$this->transEsc('Suomi.fi Login')?></span>
    </a>
  </div>
  <div class="login-col">
    <?=$this->icon('info', 'login-info-icon') ?>
    <div class="login-description">
      <p class="login-info">
        <?=$this->translate('login_desc_suomifi_html')?>
      </p>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<?php if ($tmpl = $this->content()->findTemplateForLng('Auth/Suomifi/terms', true)): ?>
  <?=$this->partial($tmpl) ?>
<?php endif; ?>
<!-- END of: finna - Auth/Suomifi/login.phtml -->
