<!-- START of: finna - RecordDriver/AipaLrmi/core.phtml -->
<div style="border: 1px solid lightgray; padding: 1em;">
<h2><?= $driver->getTitle() ?></h2>
<?php if ($descriptions = $driver->getDescriptions()): ?>
  <div class="truncate-field wide summary recordSummary">
    <?= $this->recordFieldMarkdown()->toHTML(implode("\n\n", $descriptions), '<br>') ?>
  </div>
<?php endif; ?>

<?/* Display Main Details */?>
<?php
  $formatter = $this->recordDataFormatter();
  $filteredFields = $formatter->filterLrmiFields($formatter->getDefaults('core'));
  $coreFields = $formatter->getGroupedData($driver, $formatter->getGroupedFields([
    ['lines' => [
      'Educational Role',
      'Educational Level',
      'Learning Resource Type',
      'Educational Subject',
      'Objective and Content',
      'Subjects',
      'Language',
    ]]
  ], $filteredFields, null, null, ['skipGroup' => true]));
?>
<?php if (!empty($coreFields)): ?>
  <table class="table table-finna-record record-details record-field-groups" role="presentation">
    <?=$this->record($driver)->renderTemplate('core-field-groups.phtml', ['data' => $coreFields]);?>
  </table>
<?php endif; ?>
<?/* End Main Details */?>

<?php $materials = $driver->getMaterials() ?>
<?php foreach ($materials as $material): ?>
  <div style="border: 1px solid lightgray; padding: 1em;">
  <?php if (isset($material['driver'])): ?>
    <h3><?= $this->escapeHtml($material['driver']->getTitle()) ?></h3>
    <p><?= $this->escapeHtml($material['notes']) ?></p>
  <?php else: ?>
    Tietuetta <?= $material['id'] ?> ei löytynyt.
  <?php endif; ?>
  </div>
<?php endforeach; ?>
</div>
<!-- END of: finna - RecordDriver/AipaLrmi/core.phtml -->
