<!-- START of: finna - RecordDriver/AipaLrmi/core.phtml -->
<?php
  $rights = $this->driver->getAccessRestrictionsType($this->layout()->userLang);
  $summary = $this->driver->getSummary();
  $externalLink = $this->driver->getExternalLink();
  $materials = $this->driver->getMaterials($this->layout()->userLang);
  $dateCreated = $this->driver->getDateCreated();
  $dateModified = $this->driver->getDateModified();
  $img = $this->recordImage($this->record($this->driver));
  $thumbnail = false;
  $thumbnailAlignment = false;
  $formats = $this->driver->getFormats();
  ob_start(); ?>
  <div class="media-<?=$thumbnailAlignment?>">
    <?=$this->record($this->driver)->renderTemplate('record-image-information.phtml', ['img' => $img, 'displayIcon' => true, 'source' => 'L1', 'imageClick' => 'none']);?>

    <?php if ($this->record($this->driver)->getOrganisationMenuPosition() === 'inline'): ?>
      <div class="organisation-menu">
        <?=$this->render('record/record-organisation-menu.phtml') ?>
      </div>
    <?php endif; ?>

    <?=$this->record($this->driver)->renderTemplate('record-post-thumbnail.phtml');?>
  </div>
  <?php $thumbnail = ob_get_contents(); ?>
<?php ob_end_clean(); ?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <h2 property="name" class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h2>
  <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
    <?=$thumbnail ?>
  <?php endif; ?>
  <div class="media-body record-information">
    <h2 property="name" class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h2>
    <?php if (!empty($formats)): ?>
      <span class="recordFormat"><?=$this->record($this->driver)->getFormatList()?></span>
    <?php endif; ?>
    <div class="record-core-metadata">
      <?php if ($results = $this->driver->getNonPresenterAuthors()): ?>
        <div class="truncate-field recordAuthors">
          <strong><?= $this->transEsc('Curated By') ?>:</strong>
          <span property="author">
            <?php foreach ($results as $index => $author): ?>
              <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?><?php if (!empty($author['affiliation'])): ?>, <?= $this->escapeHtml($author['affiliation']) ?><?php endif;?></a>
            <?php endforeach; ?>
          </span>
        </div>
      <?php endif; ?>
      <?php
        $formatter = $this->recordDataFormatter($this->driver);
        $filteredFields = $formatter->getDefaults();
        $levelFields = $formatter->getGroupedData($this->driver, $formatter->getGroupedFields([
          ['lines' => [
            'Educational Level',
            'Educational Subject',
          ]]
        ], $filteredFields, null, null, ['skipGroup' => true]));
      ?>
      <table class="table table-finna-record record-details record-field-groups" role="presentation">
        <?= $this->record($this->driver)->renderTemplate('core-field-groups.phtml', ['data' => $levelFields]) ?>
      </table>
      <?= $this->record($this->driver)->getMaterialDisclaimer() ?>
      <?php if (!empty($summary)): ?>
        <div class="material-description">
          <?= $this->escapeHtml(implode('<br>', $summary)); ?>
        </div>
      <?php endif; ?>
    </div>

    <?php
      $objectivesFields = $formatter->getGroupedData($this->driver, $formatter->getGroupedFields([
        ['lines' => [
          'Objective and Content',
        ]]
      ], $filteredFields, null, null, ['skipGroup' => true]));
      ob_start();
    ?>
    <table class="table table-finna-record record-details record-field-groups" role="presentation">
      <?= $this->record($this->driver)->renderTemplate('core-field-groups.phtml', ['data' => $objectivesFields]) ?>
    </table>
    <?php
      $content = ob_get_clean();
      $content .= $this->recordFieldMarkdown()->toHtml($this->driver->getStudyObjectives() ?? '');
    ?>
    <?= $this->render('components/molecules/containers/finna-panel', [
        'attributes' => ['class' => ['finna-panel-default', 'organisation-info-panel']],
        'heading' => $this->transEsc('aipa_lrmi_objectives'),
        'headingLevel' => 4,
        'content' => $content,
        'headingId' => uniqid('heading-'),
        'collapseId' => uniqid('collapse-')
      ]); ?>

    <?= $this->render('components/molecules/containers/finna-panel', [
        'attributes' => ['class' => ['finna-panel-default', 'organisation-info-panel']],
        'heading' => $this->transEsc('aipa_lrmi_assignment_ideas'),
        'headingLevel' => 4,
        'content' => $this->recordFieldMarkdown()->toHtml($this->driver->getAssignmentIdeas()),
        'headingId' => uniqid('heading-'),
        'collapseId' => uniqid('collapse-')
      ]); ?>

    <?= $this->record($this->driver)->renderEncapsulatedRecords() ?>

    <?php if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
      <div>
        <?=$this->render($template)?>
      </div>
    <?php endif; ?>
  </div>
</div>
<!-- END of: finna - RecordDriver/AipaLrmi/core.phtml -->
