<!-- START of: finna - search/advanced/multiselect.phtml -->
<?php
  // Convert the array to be usable in the multiselect component
  $list = $this->list['list'];
  foreach ($list as $key => &$value) {
    $op = ($value['operator'] === 'OR' ? '~' : '');
    $value['value'] = "{$op}{$this->field}:{$value['value']}";
  }
?>
<div class="facet">
  <div class="solr-adv-filter <?=$this->escapeHtmlAttr(str_replace(' ', '', $this->field))?>-container">
    <finna-multiselect
      data-clear-text="<?=$this->transEsc('Clear Selections')?>"
      data-label-id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $this->field))?>"
      data-label-text="<?=$this->transEsc($this->list['label'])?>:"
      data-label="<?= $this->transEsc('Add filter') . ' ' . $this->transEsc($this->list['label']) ?>"
      data-placeholder="<?=$this->transEsc('search_placeholder')?>"
      data-entries="<?=htmlspecialchars(json_encode($list), ENT_QUOTES, 'UTF-8');?>"
    ></finna-multiselect>
  </div>
</div>
<!-- END of: finna - search/advanced/multiselect.phtml -->
