<!-- START of: finna - search/advanced/solr.phtml -->
<?php if (!empty($this->facetList) || !empty($this->checkboxFacets)): ?>
<?php
  if (isset($this->saved) && is_object($this->saved)) {
    $searchFilters = $this->saved->getParams()->getFilterList(true);
    $checkboxFilters = $this->saved->getParams()->getCheckboxFacets();
    $usedCheckboxFilters = [];
    foreach ($checkboxFilters as $filter) {
        if ($filter['selected']) {
            array_push($usedCheckboxFilters, $filter);
        }
    }
    // Remove date range filter (search_daterange_mv) and geographic filters so that
    // they don't get included in the list of active filters
    $searchFilters = $this->saved->getParams()->removeDateRangeFilter($searchFilters);
    $searchFilters = $this->saved->getParams()->removeGeographicFilters($searchFilters);
    $hiddenFilters = $this->saved->getParams()->getHiddenFilters();
  }
?>
  <div>
    <h4><?=$this->transEsc('Limit To')?></h4>
  </div>
  <div>
    <div class="option-container">
      <?php if (!empty($this->checkboxFacets)): ?>
        <div class="checkboxFilter">
          <?=$this->render('search/advanced/checkbox-filters.phtml')?>
        </div>
      <?php endif; ?>
      <fieldset class="well limit-to facets">
        <legend class="sr-only"><?=$this->transEsc('Limit To')?></legend>
        <div class="facet-container">
          <?php
          $this->htmlElement()->addAttributeTemplate('finna-multiselect', [
            'class' => 'finna-multiselect form-control',
            'name' => 'filter[]',
            'multiple' => 'multiple'
          ]);
          ?>
          <?php $i = 0; ?>
          <?php foreach ($this->facetList as $field => $list): ?>
            <div class="facet">
              <div class="solr-adv-filter <?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>-container">
                <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>"><?=$this->transEsc($list['label'])?>:</label>
                <?php
                $multiSelect = [
                  'data-label' => $this->translate($list['label']),
                  'id' => 'limit_' . str_replace(' ', '', $field)
                ];
                ?>
                <div class="multiselect-dropdown" id="">
                  <select aria-labelledby="" <?= $this->htmlElement()->getAttributes($multiSelect, 'finna-multiselect') ?>>
                    <?php if (is_array($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
                      <?php foreach ($list['list'] as $value): ?>
                        <?php
                        $display = str_pad('', 4 * $value['level'] * 6, '&nbsp;', STR_PAD_LEFT) . $this->escapeHtml($value['displayText']);

                        $listAttributes = [
                          'value' => ($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"',
                          'selected' => (isset($value['selected']) && $value['selected'])? 'selected' : ''
                        ];
                        ?>
                        <option <?= $this->htmlElement()->getAttributes($listAttributes); ?>><?=$display?></option>
                      <?php endforeach; ?>
                    <?php else: ?>
                      <?php
                        // Sort the current facet list alphabetically; we'll use this data
                        // along with the foreach below to display facet options in the
                        // correct order.
                        $sorted = [];
                        foreach ($list['list'] as $i => $value) {
                          if (!empty($value['displayText'])) {
                            $sorted[$i] = $value['displayText'];
                          }
                        }
                        natcasesort($sorted);
                      ?>
                      <?php foreach ($sorted as $i => $display): ?>
                        <?php $value = $list['list'][$i]; ?>
                        <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($display)?></option>
                      <?php endforeach; ?>
                    <?php endif; ?>
                  </select>
                  <label></label>
                  <div class="ms-input-wrapper" role="combobox" aria-expanded="false" aria-owns="<?= 'multiselect_' . $i ?>" aria-haspopup="listbox">
                    <input aria-autocomplete="both" aria-controls="<?= 'multiselect_' . $i ?>" aria-activedescendant="" aria-label="<?= $this->translate('add_selection');?>" class="form-control multiselect-input" type="text">
                    <span class="caret"></span>
                  </div>
                  <ul class="multiselect-dropdown-menu" role="listbox" aria-multiselectable="true" id="<?= 'multiselect_' . $i ?>">
                  </ul>
                  <div class="multiselect-selected">
                    <span class="removed-header"><?= $this->translate('none_selected');?></span>
                  </div>
                </div>
              </div>
            </div>
          <?php endforeach; ?>
        </div>
        <div class="information"><p class="information-text"><?=$this->transEsc('advanced_search_information_text_facets')?></p></div>
      </fieldset>
      <?php if (!empty($this->daterange)): ?>
        <div class="ranges-container well limit-to">
          <?=$this->render('search/advanced/ranges.phtml', ['searchClassId' => $this->searchClassId, 'ranges' => $this->daterange])?>
        </div>
      <?php endif; ?>
    </div>
    <?php if (!empty($searchFilters) || !empty($usedCheckboxFilters)): ?>
      <h4><?=$this->transEsc("adv_search_filters")?></h4>
      <fieldset class="well limit-to">
        <?=$this->render('search/advanced/filters.phtml', ['usedCheckboxFilters' => $usedCheckboxFilters, 'searchFilters' => $searchFilters])?>
      </fieldset>
    <?php endif; ?>
  </div>
<?php endif; ?>
<?=$this->render('search/advanced/map.phtml', ['searchClassId' => $this->searchClassId, 'saved' => $this->saved])?>
<?php if (isset($this->illustratedLimit)): ?>
  <fieldset>
    <legend><?=$this->transEsc("Illustrated")?>:</legend>
    <?php foreach ($this->illustratedLimit as $current): ?>
      <input id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected']?' checked="checked"':''?>/>
      <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br/>
    <?php endforeach; ?>
  </fieldset>
<?php endif; ?>
<!-- END of: finna - search/advanced/solr.phtml -->
