<!-- START of: finna - RecordDriver/EDS/online-url-list.phtml -->
<?php foreach ($this->urls as $current): ?>
  <?php
    $url = $current['url'];
    $target = ' target="_blank"';
    if ('#' === $url[0]) {
      $url = $this->recordLinker()->getUrl($this->driver) . $url;
      $target = '';
    } else {
      $url = $this->proxyUrl($url);
    }
  ?>
  <a href="<?=$this->escapeHtmlAttr($url)?>" class="fulltext<?=!empty($current['citation']) ? ' citation' : ''?>"<?=$target?> aria-label="<?=$this->transEsc($current['desc'])?> <?=$this->transEsc('external_online_link')?>"><?=$this->icon('external-link') ?> <?=$this->transEsc($current['desc'])?></a>
<?php endforeach; ?>
<!-- END of: finna - RecordDriver/EDS/online-url-list.phtml -->
