<!-- START of: finna - RecordDriver/Primo/core-fields.phtml -->
<div class="record-details">
  <?php
    $formatter = $this->recordDataFormatter($this->driver);
    $coreFields = $formatter->getData(
        $formatter->filterPrimoFields($formatter->getDefaults($this->defaults))
    );
  ?>
  <?php if (!empty($coreFields)): ?>
    <table class="table table-finna-record record-details" role="presentation">
      <?=$this->record($this->driver)->renderTemplate('core-fields.phtml', ['coreFields' => $coreFields]);?>
    </table>
  <?php endif; ?>
  <?=$openUrl ? $openUrl->renderMoreOptions() : '' ?>
</div>
<!-- END of: finna - RecordDriver/Primo/core-fields.phtml -->
