<!-- START of: custom - layout/Additions/privacyAdditions_sv.phtml -->
<h2>Den Finna-söktjänst som du använder och personuppgifter</h2>
<p>Följande tilläggstjänster har integrerats i xxx-söktjänsten som du använder, och för behandlingen av personuppgifterna i tjänsten ansvarar NN (ange den organisation som ansvarar för behandlingen):
</p>
<table class="content-table">
  <tr>
    <td><strong>Tilläggstjänst</strong></td>
    <td><strong>Personuppgifter som behandlas</strong></td>
  </tr>
  <tr>
    <th>lorem ipsum (ange tilläggstjänsten, såsom chatbot, integration med sociala medier eller system för bokning av lokaler)</th>
    <td>lorem ipsum (ange de personuppgifter som behandlas i tilläggstjänsten)</td>
  </tr>
</table>
<p>Mer information om behandlingen av personuppgifter finns i NN:s dataskyddsbeskrivning. (länk till den ansvariga aktörens dataskyddsbeskrivning)
</p>
<!-- END of: custom - layout/Additions/privacyAdditions_sv.phtml -->