<!-- START of: custom - layout/Additions/privacyAdditions_fi.phtml -->
<h2>Käyttämäsi Finna-hakupalvelu ja henkilötiedot</h2>
<p>Käyttämääsi xxx-hakupalveluun on integroitu seuraavat lisäpalvelut, joiden henkilötietojen käsittelystä vastaa NN (kirjataan käsittelystä vastaava organisaatio):
</p>
<table class="content-table">
  <tr>
    <td><strong>Tieto</strong></td>
    <td><strong>Tarkoitus</strong></td>
  </tr>
  <tr>
    <th>lorem ipsum (kirjataan lisäpalvelu, kuten esim. chatbot, sosiaalisen median integraatio tai tilavarausjärjestelmä)</th>
    <td>lorem ipsum (kirjataan lisäpalvelussa käsiteltävät henkilötiedot)</td>
  </tr>
</table>
<p>Lisätietoa henkilötietojen käsittelystä löytyy NN:n tietosuojaselosteesta. (linkataan näkymän vastuutahon tietosuojaseloste)
</p>
<!-- END of: custom - layout/Additions/privacyAdditions_fi.phtml -->
