<!-- START of: custom - layout/Additions/privacyAdditions_en-gb.phtml -->
<h2>Your Finna search service and personal data</h2>
<p>The following additional services have been integrated into the XXX search service you are using, with NN (enter the organisation responsible for processing) being responsible for the processing of personal data in the additional services:
</p>
<table class="content-table">
  <tr>
    <td><strong>Additional service</strong></td>
    <td><strong>Processed personal data</strong></td>
  </tr>
  <tr>
    <th>lorem ipsum (enter an additional service, including chatbot, social media integration or facility booking system)</th>
    <td>lorem ipsum (enter the personal data processed in the additional service)</td>
  </tr>
</table>
<p>More information about the processing of personal data is available in NN’s privacy policy. (link to the responsible organisation’s privacy policy)
</p>
<!-- END of: custom - layout/Additions/privacyAdditions_en-gb.phtml -->
