<!-- START of: finna - RecordDriver/SolrAuthDefault/core-fields.phtml -->
<?php
  $formatter = $this->recordDataFormatter($this->driver);
  $coreFields = $formatter->getData($formatter->getDefaults($this->defaults));
?>
<?php if (!empty($coreFields)): ?>
  <table class="table table-finna-record record-details" role="presentation">
    <?=$this->record($this->driver)->renderTemplate('core-fields.phtml', ['coreFields' => $coreFields]);?>
  </table>
<?php endif; ?>
<!-- END of: finna - RecordDriver/SolrAuthDefault/core-fields.phtml -->
