<!-- START of: finna - RecordDriver/SolrAuthDefault/core.phtml -->
<?php
  $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
?>
<?php $this->headScript()->appendFile("finna-record.js"); ?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <h1 property="name" class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
  <div class="media-body record-information">
      <h1 property="name" class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>

      <?/* Display anchor links to authority records tabs */?>
      <?php if ($authSummary = $this->record($this->driver)->getAuthoritySummary()): ?>
        <div class="authority-records-summary">
          <?php if (!empty($authSummary['author'] && in_array('AuthorityRecordsAuthor', array_keys($this->tabs)))): ?>
            <div>
              <div class="text"><?= $this->transEsc('authority_records_author')?></div>
              <div class="count">
                <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'AuthorityRecordsAuthor')?>#tabnav">
                  <?=$this->translate('authority_records_count', ['%%count%%' => $authSummary['author']]);?>
                </a>
              </div>
            </div>
          <?php endif; ?>
          <?php if (!empty($authSummary['topic']) && in_array('AuthorityRecordsTopic', array_keys($this->tabs))): ?>
            <div>
              <div class="text"><?= $this->transEsc('authority_records_topic')?></div>
              <div class="count">
                <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'AuthorityRecordsTopic')?>#tabnav">
                  <?=$this->translate('authority_records_count', ['%%count%%' => $authSummary['topic']]);?>
                </a>
              </div>
            </div>
          <?php endif; ?>
        </div>
      <?php endif; ?>

      <?php $summ = $this->driver->getSummary(); if (!empty($summ)): ?>
      <div class="truncate-field wide recordSummary">
        <p class="summary">
        <?php foreach ($summ as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
        </p>
      </div>
      <?php endif; ?>

      <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
        <?php /* Display the lists that this record is saved to */ ?>
        <div class="savedLists" id="savedLists">
          <strong><?=$this->transEsc("Saved in")?>:</strong>
        </div>
      <?php endif; ?>

      <?/* Display Main Details */?>
      <?php
        $formatter = $this->recordDataFormatter();
        $coreFields = $formatter->getDefaults('authority');
        $coreFields = $formatter->getData($driver, $coreFields);
      ?>
      <?php if (!empty($coreFields)): ?>
        <table class="table table-finna-record record-details">
          <?=$this->record($this->driver)->renderTemplate('core-fields.phtml', ['coreFields' => $coreFields]);?>
        </table>
      <?php endif; ?>
      <?/* End Main Details */?>

      <?php if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
      <div>
        <?=$this->render($template)?>
      </div>
      <?php endif; ?>
    </div>
</div>
<!-- END of: finna - RecordDriver/SolrAuthDefault/core.phtml -->
