<?php foreach ($data as $url): ?>
  <?php
    $title = $url['title'];
    if (!empty($url['info'])) {
      $title .= ' <span class="info">' . $url['info'] . '</span>';
    }
  ?>
  <?php if (!empty($url['url'])): ?>
    <a href="<?=$url['url']?>"><?=$title?></a><?= $url['subtitle'] ? (' ' . $url['subtitle']) : '' ?>
  <?php else: ?>
    <?=$title?>
  <?php endif; ?>
  <br />
<?php endforeach; ?>
