<div class="authority-record-count-container">
<?php if (!empty($this->count['author'] && in_array('AuthorityRecordsAuthor', array_keys($this->tabs)))): ?>
  <div class="info-row author">
    <?php if ($title = ($this->titles['author'] ?? null)): ?>
      <div class="text"><?= $this->transEsc($title)?></div>
    <?php endif ?>
    <div class="count">
      <a href="<?=$this->recordLink()->getTabUrl($driver, 'AuthorityRecordsAuthor')?>#tabnav">
        <?=$this->transEsc($this->labels['author'], ['%%count%%' => $this->count['author']]);?>
      </a>
    </div>
  </div>
<?php endif; ?>

<?php if (!empty($this->count['topic']) && in_array('AuthorityRecordsTopic', array_keys($this->tabs))): ?>
  <div class="info-row topic">
    <?php if ($title = ($this->titles['topic'] ?? null)): ?>
      <div class="text"><?= $this->transEsc($title)?></div>
    <?php endif ?>
    <div class="count">
      <a href="<?=$this->recordLink()->getTabUrl($driver, 'AuthorityRecordsTopic')?>#tabnav">
        <?=$this->transEsc($this->labels['topic'], ['%%count%%' => $this->count['topic']]);?>
      </a>
    </div>
  </div>
<?php endif; ?>
</div>
