<!-- START of: finna - record/video.phtml -->

<div>
  <video id="video-player" class="video-js" controls>
    <!--<source src="http://elo.salama.tv.funet.fi/vod/_definst_/mp4:fi/kava/elonet/2012/MV-266_Polyteekkarifilmi_470272_klippi.mp4/manifest.mpd" type="application/dash+xml">-->
  </video>
</div>

<script src="/vufind2/themes/finna/js/vendor/video.min.js"></script>
<script src="/vufind2/themes/finna/js/vendor/videojs-dash.min.js"></script>

<script>
    var player = videojs('video-player');

    var disablelogging = function(player, mediaPlayer) {
        mediaPlayer.getDebug().setLogToBrowserConsole(false);
    };
    videojs.Html5DashJS.hook('beforeinitialize', disablelogging);

    player.src({
        src: 'http://elo.salama.tv.funet.fi/vod/_definst_/mp4:fi/kava/elonet/2012/MV-266_Polyteekkarifilmi_470272_klippi.mp4/manifest.mpd',
        type: 'application/dash+xml'
    });
</script>

<!-- END of: finna - record/video.phtml -->
