<!-- START of: finna - record/video.phtml -->

<div class="video-popup">
  <div class="mfp-bg mfp-ready"></div>
  <div class="mfp-wrap mfp-gallery mfp-close-btn-in mfp-auto-cursor mfp-ready" tabindex="-1">
    <div class="mfp-container mfp-ajax-holder mfp-s-ready">
      <div class="mfp-content">
        <div class="imagepopup-holder marc" data-type="marc">
          <video id="my-video" class="video-js vjs-default-skin" controls style="width:100%; height: auto;">
            <source src="http://elo.salama.tv.funet.fi/vod/_definst_/mp4:fi/kava/elonet/2012/MV-266_Polyteekkarifilmi_470272_klippi.mp4/manifest.mpd" type="application/dash+xml">
          </video>
          <button type="button" class="mfp-close">×</button>
        </div>
      </div>
      <div class="mfp-preloader"></div>
    </div>
  </div>
</div>

<!-- END of: finna - record/video.phtml -->
