<?php
  $dateinputId = $this->dateinputId ?? '';
  $dateinputClass = $this->dateinputId ?? '';
  $dateinputLabel = $this->dateinputLabel ?? 'Testi2';
  $dateinputPlaceholder = $this->dateinputPlaceholder ?? '';
  $dateinputValue = $this->dateinputValue ?? '';
  $dateinputPicker = $this->dateinputPicker ?? '';
?>
<span class="finna-dateinput">
  <label for="<?=$dateinputId ?>"><?=$dateinputLabel ?></label>
  <input class="input <?=$dateinputClass ?>" id="<?=$dateinputId ?>" value="<?=$dateinputValue ?>" autocomplete="off">
  <span class="datepicker">
    <button class="datepicker-toggle">
      <?=$this->icon('calendar') ?>
      <span class="sr-only"><?=$this->transEsc('datepicker_select_date')?><span class="datepicker-date-selected"></span></span>
    </button>
    <dialog tabindex="-1" id="datepicker-<?=$dateinputId ?>" class="datepicker-popover">
      <calendar-date locale="<?=$this->layout()->userLang?>">
        <div role="button" slot="previous"><?=$this->transEsc('Prev')?></div><div role="button" slot="next"><?=$this->transEsc('Next')?></div>
        <calendar-month></calendar-month>
      </calendar-date>
      <button class="btn-datepicker-close"><?=$this->transEsc('close')?></button>
    </dialog>
  </span>
</span>
