<?php
  $dateinputId = $this->dateinputId ?? '';
  $dateinputName = $this->dateinputName ?? '';
  $dateinputClass = $this->dateinputId ?? '';
  $dateinputLabel = $this->dateinputLabel ?? '';
  $dateinputPlaceholder = $this->dateinputPlaceholder ?? '';
  $dateinputDateFormatHint = '<span class="sr-only">' . $this->transEsc('dateformat_hint_screenreader') . '</span>' . $this->dateTime()->getDisplayDateFormat();
  $dateinputValue = $this->dateinputValue ?? '';
  $dateinputPicker = $this->dateinputPicker ?? '';
  $dateinputRequired = $this->dateinputRequired ?? false;
  $dateinputSize = $this->dateinputSize ?? '10';
  $dateinputMaxlength = $this->dateinputMaxlength ?? '10';
  $dateinputAutocomplete = $this->dateinputAutocomplete ?? 'off';
?>
<div class="finna-dateinput <?php if($dateinputPicker === 'single'): ?>finna-datepicker<?php endif; ?>">
  <label for="<?=$dateinputId ?>"><?=$dateinputLabel ?> <span class="dateformat-hint">(<?=$dateinputDateFormatHint ?>)</span></label>
  <?php if($dateinputPicker === 'single'): ?>
    <div class="input-group">
      <input type="text" class="input-field form-control <?=$dateinputClass ?>" id="<?=$dateinputId ?>" name="<?=$dateinputName ?>" value="<?=$dateinputValue ?>" placeholder="<?=$dateinputPlaceholder ?>" size="<?=$dateinputSize ?>" maxlength="<?=$dateinputMaxlength ?>" <?php if ($dateinputRequired): ?>required<?php endif; ?> autocomplete="<?=$dateinputAutocomplete ?>">
        <div class="input-group-btn">
          <button type="button" class="btn btn-default datepicker-toggle">
            <?=$this->icon('calendar') ?>
            <span class="sr-only"><?=$this->transEsc('datepicker_select_date')?> <span class="datepicker-date-selected"></span></span>
          </button>
        </div>
    </div>
    <dialog tabindex="-1" id="datepicker-<?=$dateinputId ?>" class="datepicker-dialog">
      <calendar-date locale="<?=$this->layout()->userLang?>">
        <div class="btn-datepicker-prev" role="button" slot="previous"><?=$this->icon('datepicker-prev') ?><span class="sr-only"><?=$this->transEsc('Prev')?></span></div><div class="btn-datepicker-next" role="button" slot="next"><?=$this->icon('datepicker-next') ?><span class="sr-only"><?=$this->transEsc('Next')?></span></div>
        <calendar-month></calendar-month>
      </calendar-date>
      <button type="button" class="btn btn-primary btn-xs btn-datepicker-close"><?=$this->transEsc('close')?></button>
    </dialog>
  <?php else: ?>
    <input type="text" class="input-field form-control <?=$dateinputClass ?>" id="<?=$dateinputId ?>" name="<?=$dateinputName ?>" value="<?=$dateinputValue ?>" placeholder="<?=$dateinputPlaceholder ?>" size="<?=$dateinputSize ?>" maxlength="<?=$dateinputMaxlength ?>" <?php if ($dateinputRequired): ?>required<?php endif; ?> autocomplete="<?=$dateinputAutocomplete ?>">
  <?php endif; ?>
</div>
