<?php
  $url = $this->url['url'] ?? $this->url;
  $embeddedVideo = $this->embed === 'data-embed-iframe' ?: false;
  $videoIndex = $this->index;
  $active = $this->active ?? false;
  $description = $this->description ?? $this->translate('format_Video');
  $videoSources = $this->videoSources ?? [];
  $videoIndex = $this->index ?? 1;
  $buttonAttributes = [
    'class' => $this->class ?? 'video-link-container',
    'aria-label' => $this->ariaLabel ?? $this->translate('Link to video') . ' ' . $description,
    'title' => $url,
    'data-vc-url' => $url,
    'data-vc-index' => $index,
    'data-vc-invocation' => $this->_invocation,
    'data-vc-inline' => $this->inline ?? false,
    'data-vc-embed' => $embeddedVideo,
    'data-vc-consent' => $this->consent ?? 'recordvideo',
    'aria-haspopup' => true,
  ];
  $buttonAttributes['class'] .= ' ' . $this->_componentClass;
  if ($active) {
    $buttonAttributes['class'] .= ' active-video';
  }
  // Generate unique selector for the button
  $jsSelector = '.' . str_replace(' ', '.', $buttonAttributes['class']) . "[data-vc-invocation=\"$this->_invocation\"]";
?>
<button <?=$this->htmlAttributes($buttonAttributes);?> <?php if ($videoSources): ?>data-video-sources="<?=htmlspecialchars(json_encode($videoSources), ENT_QUOTES, 'UTF-8');?>"<?php endif;?>>
  <?=$this->icon('video-play', 'video-play-icon');?>
  <span class="video-desc"><?=$this->escapeHtml($this->truncate(ucfirst($description), 30))?></span>
</button>
<?php
$script = <<<JS
    finna.scriptLoader.load(
      {'finna-video-player': 'finna-video-player.js'},
      () => {
        finna.videoPlayer.initVideoButton('{$jsSelector}');
      }
    );
    JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script);?>
