<?php
    $infoTypeClass = match ($this->type ?? '') {
        'info' => 'alert alert-info',
        'danger' => 'alert alert-danger',
        'success' => 'alert alert-success',
        default => 'alert alert-info',
    };
    $divAttrs = [
        'class' => trim(($this->class ?? '') . "$infoTypeClass $this->_componentClass margin-top"),
    ];
    if ($this->bold ?? false) {
        $divAttrs['class'] .= ' bold';
    }
    $content = $this->content ?? '';
?>
<div<?=$this->htmlAttributes($divAttrs)?>>
    <?=$this->escapeHtml($content);?>
</div>