<?php
  /**
   * Container for editable components. Provides a consistent interface for activating
   * edit mode and showing a busy state.
   *
   * @param ?iterable attributes          Additional attributes
   * @param ?iterable containerAttributes Additional attributes for the container
   * @param ?string   editable            Rendered HTML of the editable component
   * @param ?string   editLabel           Label for the edit button. Defaults to
   *                                      'Edit'.
   * @param ?string   name                Name of the hidden input that will hold the
   *                                      edited value.
   *
   * Supported variations using CSS classes:
   * - finna-editable-open
   *     Editable component has been activated using edit button
   * - finna-editable-busy
   *     Editable component is busy, e.g. loading or saving
   */
?>
<div<?= $this->htmlAttributes($attributes ?? [])->add('class', ['finna-editable', 'clearfix']) ?>>
  <?= $this->component('finna-btn', [
      'ariaLabel' => $editLabel ?? $this->transEsc('Edit'),
      'attributes' => ['class' => 'finna-editable-btn'],
      'icon' => 'ui-edit',
      'iconClass' => 'finna-editable-btn-icon',
    ]); ?>
  <?php if ($inputName = $this->name ?? ''): ?>
    <input class="js-editable-hidden-input" type="hidden" name="<?= $this->escapeHtmlAttr($name) ?>" value="<?= $this->escapeHtmlAttr($editable ?? '') ?>">
  <?php endif; ?>
  <?=$this->icon('spinner', 'finna-editable-spinner')?>
  <div<?= $this->htmlAttributes($containerAttributes ?? [])->add('class', 'finna-editable-container') ?>>
    <?= $editable ?? '' ?>
  </div>
</div>
