<?php
  /**
   * Component for opening or displaying proper video content.
   *
   * @param string url Url for the video
   * @param int index Video index, used to identify i.e video warnings
   * @param array videoSources Sources for the video if applicable
   * @param string ariaLabel Translated aria label. Default is 'Link to video $description'
   * @param string consent Consent category to be accepted.
   * @param bool embed Is the video an iframe embed?
   * @param string description Text description inside the button. Default is format_Video translated.
   */

  $inlineVideoPlayer = $this->inline ?? false;
  $index = $this->index ?? 0;
  $description = $this->description ?? $this->translate('format_Video');
  $videoSources = $this->videoSources ?? [];
  $consent = $this->consent ?? 'recordvideo';
  $embeddedVideo = $this->embed ?? false;
  $buttonAttributes = [
    'class' => trim(($this->class ?? 'video-link-container') . " vc-invocation-$this->_invocation $this->_componentClass"),
    'aria-label' => $this->ariaLabel ?? $this->translate('Link to video') . ' ' . $description,
    'data-url' => $this->url ?? '',
    'data-index' => $index,
    'data-inline' => $inlineVideoPlayer,
    'data-embed' => $embeddedVideo,
    'data-consent' => $consent,
    'data-consent-title' => $this->translate($this->cookieConsent()->getCategoryTitleForService($consent)),
    'aria-haspopup' => true,
  ];

  if ($index === 0 && $inlineVideoPlayer) {
    $buttonAttributes['class'] .= ' active-video';
  }
  // Generate unique selector for the button
  $jsSelector = '.' . str_replace(' ', '.', $buttonAttributes['class']);
?>
<button <?=$this->htmlAttributes($buttonAttributes);?> <?php if ($videoSources): ?>data-video-sources="<?=htmlspecialchars(json_encode($videoSources), ENT_QUOTES, 'UTF-8');?>"<?php endif;?>>
  <?=$this->icon('video-play', 'video-play-icon');?>
  <span class="video-desc"><?=$this->escapeHtml($this->truncate(ucfirst($description), 30))?></span>
</button>
<?php
$script = <<<JS
    finna.scriptLoader.load(
      {'finna-video-player': 'finna-video-player.js'},
      () => {
        const embedded = '{$embeddedVideo}';
        if (embedded) {
          finna.videoPlayer.initIFrameButton('{$jsSelector}');
        } else {
          finna.videoPlayer.initVideoButton('{$jsSelector}');
        }
      }
    );
    JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script);?>
