<?php
  /**
   * Addition template component, renders addition content from custom theme if template exists in user language 
   *
   * @param string       class         CSS class used with content
   * @param string       template      Template to be rendered
   * @param string       templatePath  Path to the template in custom theme
   */
  $class = $this->class ?? '';
  $template = $this->template ?? '';
  $templatePath = 'content/Additions/'
?>
<?php if ($template = $this->content()->findTemplateForLng($templatePath . $template)): ?>
  <div class="<?=$class?>"><?=$this->render($template)?></div>
<?php endif; ?>
