<?php
    /**
     * Component to display an information box with text.
     *
     * @param string type Type of the information box to display. Default is info.
     * @param string class Extra classes to add for the information box. Default is alert alert-info vc-finna-information-box margin-top.
     * @param string content Translated content without escaping. Escaping is handled inside this component.
     * @param bool   bold If the text should be bolded. Default is false.
     */
    $infoTypeClass = match ($this->type ?? '') {
        'info' => 'alert alert-info',
        'danger' => 'alert alert-danger',
        'success' => 'alert alert-success',
        default => 'alert alert-info',
    };
    $divAttrs = [
        'class' => trim(($this->class ?? '') . "$infoTypeClass $this->_componentClass margin-top"),
    ];
    if ($this->bold ?? false) {
        $divAttrs['class'] .= ' bold';
    }
    $content = $this->content ?? '';
?>
<div<?=$this->htmlAttributes($divAttrs)?>>
    <?=$this->escapeHtml($content);?>
</div>
