<!-- START of: finna - search/modals.phtml -->
<!-- BASIC MODAL IN CASE WE NEED ONE -->
<div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="<?= $this->transEsc('close') ?>"></button>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

<!-- IMAGEPOPUP MODAL -->
<div id="imagepopup-modal" hidden>
  <div class="imagepopup-holder" aria-hidden="true">
    <div class="imagepopup-container">
      <div class="popup-canvas paginator-canvas">
        <button class="next-image left" title="<?= $this->transEsc('previous_image'); ?>" type="button"><i class="fa fa-chevron-left"></i><span class="sr-only"><?= $this->transEsc('previous_image'); ?></span></button>
        <div class="popup-nonzoom non-zoomable">
          <div class="iconlabel"></div>
          <img src="<?= $this->imageSrc()->getDataPixel() ?>" alt="" />
        </div>
        <div class="leaflet-map-image image-wrapper">
          <img src="<?=$this->imageSrc()->getDataPixel()?>" alt="" />
          <div class="imagepopup-zoom-container">
            <button class="zoom-in zoom-button" title="<?= $this->transEsc('zoom_in'); ?>"><i class="fa fa-zoom-in" aria-hidden="true"></i><span class="sr-only"><?= $this->transEsc('zoom_in'); ?></span></button>
            <button class="zoom-out zoom-button" title="<?= $this->transEsc('zoom_out'); ?>"><i class="fa fa-zoom-out" aria-hidden="true"></i><span class="sr-only"><?= $this->transEsc('zoom_out'); ?></span></button>
            <button class="zoom-reset zoom-button" title="<?= $this->transEsc('zoom_center'); ?>"><i class="fa fa-zoom-100" aria-hidden="true"></i><span class="sr-only"><?= $this->transEsc('zoom_center'); ?></span></button>
          </div>
          <div class="leaflet-image-loading">
          </div>
        </div>
        <div class="popup-video video-popup"></div>
        <button class="next-image right" title="<?= $this->transEsc('next_image'); ?>" type="button"><i class="fa fa-chevron-right"></i><span class="sr-only"><?= $this->transEsc('next_image'); ?></span></button>
      </div>
      <div class="finna-image-pagination">
      </div>
    </div>
    <div class="image-information-holder">
      <div class="collapse-content-holder">
      </div>
      <div class="record-informations">
        <div class="record-index">
          <span class="total"></span>
        </div>
        <div class="paginator-info">
          <span class="image-index"></span>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- 3D model modal -->
<div id="model-modal" hidden>
  <div class="model-wrapper">
    <div class="model-canvas-wrapper">
      <div class="viewer-state-wrapper">
      </div>
      <div class="viewer-options">
        <div class="viewer-controls">
          <button class="viewer-btn model-fullscreen collapsed" type="button"><i class="fa fa-fullscreen"></i> <span class="sr-only"><?=$this->transEsc('Fullscreen mode')?></span></button>
          <button class="viewer-btn model-settings-btn collapsed" data-toggle="collapse" data-target="#model-settings" type="button"><i class="fa fa-star"></i> <span class="sr-only">Asetukset</span></button>
          <button class="viewer-btn model-statistics collapsed" data-toggle="collapse" data-target="#model-stats" type="button"><i class="fa fa-info-circle-hollow"></i> <span class="sr-only"><?=$this->transEsc('Information of model')?></span></button>
          <button class="viewer-btn model-help-btn collapsed" data-toggle="collapse" data-target="#model-help" type="button" ><i class="fa fa-question-circle-o"></i> <span class="sr-only"><?=$this->transEsc('model_help')?></span></button>
        </div>
        <div class="viewer-statistics">
          <div>
            <div class="model-stats collapse">
              <table class="table table-finna-record">
                  <tbody class="statistics-table">
                  </tbody>
              </table>
            </div>
            <div class="model-help collapse">
            </div>
            <div class="model-settings collapse">
              <div class="camera-holder">
                <div class="model-setting camera template hidden">
                  <form class="camera-form" name="templateform">
                  </form>
                </div>
              </div>
              <div class="renderer-holder">
                <div class="model-setting renderer template hidden">
                  <form class="renderer-form" name="templateform">
                  </form>
                </div>
              </div>
              <div class="material-holder">
                <div class="model-setting material template hidden">
                  <form class="material-form" name="templateform">
                  </form>
                </div>
              </div>
              <div class="light-holder">
                <div class="model-setting light template hidden">
                  <form class="light-form" name="templateform">
                    <button class="save-light" type="button" value="save-light">Save</button>
                    <button class="delete-light hidden" type="button" value="delete-light">Delete</button>
                  </form>
                </div>
                <button class="add-light template" type="button" value="add-light">Add light</button>
              </div>
              <button class="export-settings template" type="button" value="export-settings">Export</button>
              <button class="import-settings template" type="button" value="import-settings">Import</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END of: finna - search/modals.phtml -->
