<!-- START of: finna - search/searchTabs.phtml -->
<?php
  $isManyTabs = (count($searchTabs) > 2);
  $module = $this->layout()->templateDir;
  $hasSelectedTab = false;
?>
<?php if (!$isManyTabs): ?>
  <div class="tabs-table">
<?php endif; ?>
<?php if (!empty($searchTabs)): ?>
  <div role="navigation" aria-label="<?=$this->transEscAttr('Search Tabs')?>">
    <?php
      $tooltipElement = $this->htmlElement()->addAttributeTemplate('tooltip-element', [
        'class' => 'tooltip',
        'data-bs-toggle' => 'tooltip',
        'data-bs-trigger' => 'click',
        'data-bs-html' => 'true',
        'data-bs-placement' => 'bottom',
      ]);
    ?>
    <ul class="nav nav-tabs <?=$isManyTabs ? ' many-tabs hidden-xs' : '';?>">
      <?php foreach ($searchTabs as $tab): ?>
        <?php if ($tab['selected']) {
          $this->layout()->currentTabId = $tab['id'];
          $hasSelectedTab = true;
        } ?>
        <li class="<?=$tab['selected'] ? 'active' : 'hidden-print'?>">
          <a <?=$tab['selected'] ? 'aria-current="true"' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
            <?=$this->transEsc($tab['label']); ?>
            <?php $tooltipKeyHtml = 'tooltip_' . $tab['label'] . '_html'; ?>
            <?php if ($this->layout()->templateName !== 'advanced' && !$this->translationEmpty($tooltipKeyHtml)): ?>
              <?php
                $tooltip = [
                  'aria-label' => $this->translate('Help') . ' - ' . $this->translate($tab['label']),
                  'data-bs-title' => $this->translate($tooltipKeyHtml),
                  'class' => 'tooltip-' . $tab['label'],
                  'data-bs-custom-class' => 'tooltip-' . $tab['label'],
                ];
              ?>
              <button <?= $this->htmlElement()->getAttributes($tooltip, 'tooltip-element'); ?>>
                <?=$this->icon('help') ?>
              </button>
            <?php endif; ?>
          </a>
        </li>
      <?php endforeach; ?>
      <?php if (!$hasSelectedTab && !$this->translationEmpty('temporary_search_tab_title')): ?>
        <li class="active">
          <a><?=$this->transEsc('temporary_search_tab_title')?></a>
        </li>
      <?php endif; ?>
    </ul>
    <?php if (!$this->translationEmpty("search_tab_tip_{$module}_html")) :?>
      <div class="search-tab-tip">
        <?=$this->translate("search_tab_tip_{$module}_html");?>
      </div>
    <?php endif; ?>
    <div class="mobile-main-tabs <?=count($searchTabs) > 2 ? 'visible-xs' : 'hidden';?>">
      <div class="dropdown visible-xs">
        <?php foreach ($searchTabs as $tab): ?>
          <?php if ($tab['selected']): ?>
            <div class="dropdown-toggle clearfix" data-toggle="dropdown">
              <div class="tab-title"><?=$this->transEsc($tab['label']); ?></div>
              <div class="more"><?=$this->transEsc('More');?><?=$this->icon('menu-open') ?> </div>
            </div>
          <?php endif; ?>
        <?php endforeach; ?>
        <ul class="dropdown-menu" role="menu">
          <?php foreach ($searchTabs as $tab): ?>
            <?php if ($tab['selected']) {
              $this->layout()->currentTabId = $tab['id'];
            } ?>
            <li class="<?=$tab['selected'] ? 'active' : ''?>">
              <a role="menuitem" <?=$tab['selected'] ? 'aria-current="true"' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
            </li>
          <?php endforeach; ?>
        </ul>
      </div>
    </div>
  </div>
<?php endif; ?>
<?php if (!$isManyTabs): ?>
  </div>
<?php endif; ?>
<!-- END of: finna - search/searchTabs.phtml -->
