<!-- START of: finna - search/searchTabs.phtml -->
<?php
  $isManyTabs = (count($searchTabs) > 2);
  $module = $this->layout()->templateDir;
  $hasSelectedTab = false;
?>
<?php if (!$isManyTabs): ?>
  <div class="tabs-table">
<?php endif; ?>
<?php if (!empty($searchTabs)): ?>
  <div role="navigation" aria-label="<?=$this->transEscAttr('Search Tabs')?>">
    <?php
      $popoverElement = $this->htmlElement()->addAttributeTemplate('popover-element', [
        'class' => 'popover-btn',
        'data-bs-toggle' => 'popover',
        'data-bs-trigger' => 'click',
        'data-bs-html' => 'true',
        'data-bs-placement' => 'bottom',
      ]);
    ?>
    <ul class="nav nav-tabs <?=$isManyTabs ? ' many-tabs hidden-xs' : '';?>">
      <?php foreach ($searchTabs as $tab): ?>
        <?php if ($tab['selected']) {
          $this->layout()->currentTabId = $tab['id'];
          $hasSelectedTab = true;
        }
        $popoverKeyHtml = 'tooltip_' . $tab['label'] . '_html';
        if ($this->layout()->templateName !== 'advanced' && !$this->translationEmpty($popoverKeyHtml)) {
          // Note: tooltip- class is kept for back-compatibility
          $popover = [
            'aria-label' => $this->translate('Help') . ' - ' . $this->translate($tab['label']),
            'data-bs-content' => $this->translate($popoverKeyHtml),
            'class' => 'tooltip-' . $tab['label'],
            'data-bs-custom-class' => 'tooltip-' . $tab['label'],
          ];
        } else {
          $popover = '';
        }
        ?>
        <li class="nav-item <?=$tab['selected'] ? 'active' : 'hidden-print'?><?=$popover ? ' with-popover' : ''?>">
          <a class="nav-link<?=$tab['selected'] ? ' active' : ''?>" <?=$tab['selected'] ? 'aria-current="true"' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
            <?=$this->transEsc($tab['label']); ?>
          </a>
          <?php if ($popover): ?>
            <button <?= $this->htmlElement()->getAttributes($popover, 'popover-element'); ?>>
              <?=$this->icon('help') ?>
            </button>
          <?php endif; ?>
        </li>
      <?php endforeach; ?>
      <?php if (!$hasSelectedTab && !$this->translationEmpty('temporary_search_tab_title')): ?>
        <li class="nav-item active">
          <a><?=$this->transEsc('temporary_search_tab_title')?></a>
        </li>
      <?php endif; ?>
    </ul>
    <?php if (!$this->translationEmpty("search_tab_tip_{$module}_html")) :?>
      <div class="search-tab-tip">
        <?=$this->translate("search_tab_tip_{$module}_html");?>
      </div>
    <?php endif; ?>
    <div class="mobile-main-tabs <?=count($searchTabs) > 2 ? 'visible-xs' : 'hidden';?>">
      <div class="dropdown visible-xs">
        <?php foreach ($searchTabs as $tab): ?>
          <?php if ($tab['selected']): ?>
            <div class="dropdown-toggle clearfix" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="tab-title"><?=$this->transEsc($tab['label']); ?></div>
              <div class="more"><?=$this->transEsc('More');?><?=$this->icon('menu-open') ?> </div>
            </div>
          <?php endif; ?>
        <?php endforeach; ?>
        <ul class="dropdown-menu" role="menu">
          <?php foreach ($searchTabs as $tab): ?>
            <?php if ($tab['selected']) {
              $this->layout()->currentTabId = $tab['id'];
            } ?>
            <li class="<?=$tab['selected'] ? 'active' : ''?>">
              <a role="menuitem" <?=$tab['selected'] ? 'aria-current="true"' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
            </li>
          <?php endforeach; ?>
        </ul>
      </div>
    </div>
  </div>
<?php endif; ?>
<?php if (!$isManyTabs): ?>
  </div>
<?php endif; ?>
<!-- END of: finna - search/searchTabs.phtml -->
