<!-- START of: finna - search/searchTabs.phtml -->
<?php
  $module = $this->layout()->templateDir;
  $hasSelectedTab = false;
  $selectedTabLabel = 'default_empty_label';
?>
<?php if (!empty($searchTabs)): ?>
    <?php if (!$this->translationEmpty("search_tab_tip_{$selectedTabLabel}_html")) :?>
    <div class="search-tab-tip">
      <?=$this->translate("search_tab_tip_{$selectedTabLabel}_html");?>
    </div>
  <?php elseif (!$this->translationEmpty("search_tab_tip_{$module}_html")) :?>
    <div class="search-tab-tip">
      <?=$this->translate("search_tab_tip_{$module}_html");?>
    </div>
  <?php endif; ?>
  <div role="navigation" class="nav-scrollable" aria-label="<?=$this->transEscAttr('Search Tabs')?>">
    <button class="arrow-btn scroll-prev-btn js-scroll-prev hidden" aria-label="<?=$this->transEscAttr('Scroll backward') ?>">
      <?=$this->icon('tabs-prev')?>
    </button>
    <button class="arrow-btn scroll-next-btn js-scroll-next hidden" aria-label="<?=$this->transEscAttr('Scroll forward') ?>">
      <?=$this->icon('tabs-next')?>
    </button>
    <ul class="nav nav-tabs link-tabs">
      <?php foreach ($searchTabs as $tab): ?>
        <?php if ($tab['selected']) {
          $this->layout()->currentTabId = $tab['id'];
          $hasSelectedTab = true;
          $selectedTabLabel = $tab['label'];
        }
        $toggletipKeyHtml = 'tooltip_' . $tab['label'] . '_html';
        if ($this->layout()->templateName !== 'advanced' && !$this->translationEmpty($toggletipKeyHtml)) {
          $toggletip = [
            'icon' => 'help',
            'ariaLabel' => $this->translate('Help') . ' - ' . $this->translate($tab['label']),
            'contentHtml' => $this->translate($toggletipKeyHtml),
            'class' => 'tooltip-' . $tab['label'], // for back-compatibility
          ];
        } else {
          $toggletip = '';
        }
        ?>
        <li class="nav-item <?=$tab['selected'] ? 'active' : 'hidden-print'?><?=$toggletip ? ' with-tooltip' : ''?>">
          <a class="nav-link<?=$tab['selected'] ? ' active' : ''?>" <?=$tab['selected'] ? 'aria-current="true"' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
            <?=$this->transEsc($tab['label']); ?>
          </a>
          <?php if ($toggletip): ?>
            <?=$this->component('finna-toggletip', $toggletip)?>
          <?php endif; ?>
        </li>
      <?php endforeach; ?>
      <?php if (!$hasSelectedTab && !$this->translationEmpty('temporary_search_tab_title')): ?>
        <li class="nav-item active">
          <a class="nav-link active"><?=$this->transEsc('temporary_search_tab_title')?></a>
        </li>
      <?php endif; ?>
    </ul>
  </div>
<?php endif; ?>
<!-- END of: finna - search/searchTabs.phtml -->
