<!-- START of: finna - search/street-search-header.phtml -->
<?
  $this->headLink()->appendStylesheet('vendor/leaflet.css');
  $this->headLink()->appendStylesheet('vendor/leaflet.draw.css');
  $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/leaflet.js');
  $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/leaflet.draw.js');
  $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'finna-street-map.js');
  echo $this->inlineScript();
  //$this->headScript()->appendFile('finna-street-map.js');
?>
<div class="row">
  <div class="col-md-4">
    <div class="update-location-button text-left">
      <a class="btn btn-primary" href="<?=$this->url('search-streetsearch')?>?go=1"><i class="fa fa-crosshairs"></i> <span><?=$this->transEsc('street_search_refresh')?></span></a>
    </div>
  </div>
  <div class="col-md-4">
    <div class="street-search-header-message">
      <h4><?=$this->transEsc('street_under_development')?></h4>
      <p><?=$this->transEsc('street_search_help')?></p>
    </div>
  </div>
  <div class="col-md-4">
    <div class="street-search-feedback text-right">
      <a class="btn btn-primary" href="<?=$this->url('feedback-home', [], ['query' => ['comments' => $this->transEsc('street_search_feedback'), 'url' => $this->serverUrl(true)]])?>"><?=$this->transEsc('Give Feedback')?></a>
    </div>
  </div>
  <div class="map" style="height: 300px; width: 300px;"></div>
</div>
<?
  $geoFilters = $this->params->getGeographicFilters($this->params->getFilterList());
?>
<script type="text/javascript">
  $(document).ready(function() {
    var options = {
      items: []
    };
    <? foreach ($geoFilters as $filter): ?>
      <? foreach (preg_split('/\s+OR\s+/', $filter) as $item): ?>
        options.items.push('<?=$this->escapeJs($item) ?>');
      <? endforeach; ?>
    <? endforeach; ?>
    finna.StreetMap.initMap(options);
  });
</script>
<!-- END of: finna - search/street-search-header.phtml -->
