<!-- START of: finna - search/streetsearch.phtml -->
<?
$this->headLink()->appendStylesheet('vendor/leaflet.css');
$this->headLink()->appendStylesheet('vendor/leaflet.draw.css');
$this->headScript()->appendFile('vendor/leaflet.js');
$this->headScript()->appendFile('vendor/leaflet.draw.js');
$this->headScript()->appendFile('finna-map-facet.js');
?>
<?=$this->headLink()?>
<?
$this->headTitle($this->translate('street_search'));
$this->content()->setHeading = true;

$this->layout()->searchbox = $this->streetSearch();
?>
<div class="street-search">
  <div class="street-search-action-links hidden">
    <a href="<?=$this->url('search-streetsearch')?>?go=1"><i class="fa fa-map-marker"></i><?=$this->translate("use_my_location");?></a>
    <a class="select-from-map" href="<?=$this->url('search-mapfacet')?>" data-lightbox><i class="fa fa-map-o"></i><?=$this->translate("select_area_from_map");?></a>
  </div>
  <div>
    <ul id="street-search-output"></ul>
    <div class="street-search-introduction">
        <?=$this->translate('street_search_introduction_html')?>
    </div>
    <p class="street-search-info-box">
      <?=$this->translate('street_search_info_html')?>
    </p>
  </div>
</div>
<!-- END of: finna - search/streetsearch.phtml -->
