<!-- START of: finna - RecordTab/authorityrecords.phtml -->
<?php
  $script = <<<JS
$(document).ready(function() {
  finna.layout.initCondensedList();
});
JS;
  echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');

$results = $this->tab->loadRecords($this->driver);
$resultCnt = $results->getResultTotal();
$i = 0;
$moreUrl = $this->record($this->driver)->getLink('author-id', '', ['authId' => $this->driver->getUniqueID(), 'filter' => $this->tab->getSearchQuery(), 'linkType' => 'author-id', 'searchAction' => 'search-results']);
?>
<div class="authority-records">
  <div class="pagination-container">
    <span class="showing"><?=$this->translate(
      'showing_results_html', [
        '%%start%%' => 1,
        '%%end%%' => count($results->getResults())
      ]
    ) . "</span> / <span class=\"search-link\"><a href=\"{$moreUrl}\">" . $this->translate('authority_records_search_link', ['%%count%%' => $this->localizedNumber($results->getResultTotal())]) . '</a></span>'
    ?>
  </div>
  <?php foreach ($results->getResults() as $current): ?>
  <div id="result<?=$i++ ?>" class="result condensed-list-view clearfix<?=$current->supportsAjaxStatus()?' ajaxItem':''?>">
    <span class="sr-only"><?=$this->transEsc('Search Result');?> <?=$i ?></span>
    <?=$this->record($current)->getSearchResult('condensed', ['authorId' => $this->driver->getUniqueId()])?>
  </div>
  <?php endforeach ?>
</div>
<!-- END of: finna - RecordTab/authorityrecords.phtml -->
