<?php // Do not add start and end comments ?>
<?php foreach ($orgInfo['accessibilityInfo'] ?? [] as $i => $accessibilityGroup): ?>
  <h5 class="accessibility-group-heading"><?=$this->escapeHtml($accessibilityGroup['heading'])?></h5>
  <div class="accessibility-group-statements"<?php if (0 === $i): ?> data-track-content data-content-name="Location Accessibility" data-content-piece="<?=$this->escapeHtmlAttr($id . '/' . $orgInfo['name'])?>"<?php endif; ?>>
    <?php foreach ($accessibilityGroup['statements'] as $statement): ?>
      <p><?=$this->escapeHtml($statement)?>
    <?php endforeach; ?>
  </div>
<?php endforeach; ?>
