<!-- START of: finna - Helpers/contenttabs.phtml -->
<finna-content-tabs
  active="<?=$this->escapeHtmlAttr($this->active)?>"
  title="<?=$this->escapeHtmlAttr($this->translate($this->title))?>"
  identifier="<?=$this->escapeHtmlAttr($this->id)?>"
  tabs="<?=htmlspecialchars(json_encode($this->contents ?? []), ENT_QUOTES, 'UTF-8');?>"
>
  <?php foreach ($this->contents as $key => $value): ?>
    <?= $this->partial("content/{$this->escapeHtml($value)}") ?>
  <?php endforeach; ?>
</finna-content-tabs>
<!-- END of: finna - Helpers/contenttabs.phtml -->
