<!-- START of: finna - Helpers/contenttabs.phtml -->
<finna-content-tab
  active="<?=$this->escapeHtmlAttr($this->active)?>"
  title="<?=$this->escapeHtmlAttr($this->translate($this->title))?>"
  identifier="<?=$this->escapeHtmlAttr($this->id)?>"
  tabs="<?=htmlspecialchars(json_encode($this->contents ?? []), ENT_QUOTES, 'UTF-8');?>"
>
  <?php foreach ($this->contents as $key => $value): ?>
    <?= $this->partial("content/$value") ?>
  <?php endforeach; ?>
</finna-content-tab>

<?php
  $this->headScript()->appendFile("finna-content-tab.js");
  $js = <<<JS
document.addEventListener('DOMContentLoaded', () => {
  finna.contentTabs.init();
}, false);
JS;
$this->headScript()->appendScript($js);
?>
<!-- END of: finna - Helpers/contenttabs.phtml -->
