<!-- START of: finna - Helpers/cookie-consent.phtml -->
<?php
  // Render the new cookie consent initialization script if necessary:
 if (!empty($this->consentDialogConfig)) {
  $this->headScript()->appendFile('vendor/cookieconsent.umd.js');
  $this->headScript()->appendFile('cookie.js');

  // Quick fix for null domain:
  $consentDialogConfig = $this->consentDialogConfig;
  if (array_key_exists('domain', $consentDialogConfig['cookie']) && $consentDialogConfig['cookie']['domain'] === null) {
    unset($consentDialogConfig['cookie']['domain']);
  }
  $configJson = json_encode(
      [
          'consentDialog' => $consentDialogConfig,
          'controlledVuFindServices' => $this->controlledVuFindServices,
      ]
  );
  $this->headScript()->appendScript("window.addEventListener('load', function() { VuFind.cookie.setupConsent($configJson); });");
  return;
}
?>
<div class="container-fluid cookie-consent">
  <div class="cookie-consent-text">
    <?=$this->translate('cookie_consent_html', ['%%link%%' => $this->escapeHtmlAttr($this->url('content-page', ['page' => 'privacy']) . '#cookies')])?>
  </div>
  <div class="nav navbar-nav nav-absolute cookie-consent-button">
    <button class="btn btn-primary cookie-consent-dismiss" aria-label="<?=$this->transEsc('Accept cookies')?>"><?=$this->transEsc('OK')?></button>
  </div>
</div>
<!-- END of: finna - Helpers/cookie-consent.phtml -->
