<!-- START of: finna - Helpers/copyright-field-value.phtml -->
<?php if (isset($data['copyright'])): ?>
  <span class="rights-icons">
    <?php $copyright = $data['mappedCopyright'] ?? $data['copyright']; ?>
    <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $copyright]);?>
    <span class="rights-text"><?= $this->escapeHtml($copyright); ?></span>
  </span>
  <?php if (isset($data['link'])): ?>
    <span class="rights-link">
      <a href="<?= $this->escapeHtmlAttr($data['link']); ?>" target="_blank"><?= $this->transEsc('usage_meaning')?></a>
    </span>
  <?php endif; ?>
<?php endif; ?>
<!-- END of: finna - Helpers/copyright-field-value.phtml -->
