<!-- START of: finna - Helpers/feedtabs.phtml -->
<finna-feed-tab
  active="<?=$this->escapeHtmlAttr($this->active)?>"
  title="<?=$this->escapeHtmlAttr($this->translate($this->title))?>"
  identifier="<?=$this->escapeHtmlAttr($this->id)?>"
  tabs="<?=htmlspecialchars(json_encode($this->feedIds ?? []), ENT_QUOTES, 'UTF-8');?>"
>
</finna-feed-tab>

<?php
  $this->headScript()->appendFile("finna-feed-tabs.js");
  $js = <<<JS
document.addEventListener('DOMContentLoaded', () => {
  finna.feedTabs.init();
}, false);
JS;
$this->headScript()->appendScript($js);
?>
<!-- END of: finna - Helpers/feedtabs.phtml -->
