<!-- START of: finna - Helpers/feedtabs.phtml -->
<div class="feed-tabs" id="feed-tabs-<?=$this->escapeHtmlAttr($this->id)?>">
  <?php if (count($this->feedIds) > 3): ?>
  <div class="tabs-responsive">
  <?php endif; ?>
    <ul class="feedTabs nav nav-tabs visible-md visible-lg" role="tablist">
      <? $tabNames = []; ?>
      <?php foreach ($this->feedIds as $desc => $feed): ?>
        <?php // add current tab to breadcrumbs if applicable:
          $tabName = preg_replace("/\W/", "-", strtolower($feed));
          $tabNames[] = $tabName;
          $tabClasses = [ 'nav-item', 'feed-tab', $tabName ];
          if (0 === strcasecmp($this->active, $feed)) {
              $tabClasses[] = 'active initial-active';
          }
          $tabId = $this->id . '-' . $feed;
        ?>
      <li class="<?=$this->escapeHtmlAttr(implode(' ', $tabClasses))?>" data-tab="<?=$this->escapeHtmlAttr($tabName)?>">
          <a class="<?=$this->escapeHtmlAttr(strtolower($feed)) ?>"
             aria-label="<?=$this->escapeHtmlAttr($this->transEsc($desc))?>"
             id="<?=$this->escapeHtmlAttr($tabId)?>-tab"
             href="#"
             role="tab"
             data-toggle="tab"
             data-tab="<?=$this->escapeHtmlAttr($feed)?>"
             araia-controls="<?=$this->escapeHtmlAttr($tabId)?>"><?= $this->transEsc($desc) ?></a>
      </li>
      <?php endforeach; ?>
    </ul>
  <?php if (count($this->feedIds) > 3): ?>
  </div>
  <?php endif; ?>

  <div class="feed-accordions">
    <?php $i = 0; foreach ($this->feedIds as $desc => $feed): ?>
      <?php
        $classes = ['accordion', 'accordion-' . $tabNames[$i++]];
        if (0 === strcasecmp($this->active, $feed)) {
          $classes[] = 'active initial-active';
        }
        $tabId = $this->id . '-' . $feed;
      ?>
      <div class="<?=$this->escapeHtmlAttr(implode(' ', $classes))?>">
        <div class="accordion-toggle" data-tab="<?=$this->escapeHtmlAttr($feed)?>">
          <a data-tab="<?=$this->escapeHtmlAttr($feed)?>"
             class="accordion-title"
             href="#"
          >
            <span class="title"><?=$this->transEsc($desc)?></span>
            <i class="icon"></i>
          </a>
        </div>
      </div>
    <?php endforeach; ?>
  </div>

  <div class="tab-content" id="tab-content-<?=$this->escapeHtmlAttr($this->id)?>">
    <div class="feed-container" data-init="0"></div>
  </div>
</div>
<?php
$this->headScript()->appendFile("finna-feed-tabs.js");
// Set up validation; we do this inline instead of in the header for lightbox compatibility:
$js = <<<JS
$(document).ready(function(){
  finna.feedTabs.init("feed-tabs-{$this->id}");
});
JS;
$this->headScript()->appendScript($js);
?>
<!-- END of: finna - Helpers/feedtabs.phtml -->
