<!-- START of: finna - Helpers/reservationlist-reserve.phtml -->
<?php
  $user = $this->auth()->getManager()->getUserObject();
?>

<?php
  $contents = array_map(
    function ($listHandler) {
      $location = $listHandler->getTitle($this->layout()->userLang);
      if (!$location) {
        $location = $this->transEscWithPrefix('source_', $listHandler->getInstitution()) . ': ' . $listHandler->getIdentifier();
      }
      $href = $this->url(
          'reservationlist-placeorderoptions',
          [],
          [
          'query' => [
            'recordId' => $this->driver->getUniqueID(),
            'source' => $this->driver->getSourceIdentifier(),
            'institution' => $listHandler->getInstitution(),
            'listIdentifier' => $listHandler->getIdentifier(),
          ],
        ]
      );
      $linkLabel = $this->translate(['ReservationList', 'Place hold on this title']);
      return $this->component('finna-holdings/location-and-link', compact('href', 'location', 'linkLabel'));
    },
    $this->listHandlers
  );
?>
<?=
  $this->component(
      'finna-holdings/table',
      [
      'header' => $this->translate('ReservationList::Place hold on this title'),
      'contents' => $contents,
    ]
  );
?>
<?php
  if ($listsContainingRecord = $this->reservationList($user)->getListsContainingRecord($this->driver)):
    $lists = array_map(
        function ($listEntity) {
        $title = $listEntity->getTitle();
        $href = $this->url('reservationlist-displaylist', ['listId' => $listEntity->getId()]);
        return compact('title', 'href');
      },
        $listsContainingRecord
    );
?>
  <?= $this->component('finna-list/saved-in', ['class' => 'loaded', 'lists' => $lists])?>
<?php endif; ?>
<!-- END of: finna - Helpers/reservationlist-reserve.phtml -->
