<!-- START of: finna - Helpers/selection-view.phtml -->
<div class="container-fluid cookie-consent">
  <div class="cookie-consent-text">
    <?=$this->transEsc('selection_view')?>
  </div>
  <div class="nav navbar-nav nav-absolute cookie-consent-button">
    <?php if ($this->layout()->currentRecordId): ?>
        <form action="<?=$this->session()->get('return_url')?>" method="POST">
            <input type="hidden" name="params" value="<?=$this->layout()->currentRecordId?>">
            <input type="submit" name="submit" value="<?=$this->transEsc('selection')?>" class="btn btn-primary feedback-record">
        </form>
    <?php endif; ?>
  </div>
  <div class="nav navbar-nav nav-absolute cookie-consent-button">
    <a href="<?=$this->session()->get('return_url')?>" class="btn btn-primary feedback-record"><?=$this->transEsc('selection_cancel')?></a>
  </div>
</div>
<!-- END of: finna - Helpers/selection-view.phtml -->