<!-- START of: finna - Helpers/selection-view.phtml -->
<div class="container-fluid bazaar-selection">
  <div class="bazaar-selection-text">
    <?=$this->transEscAttr('selection_view')?>
  </div>
  <div class="nav navbar-nav nav-absolute bazaar-selection-button">
    <?php if ($this->layout()->bazaarRecordId): ?>
        <form action="<?=$this->escapeHtmlAttr($this->bazaarSession()->get('return_url'))?>" method="POST">
            <input type="hidden" name="params" value="<?=$this->escapeHtmlAttr($this->layout()->bazaarRecordId)?>">
            <input type="submit" name="submit" value="<?=$this->transEscAttr('selection')?>" class="btn btn-primary bazaar-record">
        </form>
    <?php endif; ?>
  </div>
  <div class="nav navbar-nav nav-absolute bazaar-selection-button">
    <a href="<?=$this->escapeHtmlAttr($this->bazaarSession()->get('return_url'))?>" class="btn btn-primary bazaar-record"><?=$this->transEscAttr('selection_cancel')?></a>
  </div>
</div>
<!-- END of: finna - Helpers/selection-view.phtml -->

