<?php // Do not add start and end comments ?>
<?php if ($this->wrapper): ?>
    <div class="social-icon-wrapper <?=$this->class?>">
      <i class="social-icon fa <?="fa-{$this->escapeHtmlAttr($icon['name'])}"?>" aria-label="<?=$this->transEscAttr('social_icon', ['%%platform%%' => $icon['name']])?>"></i>
    </div>
<?php else: ?>
    <i class="social-icon fa <?="fa-{$this->escapeHtmlAttr($icon['name'])}"?>" aria-label="<?=$this->transEscAttr('social_icon', ['%%platform%%' => $icon['name']])?>"></i>
<?php endif; ?>
