<div class="public-list-embed">
  <div class="clearfix hidden-print">
    <div class="public-list-row">
      <? if ($this->title): ?><h<?=$this->headingLevel?>><?= $this->title ?></h<?=$this->headingLevel?>><? endif ?>
      <? if ($this->description): ?><div class="public-list-desc"><?= $this->markdown()->toHtml($this->description) ?></div><? endif ?>
      <? if ($this->date): ?>
        <div class="public-list-info">
          <div><?= $this->transEsc("modified"); ?>: <?=$this->dateTime()->convertToDisplayDate('Y-m-d H:i:s', $this->date); ?></div>
        </div>
      <? endif ?>
    </div>
  </div>
  <div class="public-list-view results result-view-<?=$this->escapeHtmlAttr($this->params->getView())?>">
    <?= $this->partial('search/list-' . $this->view . '.phtml',
    [
      'results' => $this->results,
      'params' => $this->params
    ])
    ?>
  </div>
</div>
