<div class="login-description-terms">
  <p>Kirjastokortin numerolla kirjauduttaessa henkilötiedoistasi tallennetaan verkkopalveluun kirjastokortin käyttäjätunnus tai kortin numero, PIN-koodi, kirjautujan nimi, sähköpostiosoite ja kotikirjasto.</p>
  <p>Sähköpostiosoitteella kirjauduttaessa henkilötiedoistasi tallennetaan kirjautujan nimi, sähköpostiosoite ja kotikirjasto. </p>
  <p>Lisätietoa henkilötietojesi käsittelystä <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>" data-lightbox-ignore target="_blank"><?=$this->transEsc('Privacy')?>-sivulla</a>.</p>
</div>
