<!-- START of: finna - Recommend/CollectionSideFacets.phtml -->
<?php
    if ($this->driver instanceof \Finna\RecordDriver\SolrLido || $this->driver->tryMethod('getArchiveType') === 'collection') {
        $term = 'Filter Collection';
    } else {
        $term = 'Filter Archive';
    }
    $this->slot('side-facet-caption')->set($term);
?>
<?php $this->baseUriExtra = $this->recommend->getResults()->getParams()->getCollectionId(); ?>
<?=$this->render('Recommend/SideFacets.phtml')?>
<!-- END of: finna - Recommend/CollectionSideFacets.phtml -->
