<!-- START of: finna - Recommend/DateRangeVisAjax.phtml -->
<div class="daterange-vis">
  <form action="<?= $this->formAction; ?>" class="year-form">
    <div class="form-ui">
	  <div class="year-range">
      <label for="year-from" class="visually-hidden"><?=$this->transEsc('year_from');?></label>
	    <input id="year-from" class="form-control form-inline input-year year-from" type="number" value="<?=$this->escapeHtmlAttr($this->from) ?>">
	    <span class="year-separator">&ndash;</span>
      <label for="year-to" class="visually-hidden"><?=$this->transEsc('year_to');?></label>
	    <input id="year-to" class="form-control form-inline input-year year-to" type="number" value="<?=$this->escapeHtmlAttr($this->to) ?>">
	  </div>
	  <button class="btn btn-primary submit" type="submit">
      <?=$this->icon('search') ?><span><?= $this->transEsc($this->submitLabel); ?></span>
    </button>
    </div>
    <div class="content" aria-hidden="true">
      <?php $this->assetManager()->appendScriptLink('vendor/jquery.colorhelpers.min.js'); ?>
      <?php $this->assetManager()->appendScriptLink('vendor/jquery.flot.min.js'); ?>
      <?php $this->assetManager()->appendScriptLink('vendor/jquery.flot.selection.min.js'); ?>
      <?php $this->assetManager()->appendScriptLink('finna-daterange-vis.js'); ?>
      <div class="date-vis"></div>
      <?=$this->icon('spinner') ?>
    </div>
    <div class="navigation" aria-hidden="true">
      <div class="zoom-in"><?=$this->icon('daterange-zoom-in') ?></div>
      <div class="zoom-out"><?=$this->icon('daterange-zoom-out') ?></div>
      <div class="prev"><?=$this->icon('daterange-prev') ?></div>
      <div class="next"><?=$this->icon('daterange-next') ?></div>
      <div class="expand-modal"><?=$this->icon('daterange-expand') ?></div>
    </div>
    <?php if ($backend != 'primo' && (!isset($hideType) || !$hideType)): ?>
    <div class="range-type" role="radiogroup" aria-labelledby="range_type_label">
      <label id="range_type_label" class="visually-hidden"><?=$this->transEsc('Search Type')?>:</label>
      <div class="radiobutton">
        <input class="timeline_overlap" type="radio" name="type" id="radio_overlap" value="overlap"<?= !$this->type || $this->type == 'overlap' ? ' checked="checked"' : ''; ?>>
        <label for="radio_overlap"><?= $this->translate('Timeline overlap'); ?></label>
      </div>
      <div class="radiobutton">
        <input class="timeline_within" type="radio" name="type" id="radio_within" value="within"<?= $this->type == 'within' ? ' checked="checked"' : ''; ?>>
        <label for="radio_within"><?= $this->translate('Timeline within'); ?></label>
      </div>
    </div>
    <?php endif; ?>
  </form>
</div>
<?php
$script = <<<JS
    $(document).ready(function() {
      finna.dateRangeVis.initVis(
          '{$backend}',
          '{$daterangeFacet}',
          '{$searchParams}',
          '{$baseParams}',
          $('.daterange-vis'),
    JS;

$script .= isset($this->plotFrom) ? "{$this->plotFrom}," : 'false,';
$script .= isset($this->plotTo) ? "{$this->plotTo}," : 'false,';
$script .= isset($this->plotImmediately) ? "{$this->plotImmediately}" : 'false';
$script .= '
  );
});';
?>
<?=$this->assetManager()->outputInlineScriptString($script); ?>
<!-- END of: finna - Recommend/DateRangeVisAjax.phtml -->
