<?php
  $__attributes = $this->htmlAttributes($attributes ?? [])->add('class', 'finna-md-editable');
  $__markdown = $markdown ?? '';
  $__containerAttributes = $this->htmlAttributes(['data-markdown' => $__markdown]);
  $__editable = $html ?? '';
  if (isset($emptyHtml)) {
    $__containerAttributes['data-empty-html'] = $emptyHtml;
    if (empty($__markdown)) {
      $__editable = $emptyHtml;
    }
  }
  if ($preview ?? false) {
    $__containerAttributes['data-preview'] = 'true';
  }
?>
<?= $this->render('components/molecules/containers/finna-editable/finna-editable.phtml', [
    'attributes' => $__attributes,
    'containerAttributes' => $__containerAttributes,
    'editable' => $__editable,
    'editLabel' => $editLabel ?? null
  ]); ?>
<?php $this->jsTranslations()->addStrings([
    'editor_bold' => 'editor_bold',
    'editor_close' => 'editor_close',
    'editor_heading' => 'editor_heading',
    'editor_image' => 'editor_image',
    'editor_italic' => 'editor_italic',
    'editor_link' => 'editor_link',
    'editor_ordered_list' => 'editor_ordered_list',
    'editor_other' => 'editor_other',
    'editor_panel' => 'editor_panel',
    'editor_prompt_image' => 'editor_prompt_image',
    'editor_prompt_link' => 'editor_prompt_link',
    'editor_quote' => 'editor_quote',
    'editor_truncate' => 'editor_truncate',
    'editor_unordered_list' => 'editor_unordered_list',
    'details_summary_placeholder' => 'details_summary_placeholder',
    'details_text_placeholder' => 'details_text_placeholder',
    'preview' => 'Preview'
  ]); ?>
<?php $this->headScript()->appendFile('components/organisms/widgets/finna-md-editable/finna-md-editable.js'); ?>
