<?=$this->component('page-title', ['title' => $this->transEsc('library_card_connected_users')]);?>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th scope="col"><?=$this->transEsc('library_card_date_of_connection')?></th>
      <th scope="col"><?=$this->transEsc('Last Login')?></th>
      <th scope="col"><?=$this->transEsc('account_username')?></th>
      <th scope="col"><?=$this->transEsc('account_login_method')?></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->accounts as $account): ?>
      <tr>
        <td data-label="<?=$this->transEsc('library_card_date_of_connection')?>"><?=$this->escapeHtml($account['created']->format($this->config()->dateTimeFormat()))?></td>
        <td data-label="<?=$this->transEsc('Last Login')?>"><?=$this->escapeHtml($account['lastLogin']->format($this->config()->dateTimeFormat()))?></td>
        <td data-label="<?=$this->transEsc('account_username')?>"><span><?=$this->escapeHtml($account['username'])?><?php if ($account['userId'] === $this->auth()->getUserObject()->getId()): ?><br><span class="library-card-this-session">(<?=$this->transEsc('library_card_this_session')?>)</span><?php endif;?></td></span>
        <td data-label="<?=$this->transEsc('account_login_method')?>"><?=$this->transEscWithPrefix('login_method_', $account['authMethod']) ?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<div class="infobox"><?=$this->transEsc('library_card_connected_users_info')?></div>
<button class="btn btn-primary" data-bs-dismiss="modal"><?=$this->transEsc('Close') ?></button>
