<?=$this->component('page-title', ['title' => $this->transEsc('library_card_connected_users')]);?>
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th scope="col"><?=$this->transEsc('library_card_date_of_connection')?></th>
      <th scope="col"><?=$this->transEsc('Last Login')?></th>
      <th scope="col"><?=$this->transEsc('account_username')?></th>
      <th scope="col"><?=$this->transEsc('account_login_method')?></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->users as $user): ?>
      <tr>
        <td data-label="<?=$this->transEsc('library_card_date_of_connection')?>"><?=$this->escapeHtml($user['created']->format($this->config()->dateTimeFormat()))?></td>
        <td data-label="<?=$this->transEsc('Last Login')?>"><?=$this->escapeHtml($user['lastLogin']->format($this->config()->dateTimeFormat()))?></td>
        <td data-label="<?=$this->transEsc('account_username')?>"><?=$this->escapeHtml($user['username'])?></td>
        <td data-label="<?=$this->transEsc('account_login_method')?>"><?=$this->transEscWithPrefix('login_method_', $user['authMethod']) ?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<div class="infobox"><?=$this->transEsc('library_card_connected_users_info')?></div>
<button class="btn btn-primary" data-bs-dismiss="modal"><?=$this->transEsc('Close') ?></button>
