<!-- START of: finna - librarycards/home.phtml -->
<?php
    // Set up page title:
    $this->headTitle($this->translate('Library Cards'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Library Cards') . '</li>';

    // Additional translations
    $this->jsTranslations()->addStrings(['new_password_success' => 'new_password_success']);

    $user = $this->auth()->isLoggedIn();
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'librarycards']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content">
      <?=$this->flashmessages()?>
      <?php if (!$this->translationEmpty('library_cards_instructions_html')): ?><p class="no-content-message"><?=$this->translate('library_cards_instructions_html')?></p><?php endif; ?>
      <h2><?=$this->transEsc('Library Cards Connected To My Account')?></h2>
      <?php if (empty($this->libraryCards)): ?>
        <h4><?=$this->transEsc('You do not have any library cards')?></h4>
      <?php else: ?>
        <table class="table table-striped useraccount-table library-cards mobile-table">
          <tr class="headers">
            <th><?=$this->transEsc('Library Card Name')?></th>
            <?php if ($this->multipleTargets): ?>
            <th><?=$this->transEsc('login_target')?></th>
            <?php endif; ?>
            <th><?=$this->transEsc('Username')?></th>
            <th class="library-card-actions"><?=$this->transEsc('Actions')?></th>
          </tr>
          <?php
            $displayCards = [];
            foreach ($this->libraryCards as $record) {
              $username = $record['cat_username'];
              $target = '';
              if ($this->multipleTargets) {
                if (strstr($username, '.')) {
                  list($target, $username) = explode('.', $username, 2);
                }
              }
              $display = '<td data-label="' . $this->transEsc('Library Card Name') . '">';
              $libraryCardName = $record['card_name'] == "$target.$username" ? $this->escapeHtml($username) : $this->escapeHtml($record['card_name']);
              if ($libraryCardName) {
                $display .= '<span>' . $libraryCardName . '</span>';
              } else {
                $display .= '<span>' . transEsc("Library Card name missing") . '<a class="btn-link" href="' . $this->url('editLibraryCard') . $this->escapeHtmlAttr($record['id']) . '" title="' . $this->transEsc('Edit Library Card') . '"> ' . $this->transEsc("Add name") . '</a></span>';
              }
              $display .= '</td>';
              if ($this->multipleTargets) {
                $displayLibraryName = $target ? $this->transEsc("source_$target", null, $target) : '&nbsp;';
                $display .= '<td data-label="' . $this->transEsc('login_target') . '"><span>' . $displayLibraryName . '</span></td>';
              }
              $display .= '<td data-label="' . $this->transEsc('Username') .'">';
              $barcode = $record['barcode'] ?? $username;
              if ($barcode !== $username) {
                $display .= '<p>' . $this->escapeHtml($username) . '</p>';
              }
              $display .= '<a href="' . $this->url('barcode-show') .'?code=' . $this->escapeHtmlAttr($barcode) . '" title="' . $this->transEscAttr('show_barcode_title') . '">';
              if (strcasecmp($record['cat_username'], $user->cat_username) === 0 && ($barcodeImg = $this->barcode()->createPng($barcode, 2, 60))) {
                $display .= '<div class="librarycard-barcode"><img src="data:image/png;base64,' . $barcodeImg . '" alt=""></div>';
              }
              $display .= '<span>' . $this->escapeHtml($barcode) . '</span></a></td>';
              $display .= '<td data-label="' . $this->transEsc('Actions') . '" class="library-card-actions"><div>';
              if ($this->ils()->checkFunction('changePassword', (array)$record)) {
                $display .= '<a class="btn-link" href="' . $this->url('newLibraryCardPassword') . '?id=' . $this->escapeHtmlAttr($record['id']) . '" data-lightbox title="' . $this->transEsc('Change Password') . '"><i class="fa fa-lock bigger gray"></i> ' . $this->transEsc('Change Password') . '</a>';
              }
              $display .= '<a class="btn-link" href="' . $this->url('editLibraryCard') . $this->escapeHtmlAttr($record['id']) . '" title="' . $this->transEsc('Edit Library Card') . '"><i class="fa fa-pen gray" aria-hidden="true"></i> ' . $this->transEsc('Update Card Details'). '</a>';
              $display .= '<div class="dropdown"><a class="btn-link dropdown-toggle" data-toggle="dropdown" href="' . $this->url('librarycards-deletecard') . '?cardID=' . urlencode($record['id']) . '">';
              $display .= '<i class="fa fa-unlink gray" aria-hidden="true"></i> ' . $this->transEsc('Disconnect Library Card') . '</a>';
              $display .= '<ul class="dropdown-menu useraccount-cancel">';
              $display .= '<li class="disabled"><a>' . $this->transEsc('Disconnect Library Card') . '?</a></li>';
              $display .= '<li><a href="' . $this->url('librarycards-deletecard') . '?cardID=' . urlencode($record['id']) . '&amp;confirm=1" data-clear-account-cache>' . $this->transEsc('confirm_dialog_yes') . '</a></li>';
              $display .= '<li><a href="#">' . $this->transEsc('confirm_dialog_no') . '</a></li>';
              $display .= '</ul></div></div></td>';
              if ($user->cat_username === $record['cat_username']) {
                array_unshift($displayCards, $display);
              } else {
                $displayCards[] = $display;
              }
            }
          ?>
          <?php foreach ($displayCards as $card): ?>
            <tr>
              <?=$card?>
            </tr>
          <?php endforeach; ?>
        </table>
      <?php endif; ?>

      <div>
        <a href="<?=$this->url('editLibraryCard') ?>NEW" class="btn btn-primary" title="<?=$this->transEsc('Connect Library Card')?>"><i class="fa fa-link" aria-hidden="true"></i> <?=$this->transEsc('Connect Library Card')?>...</a>
        <br>
        <br>
      </div>
  </div>
</div>
<!-- END of: finna - librarycards/home.phtml -->
