<!-- START of: finna - Recommend/SideFacets.phtml -->
<?
  $this->headScript()->appendFile('facets.js');

  $results = $this->recommend->getResults();
  $options = $this->searchOptions($this->searchClassId);

  $this->headScript()->appendFile('vendor/bootstrap-datepicker.min.js');
  $datePickerLang = 'en';
  switch ($this->layout()->userLang) {
    case 'en-gb':
        $this->headScript()->appendFile('vendor/bootstrap-datepicker.en-GB.min.js');
        $datePickerLang = 'en-GB';
        break;
    case 'fi':
        $this->headScript()->appendFile('vendor/bootstrap-datepicker.fi.min.js');
        $datePickerLang = 'fi';
        break;
    case 'sv':
        $this->headScript()->appendFile('vendor/bootstrap-datepicker.sv.min.js');
        $datePickerLang = 'sv';
        break;
  }
?>
<? if ($results->getResultTotal() > 0): ?>
  <h4><i class="fa fa-arrow-down visible-xs pull-left"></i> <?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?><? if (!isset($this->overrideSideFacetCaption) && !$this->translationEmpty('tooltip_facet_html')): ?><span class="tooltip-facet pull-right" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="<?=$this->transesc('tooltip_facet_html')?>"><i class="fa fa-info-big"></i></span><? endif; ?></h4>
<? endif; ?>
<?
  foreach ($checkboxFilters as $current) {
    $availCount = $current['selected'] ? -1 : $this->checkboxFacetCounts($current, $results);
    $availableRecords = $availCount < 0 ? '' : $this->localizedNumber($availCount);
  }
?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets(); ?>
<? $checkboxesShown = false; ?>
<? if (count($checkboxFilters) > 0):
    foreach ($checkboxFilters as $current) {
        $availCount = $current['selected'] ? -1 : $this->checkboxFacetCounts($current, $results);
        $availableRecords = $availCount < 0 ? '' : $this->localizedNumber($availCount);
        if ($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible']) {
            $checkboxesShown = true;
            break;
        }
    }
    ?>
  <div class="checkboxFilter<?if($shown == 0):?> hidden<? endif; ?>"><?=$html ?></div>
<?if ($checkboxesShown):?>
<div class="checkboxFilter">
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/checkbox-filters.phtml', ['checkboxFilters' => $checkboxFilters, 'results' => $results, 'availableRecords' => $availableRecords]); ?>
</div>
<? endif; ?>

<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : []; ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<? $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<? $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<? $newItemsFacets = $this->recommend->getNewItemsFacets(); ?>
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); ?>
<? $module = $this->layout()->templateDir; ?>
<?
  $plotFrom = null;
  $daterangeFacetField = null;
  if (null === $module || in_array($module, ['search', 'primo'])) {
    $options = $results->getOptions();
    if (is_callable([$options, 'getDateRangeSearchField'])) {
        $daterangeFacetField = $options->getDateRangeSearchField();
    }
    $dateRangeFilter = $params->getDateRangeFilter();
  }
?>
<?
    $queryHandler = 'AllFields';
    if ($results->getParams()->getSearchType() == 'basic') {
        $queryHandler = $results->getParams()->getQuery()->getHandler();
    }
    ?>
<?
  $customQueryHandler = $queryHandler != 'AllFields';
  if (isset($browse) && $browse) {
    $customQueryHandler = $customQueryHandler && $queryHandler != $defaultBrowseHandler;
  }
?>
<? if (!empty($filterList) || $customQueryHandler): ?>
  <div class="list-group filters">

      <? // Finna query handler (type) remove link ?>
      <? if ($customQueryHandler): ?>
        <? $removeLink = $results->getUrlQuery()->setHandler('AllFields'); ?>
        <a class="list-group-item active" href="<?=$removeLink?>">
          <span class="pull-right"><i class="fa fa-times"></i></span>
          <?=$this->transEsc('search_in_field'); ?>:
          <?=$this->transEsc($queryHandler); ?>
        </a>
      <? endif; ?>
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $i => $filter): ?>
        <?
          $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
          if ($index !== false) {
              unset($collapsedFacets[$index]); // Open if we have a match
          }
          if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
            $removeLink = $results->getUrlQuery()->replaceTerm($filter['value'], '');
          } else {
            $removeLink = $results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], $filter['operator']);
          }
          if ($filter['displayText'] == '[* TO *]') {
            $filter['displayText'] = $this->translate('filter_wildcard');
          }
        ?>
        <a class="list-group-item active" href="<?=$removeLink?>">
          <span class="pull-right"><i class="fa fa-times" aria-hidden="true"></i></span>
          <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><span class="sr-only"><?=$this->transEsc('Remove filter')?>: </span><?=$this->transEsc($field)?><? if (!empty($filter['displayText'])): ?>: <?=$this->escapeHtml($filter['displayText'])?><? endif; ?>
        </a>
      <? endforeach; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>


<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <? foreach ($sideFacetSet as $title => $cluster): ?>
  <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
    <? $facets_before_more = $this->recommend->getShowMoreSetting($title); ?>
    <? $showMoreInLightbox = $this->recommend->getShowInLightboxSetting($title); ?>
    <? $daterangeFacet = $title == $daterangeFacetField; ?>
    <div class="list-group facet<?= $daterangeFacet ? ' daterange-facet' : '' ?> facet-group" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <? // Use a with href and preventing js for keyboard navigation ?>
      <button class="list-group-item title<? if (in_array($title, $collapsedFacets)): ?> collapsed<? endif ?>" data-toggle="collapse" data-target="#side-collapse-<?=$this->escapeHtmlAttr($title) ?>" href="#" onclick="return false;"><?=$this->transEsc($cluster['label'])?></button>
      <?
        if ($daterangeFacet) {
          $fromVal = $toVal = $type = null;
          $queryHelper = $results->getUrlQuery();
          $queryHelper->removeDefaultParameter("{$daterangeFacetField}_type");
          $searchParams = $formParams = $queryHelper->getParamsWithoutPage(false);
          if ($dateRangeFilter) {
            $formParams = $queryHelper->removeFacet($dateRangeFilter['field'], $dateRangeFilter['value'], 'AND');
            $spatialFilter = $results->getParams()->parseDateRangeFilter($dateRangeFilter['value']);
            $from = isset($spatialFilter['from']) ? $spatialFilter['from'] : null;
            $to = isset($spatialFilter['to']) ? $spatialFilter['to'] : null;
            $fromVal = $from != '*' ? $from : '';
            $toVal = $to != '*' ? $to : '';
            if (isset($spatialFilter['type'])) {
              $type = $spatialFilter['type'];
            }
            if ($params->getSearchType() != 'advanced') {
              $lookfor = $params->getQuery()->getString();
              if ($lookfor == '' && $fromVal === null && $toVal === null) {
                $plotFrom = 0;
              }
            }
          }
        }
      ?>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="collapse<? if(!in_array($title, $collapsedFacets)): ?> in<? endif ?>">
        <? if (isset($newItemsFacets[$title])): ?>
          <?
            $newItemValues = [
              '7DAYS',
              '1MONTHS',
              '3MONTHS',
              '6MONTHS',
              '1YEAR'
            ];
          ?>
          <? foreach ($newItemValues as $newItemValue): ?>
            <? $addURL = $results->getUrlQuery()->replaceFacet($title, "[NOW-$newItemValue/DAY TO *]"); ?>
            <a href="<?=$addURL ?>" class="list-group-item facetAND"><?=$this->transEsc('new_items_' . strtolower($newItemValue), null, $newItemValue)?></a>
          <? endforeach; ?>
          <div class="list-group-item">
            <div class="row">
              <div class="col-sm-12">
                <form name="<?=$this->escapeHtmlAttr($title)?>Filter" id="<?=$this->escapeHtmlAttr($title)?>Filter" class="form-inline">
                  <?=$results->getUrlQuery()->asHiddenFields(['page' => "/./", 'filter' => "/^{$title}:.*/"])?>
                  <label for="<?=$this->escapeHtmlAttr($title)?>from"><?=$this->transEsc('new_items_from')?></label>
                  <input type="text" class="form-control form-inline date-picker-field" autocomplete="off" name="<?=$this->escapeHtmlAttr($title)?>from" id="<?=$this->escapeHtmlAttr($title)?>from" maxlength="10" size="10" value="<?=$this->escapeHtmlAttr($this->dateTime()->convertToDisplayDate('Y-m-d', $newItemsFacets[$title]['date'])) ?>" placeholder="<?=$this->dateTime()->getDisplayDateFormat() ?>">
                  <button class="btn btn-primary btn-default date-picker-button" type="submit" value=""><i class="fa fa-search"></i><span class="sr-only"><?=$this->transEsc('Search');?></span></button>
                </form>
<?
  $component = $this->escapeHtmlAttr($title) . 'from';
  $endDate = $this->dateTime()->convertToDisplayDate('U', time());
  // Load the script inline to support asynchronously loaded sidefacets:
  $script = <<<EOT
if ($.isReady) {
  initDatePicker();
} else {
  $(document).ready(initDatePicker);
}
function initDatePicker() {
  $('#$component').datepicker({
    'language': '$datePickerLang',
    'format': 'd.m.yyyy',
    'weekStart': 1,
    'endDate': '$endDate',
    'autoclose': true
  });
}
EOT
;
echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
              </div>
            </div>
          </div>

        <? elseif ($daterangeFacet): ?>
            <div class="list-group-item daterange">
              <?=$this->partial('Recommend/DateRangeVisAjax.phtml', [
                'submitLabel' => 'Update',
                'from' => $fromVal,
                'to' => $toVal,
                'formAction' => $formParams,
                'searchParams' => $searchParams,
                'baseParams' => $formParams,
                'type' => $type,
                'backend' => (null === $module || $module == 'search') ? 'solr' : $module,
                'daterangeFacet' => $daterangeFacetField,
                'plotFrom' => $plotFrom
              ]);
              ?>
            </div>
        <? elseif (isset($rangeFacets[$title])): ?>
          <?=$this->context($this)->renderInContext('Recommend/SideFacets/range-facet.phtml', ['results' => $results, 'title' => $title, 'facet' => $rangeFacets[$title]]); ?>
        <? else: ?>
          <? if (in_array($title, $hierarchicalFacets)): ?>
          <?=$this->context($this)->renderInContext('Recommend/SideFacets/hierarchical-facet.phtml', ['title' => $title, 'sortOptions' => $hierarchicalFacetSortOptions[$title]]); ?>
        <noscript>
          <? endif; ?>
          <? $contextVars = [
              'options' => $options,
              'allowExclude' => $this->recommend->excludeAllowed($title),
              'facets_before_more' => $this->recommend->getShowMoreSetting($title),
              'showMoreInLightbox' => $this->recommend->getShowInLightboxSetting($title)
          ]; ?>
          <?=$this->context($this)->renderInContext('Recommend/SideFacets/cluster-list.phtml', array_merge($contextVars, ['results' => $results, 'title' => $title, 'cluster' => $cluster])); ?>
          <? endif; ?>
        <? if ($title == 'usage_rights_str_mv'): ?>
          <div class="list-group-item usage-rights-info">
            <i class="fa fa-info-big"></i><div class="info"><?=$this->translate('usage_rights_info')?></div><a class="more-info" href="<?=$this->url('content-page', ['page' => 'terms'])?>#terms"><?=$this->translate('usage_rights_info_more')?></a>
          </div>
        <? endif; ?>
        <? if (in_array($title, $hierarchicalFacets)): ?>
          </noscript>
        <? endif; ?>
      </div>
    </div>
  <? endforeach; ?>
<? endif; ?>
<!-- END of: finna - Recommend/SideFacets.phtml -->
