<!-- START of: finna - search/home/home-3.phtml -->
<?= $this->linkedEventsTabs(['tabs' => [
    [
        'title' => 'Kaikki'
    ],
    [
        'title' => 'Nuoret',
        'params' => ['keyword' => 'helmet:12006']
    ],
    [
        'title' => 'Kielikahvilat',
        'params' => ['keyword' => 'helmet:11733']
    ],
    [
        'title' => 'Kirjallisuus',
        'params' => ['keyword' => 'helmet:11193']
    ],
    [
        'title' => 'Lapset',
        'params' => ['keyword' => 'helmet:12005']
    ],
    [
        'title' => 'Lukupiirit',
        'params' => ['keyword' => 'helmet:11727']
    ],
    [
        'title' => 'Musiikki',
        'params' => ['keyword' => "yso:p1808"]
    ],
    [
        'title' => 'Näyttelyt',
        'params' => ['keyword' => 'helmet:10778']
    ],
    [
        'title' => 'Opastukset ja kurssit',
        'params' => ['keyword' => 'helmet:11699']
    ],
    [
        'title' => 'Pelitapahtumat',
        'params' => ['keyword' => 'helmet:11687']
    ],
    [
        'title' => 'Satutunnit',
        'params' => ['keyword' => 'helmet:11777']
    ],
    [
        'title' => 'Seniorit',
        'params' => ['keyword' => 'helmet:10675']
    ],
    [
        'title' => 'Muut tapahtumat',
        'params' => ['keyword' => 'helmet:11689']
    ],

  ],
  'searchTools' => 'show',
  'navStyle' => 'pills',
  'showMobileAccordion' => false,
  'limit' => 9,
]); ?>

<calendar-date>
  <calendar-month></calendar-month>
</calendar-date>

<style>
      #tooltip {
        background: #333;
        color: white;
        font-weight: bold;
        padding: 4px 8px;
        font-size: 13px;
        border-radius: 4px;
        display: none;
      }

      #tooltip[data-show] {
        display: block;
      }

      #arrow,
      #arrow::before {
        position: absolute;
        width: 8px;
        height: 8px;
        background: inherit;
      }

      #arrow {
        visibility: hidden;
      }

      #arrow::before {
        visibility: visible;
        content: '';
        transform: rotate(45deg);
      }

      #tooltip[data-popper-placement^='top'] > #arrow {
        bottom: -4px;
      }

      #tooltip[data-popper-placement^='bottom'] > #arrow {
        top: -4px;
      }

      #tooltip[data-popper-placement^='left'] > #arrow {
        right: -4px;
      }

      #tooltip[data-popper-placement^='right'] > #arrow {
        left: -4px;
      }
    </style>
<button id="button" aria-describedby="tooltip">I'm a button</button>
<button id="button" aria-describedby="tooltip">I'm a button</button>

<div id="tooltip" role="tooltip">I'm a tooltip</div>


<div><h2>home-3.phtml</h2><p>Nämä ovat esimerkkejä, lisää tyhjä home-3.phtml custom/search/home -kansioon, jos et käytä tiedostoa</p></div>
<div class="home-column"><?= $this->feed('news'); ?></div>
<div class="home-column"><?= $this->feed('carousel-vertical'); ?></div>
<!-- END of: finna - search/home/home-3.phtml -->
