<!-- START of: finna - search/home/home-4.phtml -->
<div>
  <h2>home-4.phtml</h2>
  <p>Nämä ovat esimerkkejä. Lisää tyhjä home-4.phtml custom/search/home -kansioon, jos et käytä tiedostoa.</p>
</div>
<!-- END of: finna - search/home/home-4.phtml -->

<?= $this->linkedEventsTabs(['tabs' => [
    [
        'title' => 'Nuoret',
        'params' => ['keyword' => 'helmet:12006']
    ],
    [
        'title' => 'Kielikahvilat',
        'params' => ['keyword' => 'helmet:11733']
    ],
    [
        'title' => 'Kirjallisuus',
        'params' => ['keyword' => 'helmet:11193']
    ],
    [
        'title' => 'Lapset',
        'params' => ['keyword' => 'helmet:12005']
    ],
    [
        'title' => 'Lukupiirit',
        'params' => ['keyword' => 'helmet:11727']
    ],
    [
        'title' => 'Musiikki',
        'params' => ['keyword' => 'helmet:11835']
    ],
    [
        'title' => 'Lukupiirit',
        'params' => ['keyword' => 'helmet:1']
    ],
    [
        'title' => 'Näyttelyt',
        'params' => ['keyword' => 'helmet:10778']
    ],
    [
        'title' => 'Opastukset ja kurssit',
        'params' => ['keyword' => 'helmet:11699']
    ],
    [
        'title' => 'Pelitapahtumat',
        'params' => ['keyword' => 'helmet:11687']
    ],
    [
        'title' => 'Satutunnit',
        'params' => ['keyword' => 'helmet:11777']
    ],
    [
        'title' => 'Seniorit',
        'params' => ['keyword' => 'helmet:10675']
    ],
    [
        'title' => 'Muut tapahtumat',
        'params' => ['keyword' => 'helmet:11689']
    ],
    [
        'title' => 'kaikki'
    ]
  ],
  'searchTools' => 'show',
  'limit' => 6,
  'navStyle' => 'pills',
  'showMobileAccordion' => true,
]); ?>

<?=$this->feedTabs(['title' => 'Otsikko', 'ids' => ['Tapahtumat' => 'news', 'Uutiset' => 'carousel', 'Muuta' => 'carousel-small']])?>