<!-- START of: finna - Auth/Shibboleth/login.phtml -->
<?php $account = $this->auth()->getManager(); ?>
<?php $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<div>
  <div class="login-col shibboleth-login">
    <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>" data-lightbox-ignore>
      <img src="<?=$this->imageLink('haka_login_vaaka_lg.png') ?>" alt="<?=$this->transEscAttr('Haka Login') ?>">
      <span class="sr-only"><?=$this->transEsc('Institutional Login')?></span>
    </a>
  </div>
  <div class="login-col">
    <?=$this->icon('info', 'login-info-icon') ?>
    <div class="login-description">
      <p class="login-info">
       <?=$this->translate('login_desc_connect_card_html') ?>
      </p>
    </div>
    <div class="login-description shibboleth">
      <?=$this->translate('login_desc_shibboleth_html')?>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<?php if ($tmpl = $this->content()->findTemplateForLng('Auth/Shibboleth/terms', true)): ?>
  <?=$this->partial($tmpl) ?>
<?php endif; ?>
<!-- END of: finna - Auth/Shibboleth/login.phtml -->
