<!-- START of: finna - myresearch/download-checkout-history.phtml -->
<?php
    // Set page title.
    $this->headTitle($this->translate('loan_history_download'));
    $this->layout()->breadcrumbs = '<li class="breadcrumb-item"><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="breadcrumb-item active">' . $this->transEsc('loan_history_download') . '</li>';
    $inLightBox = $this->inLightbox ?? false;
?>
<?php if (!$inLightBox): ?>
  <!-- Leftside navigationbar -->
  <?=$this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'historicLoans']); ?>
  <div class="<?=$this->layoutClass('mainbody')?>">
<?php endif; ?>

<h2><?=$this->transEsc('loan_history_download') . ': ' . $this->transEsc('loan_history_download_' . $this->format); ?></h2>
<button class="btn btn-primary js-download-checkout-history" data-format="<?=$this->escapeHtmlAttr($this->format)?>" type="button"></button>

<?php if (!$inLightBox): ?>
  </div>
<?php endif; ?>
<?php
// Initialize checkout history download element
$js = <<<JS
      finna.checkoutHistory.init();
    JS;

echo $this->inlineScript()->appendScript($js);
?>
<!-- END of: finna - myresearch/download-checkout-history.phtml -->
