<!-- START of: finna - Helpers/OnlinePayment/CPU.phtml -->
<img src="<?=$this->imageLink('online-payment-cpu.png')?>" id="cpu-logo" alt="CPU" />
<input name="transactionId" type="hidden" value="<?=$this->escapeHtmlAttr($this->transactionId)?>">
<input type="submit" name="pay" class="btn btn-primary" value="<?=$this->transEscAttr('online_payment_go_to_pay', ['%%amount%%' => $this->safeMoneyFormat($this->amount / 100.00)])?>" />
<!-- END of: finna - Helpers/OnlinePayment/CPU.phtml -->
