<!-- START of: finna - Helpers/OnlinePayment/Paytrail.phtml -->
<div class="online-payment-area">
  <input name="transactionId" type="hidden" value="<?=$this->escapeHtmlAttr($this->transactionId)?>">
  <input type="submit" name="pay" class="btn btn-primary btn-lg" value="<?=$this->transEscAttr('online_payment_go_to_pay', ['%%amount%%' => $this->amount ? $this->safeMoneyFormat($this->amount / 100.00) : ''])?>"<?=(!$this->amount) ? ' disabled' : ''?>>
</div>
<img src="<?=$this->imageLink('online-payment-paytrail.png')?>" id="paytrail-logo" alt="Paytrail" />
<!-- END of: finna - Helpers/OnlinePayment/Paytrail.phtml -->
