<?php $recordHelper = $this->record($this->driver);?>
<?php if ($recordHelper->getImagePopupZoom() && $recordHelper->hasLargeImageLayout()): ?>
    <?php
      $manifestUrl = $this->recordLinker()->getGeneratedIiifManifestUrl($this->driver);
    ?>
    <!-- START of: finna - RecordDriver/DefaultRecord/iiif-viewer.phtml -->
    <?=$this->component('finna-iiif-viewer', ['manifestUrls' => [['url' => $manifestUrl]], 'pages' => $this->pages ?? null]);?>
<?php else: ?>
  <?=$this->recordImage($recordHelper)->renderImage(
    'record',
      [
        'small' => ['w' => 100, 'h' => 100],
        'medium' => ['w' => 250, 'h' => 250],
      ],
      [
        'disableModal' => true,
      ]
  );?>
<?php endif; ?>
