<?php
$scrollUrls = [];
if ($scrollData) {
  foreach ($scrollData as $key => $value) {
    $scrollUrls[$key] = $value
      ? $this->recordLinker()->getActionUrl($value, 'Modal')
      : null;
  }
}
?>
<nav aria-label="<?=$this->transEscAttr('Search Results')?>">
  <ul class="pager hidden-print">
    <?php if (isset($scrollData['previousRecord'])): ?>
      <?php if (isset($scrollData['firstRecord'])): ?>
        <li role="none">
          <a class="icon-link"
            href="<?=$this->escapeHtmlAttr($scrollUrls['firstRecord'])?>"
            aria-label="<?=$this->transEscAttr('First Search Result')?>"
            rel="nofollow"
          >
            <?=$this->icon('page-first', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('First')?></span>
          </a>
        </li>
      <?php endif; ?>
      <li role="none">
        <a class="icon-link"
          href="<?=$this->escapeHtmlAttr($scrollUrls['previousRecord'])?>"
          aria-label="<?=$this->transEscAttr('Previous Search Result')?>"
          rel="nofollow"
        >
          <?=$this->icon('page-prev', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Prev')?></span>
        </a>
      </li>
    <?php else: ?>
      <?php if (isset($scrollData['firstRecord'])): ?>
        <li class="disabled" aria-hidden="true" role="none">
          <a class="icon-link">
            <?=$this->icon('page-first', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('First')?>
          </a>
        </li>
      <?php endif; ?>
      <li class="disabled" aria-hidden="true" role="none">
        <a class="icon-link">
          <?=$this->icon('page-prev', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Prev')?></span>
        </a>
      </li>
    <?php endif; ?>

    <?php if (isset($scrollData['currentPosition']) && isset($scrollData['resultTotal'])): ?>
      <li role="none">
        <?=$this->transEsc('of_num_results', [
          '%%position%%' => $this->localizedNumber($scrollData['currentPosition']),
          '%%total%%' => $this->localizedNumber($scrollData['resultTotal']),
        ]) ?>
      </li>
    <?php endif; ?>

    <?php if (isset($scrollData['nextRecord'])): ?>
      <li role="none">
        <a class="icon-link"
          href="<?=$this->escapeHtmlAttr($scrollUrls['nextRecord'])?>"
          aria-label="<?=$this->transEscAttr('Next Search Result')?>"
          rel="nofollow"
        >
          <span class="icon-link__label"><?=$this->transEsc('Next')?></span>
          <?=$this->icon('page-next', 'icon-link__icon') ?>
        </a>
      </li>
      <?php if (isset($scrollData['lastRecord'])): ?>
        <li role="none">
          <a class="icon-link"
            href="<?=$this->escapeHtmlAttr($scrollUrls['lastRecord'])?>"
            aria-label="<?=$this->transEscAttr('Last Search Result')?>"
            rel="nofollow"
          >
            <span class="icon-link__label"><?=$this->transEsc('Last')?></span>
            <?=$this->icon('page-last', 'icon-link__icon') ?>
          </a>
        </li>
      <?php endif; ?>
    <?php else: ?>
      <li class="disabled" aria-hidden="true" role="none">
        <a class="icon-link">
          <span class="icon-link__label"><?=$this->transEsc('Next')?></span>
          <?=$this->icon('page-next', 'icon-link__icon') ?>
        </a>
      </li>
      <?php if (isset($scrollData['lastRecord'])): ?>
        <li class="disabled" aria-hidden="true" role="none">
          <a class="icon-link">
            <span class="icon-link__label"><?=$this->transEsc('Last')?></span>
            <?=$this->icon('page-last', 'icon-link__icon') ?>
          </a>
        </li>
      <?php endif; ?>
    <?php endif; ?>
  </ul>
</nav>
