<div class="container-fluid record-view-header">
  <div class="container">
    <div class="search-tools">
      <div class="record-back hidden-print">
          <?
          $html = '<span><i class="fa fa-arrow-alt-left"></i></span>';
          $html .= '<span class="back-to-search-text hidden-xs hidden-sm">' . $this->transEsc('Back to search results') . '</span>';
          $previousSearch = $this->searchMemory()->getLastSearchLink($html);
          if ($previousSearch !== ''):
              ?>
            <div class="back-to-search"><?=$previousSearch?></div>
          <? endif; ?>
      </div>
      <div>
        <?  $this->scrollData = $this->searchMemory()->getLastScrollData() ?>
          <? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
            <ul class="pager hidden-print" id="view-pager">
                <? if ($this->scrollData['previousRecord']): ?>
                    <? if ($this->scrollData['firstRecord']): ?>
                    <li>
                      <a href="<?=$this->recordLink()->getUrl($this->scrollData['firstRecord'])?>" rel="nofollow"><i class="fa fa-first-page"></i><span class="sr-only"><?=$this->transEsc('First Record')?></span></a>
                    </li>
                    <? endif; ?>
                  <li class="pager-previous-record">
                    <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" rel="nofollow"><i class="fa fa-arrow-alt-left"></i><span class="sr-only"><?=$this->transEsc('Previous Record')?></span></a>
                  </li>
                <? else: ?>
                    <? if ($this->scrollData['firstRecord']): ?>
                    <li class="disabled" title="<?=$this->transEsc('First Record')?>"><a><i class="fa fa-first-page"></i></a></li>
                    <? endif; ?>
                  <li class="disabled" title="<?=$this->transEsc('Previous Record')?>"><a><i class="fa fa-arrow-alt-left"></i></a></li>
                <? endif; ?>
              <li class="pager-text">
                  <?=$this->transEsc('of_num_results', [
                      '%%position%%' => $this->localizedNumber($this->scrollData['currentPosition']),
                      '%%total%%' => $this->localizedNumber($this->scrollData['resultTotal'])
                  ]) ?>
              </li>
                <? if ($this->scrollData['nextRecord']): ?>
                  <li class="pager-next-record">
                    <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" rel="nofollow"><i class="fa fa-arrow-alt-right"></i><span class="sr-only"><?=$this->transEsc('Next Record')?></span></a>
                  </li>
                    <? if ($this->scrollData['lastRecord']): ?>
                    <li>
                      <a href="<?=$this->recordLink()->getUrl($this->scrollData['lastRecord'])?>" rel="nofollow"><i class="fa fa-last-page"></i><span class="sr-only"><?=$this->transEsc('Last Record')?></span></a>
                    </li>
                    <? endif; ?>
                <? else: ?>
                  <li class="disabled" title="<?=$this->transEsc('Next Record')?>"><a><i class="fa fa-arrow-alt-right"></i></a></li>
                    <? if ($this->scrollData['lastRecord']): ?>
                    <li class="disabled" title="<?=$this->transEsc('Last Record')?>"><a><i class="fa fa-last-page"></i></a></li>
                    <? endif; ?>
                <? endif; ?>
            </ul>
          <? endif; ?>
      </div>
    </div>
  </div>
</div>
