<!-- START of: finna - record/sidebar-contents.phtml -->
<div class="organisation-menu">
    <?=$this->render('record/record-organisation-menu.phtml') ?>
</div>
<?php foreach ($this->related()->getList($this->driver) as $current): ?>
    <?=$this->related()->render($current)?>
<?php endforeach; ?>
<?php if ($customContentTemplate = $this->content()->findTemplateForLng('content/Additions/record-post-recommendations')): ?>
  <div>
      <?=$this->render($customContentTemplate)?>
  </div>
<?php endif; ?>
<!-- END of: finna - record/sidebar-contents.phtml -->
