<!-- START of: finna - record/validationreport.phtml -->
<?php
  $this->headTitle($this->translate('record_validation_report_title'));

  $list = function (array $items): string {
    return '<ul class="list-bullets">'
      . implode(
          '',
          array_map(
              fn ($s) => '<li>' . $this->escapeHtml($s) . '</li>',
              $items
          )
      )
      . '</ul>';
  };
?>
<h2><?=$this->transEsc('record_validation_report_title')?></h2>

<?=$this->flashmessages()?>

<?=$this->translate('record_validation_message_html', ['%%url%%' => $this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver))])?>

<?php if ($errors = $this->validationReport['errors'] ?? null): ?>
  <h3><?=$this->transEsc('Errors')?></h3>
  <?=$list($errors)?>
<?php endif; ?>

<?php if ($warnings = $this->validationReport['warnings'] ?? null): ?>
  <h3><?=$this->transEsc('Warnings')?></h3>
  <?=$list($warnings)?>
<?php endif; ?>

<?php if ($recommendations = $this->validationReport['recommendations'] ?? null): ?>
  <h3><?=$this->transEsc('Recommendations')?></h3>
  <?=$list($recommendations)?>
<?php endif; ?>

<!-- END of: finna - record/validationreport.phtml -->
