<?php
  $initParams = json_encode(
    [
          'id' => $this->id,
          'buildings' => $this->buildings,
          'details' => $this->showDetails,
      ]
);
  $setupJS = <<<JS
      $(function() {
         finna.organisationInfo.initWidget({$initParams});
      });
      JS;
   $this->headScript()->appendScript($setupJS);
?>
<div class="organisation-info js-organisation-info-widget">
  <div>
    <h2><?=$this->transEsc('organisation_info_title')?> <span class="js-loader hidden"><?=$this->icon('spinner') ?></span></h2>
  </div>
  <div class="js-content"></div>
</div>
