<?= $this->translate('due_date_hello') ?>

<? if (!empty($this->errors)): ?>

<?= $this->translate('due_date_email_txt_only_errors') ?>

<? endif; ?>
<? if (!empty($this->loans)): ?>

<?= $this->translate('due_date_email_txt' . (count($this->loans) == 1 ? '_singular' : ''), ['%%loancount%%' => count($loans)]) ?>

<? endif; ?>
<? if (!empty($this->loans)):  ?>
<? foreach ($this->loans as $loan): ?>
<?
  if (!empty($loan['title'])) {
      $title = $loan['title'];
  } else {
      if (is_a($loan['record'], 'VuFind\\RecordDriver\\SolrDefault') && !is_a($loan['record'], 'VuFind\\RecordDriver\\Missing')) {
          $title = $loan['record']->getTitle();
      }
      if (empty($title)) {
          $title = $this->transEsc('Title not available');
      }
  }
?>
<?= $title ?>

<?= $this->translate('Due Date') . ': ' . $loan['dueDateFormatted'] ?>


<? endforeach; ?>
<? endif; ?>

<?= !empty($this->errors) ? $this->translate('due_date_email_login_error') : $this->translate('due_date_email_link_title') ?>

<?= $this->url ?>

<? if (!empty($this->errors)): ?>

<?= $this->translate('due_date_failed_library') ?>
<? foreach ($this->errors as $error): ?>
<? $card = $error['card']; ?>
<? $target = ''; ?>
<? list($target, $card) = explode('.', $card, 2); ?>

<?=$target ? $this->transEsc("source_$target", null, $target) : '' ?>

<? endforeach; ?>
<? endif; ?>

<?= $this->translate('unsubscribe_description') ?>

<?= $this->unsubscribeUrl ?>
