<?= $this->transEsc('due_date_hello', ['%%firstname%%' => $this->firstname])?>

<?= $this->translate('account_expiration_body', ['%%firstname%%' => $this->firstname, '%%expirationDate%%' => $this->expirationDate, '%%serviceAddress%%' => $this->serviceAddress, '%%loginMethod%%' => $this->translate('account_expiration_login_method_' . $this->loginMethod, null, '..'), '%%privateListCnt%%' => $this->privateListCnt, '%%publicListCnt%%' => $this->publicListCnt, '%%savedSearchCnt%%' => $this->savedSearchCnt]) ?>
