<? // This is a text-only email template; do not include HTML! ?>
<?=$this->translate('This email was sent from')?>: <?=$this->from?>

<? if (!empty($this->message)): ?><?=$this->translate("Message From Sender")?>:
<?=$this->message?>

<? endif; ?>

<?=$this->translate("Online Access")?>:
<? foreach ($this->drivers as $records): ?>

------------------------------------------------------------
<?=$this->record($records)->getEmail() ?>

<?endforeach;?>

------------------------------------------------------------