<? //Don't add START and END comments ?>
<? if (!empty($data)): ?>
<div class="truncate-field" data-rows="3">
  <? foreach ($data as $field): ?>
  <div class="subjectLine" property="keywords">
    <? $subject = ''; ?>
    <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
    <? $i = 0; foreach ($field as $subfield): ?>
      <?=($i++ == 0) ? '' : ' &gt; '?>
      <? $subject = trim($subject . ' ' . $subfield); ?>
      <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
    <? endforeach; ?>
  </div>
  <? endforeach; ?>
</div>
<? endif; ?>
