<!-- START of: finna - RecordDriver/SolrDefault/data-containerTitle.phtml -->
<?
  $containerSource = $this->driver->getSourceIdentifier();
  $containerID = $this->driver->getContainerRecordID();
  $ref = $this->driver->getContainerReference();
  $link = $containerID
    ? $this->recordLink()->getUrl("$containerSource|$containerID")
    : $this->record($this->driver)->getLink('journaltitle', $data);
?>
<a href="<?=$link?>"><?=$this->escapeHtml($data)?></a>
<?=empty($ref) ? '' : $this->escapeHtml($ref)?>
<!-- END of: finna - RecordDriver/SolrDefault/data-containerTitle.phtml -->
