<? //Don't add START and END comments ?>
<? if (!empty($data)): ?>
  <div class="truncate-field">
    <? foreach($data as $row => $key): ?>
      <? $composition = []; ?>
        <? foreach ($key as $value): ?>
          <? $next = next($key); ?>
          <? if (is_numeric($next)) {
                $composition[] = "$value ($next)";
            } else if (!is_numeric($value)) {
                $composition[] = $value;
            }
          ?>
        <? endforeach; ?>
        <? if ($row): ?><br/><? endif ;?><?=implode(', ', $composition); ?>
    <? endforeach; ?>
  </div>
<? endif; ?>
