<!-- START of: finna - RecordDriver/SolrDefault/data-tags.phtml -->
<? if ($this->usertags()->getMode() !== 'disabled'): ?>
      <span class="pull-right">
        <i class="fa fa-plus"></i> <a class="tag-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
      </span>
      <div id="tagList">
        <? if (count($tagList) > 0): ?>
          <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
        <? else: ?>
          <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
        <? endif; ?>
      </div>
<? endif; ?>
<!-- END of: finna - RecordDriver/SolrDefault/data-tags.phtml -->
