<? //Don't add START and END comments ?>
<? if (!empty($data)): ?>
  <div class="truncate-field">
    <? foreach($data as $fields => $keys): ?>
        <? if (!empty($keys['solo'])): ?>
           <?=$this->escapeHtml($keys['solo'])?><? if (empty($keys['count'])): ?>,<? endif; ?>
        <? endif; ?>
        <? if (!empty($keys['count'])): ?>
            (<?=$this->escapeHtml($keys['count'])?>),
        <? endif; ?>
        <? if (!empty($keys['doubler'])): ?>
           <?=$this->escapeHtml($keys['doubler'])?>,
        <? endif; ?>
        <? if (!empty($keys['compose'])): ?>
            <?=$this->escapeHtml($keys['compose'])?>
        <? endif; ?><br/>
    <? endforeach; ?>
  </div>
<? endif; ?>
