<? //Don't add START and END comments ?>
<? if (!empty($data)): ?>
  <? foreach ($data as $field): ?>
    <?
      $partParts = [];
      if (!empty($field['name'])) {
          $partParts[] = $field['name'];
      }
      if (!empty($field['partNumber'])) {
          $partParts[] = $field['partNumber'];
      }
      if (!empty($field['partName'])) {
          $partParts[] = $field['partName'];
      }
      $lookfor = implode(', ', $partParts);
  ?>
    <?/* Depending on the record driver, $field may either be an array with
       "name" and "number" keys or a flat string containing only the series
       name.  We should account for both cases to maximize compatibility. */?>
    <? if (is_array($field)): ?>
      <? if (!empty($lookfor)): ?>
          <a href="<?=$this->record($this->driver)->getLink('series', $lookfor)?>"><?=$this->escapeHtml($lookfor)?></a><? if (!empty($field['issn']) || !empty($field['number'])): ?>, <? endif; ?>
        <? if (!empty($field['issn'])): ?>
          ISSN <?=$this->escapeHtml($field['issn'])?><? if (!empty($field['number'])): ?>; <? endif; ?>
        <? endif; ?>
        <? if (!empty($field['number'])): ?>
          <?=$this->escapeHtml($field['number'])?>
        <? endif; ?>
        <br/>
      <? endif; ?>
    <? else: ?>
      <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
    <? endif; ?>
  <? endforeach; ?>
<? endif; ?>
