<!-- START of: finna - search/filters.phtml -->
<?
$params = $this->results->getParams();
$params->activateAllFacets();
$filterList = $params->getFilterList(true);
$checkboxFilters = $params->getCheckboxFacets();
$showFilters = !empty($params->getFilterList(false));
$options = $this->searchOptions($this->searchClassId);
$lastSort = $browse ? null: $this->searchMemory()->getLastSort($this->searchClassId);
$defaultSortApplied = !isset($this->params) || $lastSort == $options->getDefaultSortByHandler($this->params->getSearchHandler());

?>

<? if ($showFilters): ?>
  <div class="finna-filters">
    <div class="container">
    <? $defaultFilterState = $this->hasDefaultsApplied || $options->getRetainFilterSetting() || !$defaultSortApplied ? ' checked="checked"' : ''; ?>
      <span class="checkbox<?=$defaultFilterState ? ' checked' : ''?>">
        <label>
          <input onChange="$('.applied-filter').click();$('.finna-filters .checkbox').toggleClass('checked'); var sort = $(this).closest('form').find('input[name=sort]'); sort.val($('.finna-filters .checkbox').hasClass('checked') ? sort.data('value') : '');" type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
            <?=$this->transEsc("basic_search_keep_filters")?>
        </label>
      </span>

      <? foreach ($checkboxFilters as $filter): ?>
        <? if($filter['selected']): ?>
          <span class="filter-value">
            <? $removeLink = $results->getUrlQuery()->removeFilter($filter['filter']); ?>
            <?=$this->translate($filter['desc']) ?>
            <a href="<?=$removeLink?>">x</a>
          </span>
        <? endif ?>
      <? endforeach; ?>

      <? foreach ($filterList  as $field => $data): ?>
        <?=$this->transEsc($field)?>:
        <? foreach ($data as $index => $value): ?>
          <? $operatorChar = ($value['operator'] == 'NOT') ? '-' : ($value['operator'] == 'OR' ? '~' : ''); ?>
          <? if ($value['operator'] == 'NOT') echo $this->transEsc('NOT'); if ($value['operator'] == 'OR' && $index > 0) echo $this->transEsc('OR'); ?>
            <span class="filter-value">
              <? $removeLink = $results->getUrlQuery()->removeFacet($value['field'], $value['value'], $value['operator']);?>
              <?=$this->escapeHtml($value['displayText'])?>
              <a href="<?=$removeLink?>">x</a>
            </span>
        <? endforeach; ?>
      <? endforeach; ?>
    </div>
  </div>
<? endif; ?>
<!-- END of: finna - search/filters.phtml -->
