<!-- START of: finna - search/filters.phtml -->
<div class="finna-filters hidden-xs">
  <div class="container">
  <? $defaultFilterState = $hasDefaultsApplied || $options->getRetainFilterSetting() || !$defaultSortApplied ? ' checked="checked"' : ''; ?>
    <span class="checkbox<?=$defaultFilterState ? ' checked' : ''?>">
      <label>
        <input onChange="$('.applied-filter').click();$('.finna-filters .checkbox').toggleClass('checked'); var sort = $(this).closest('form').find('input[name=sort]'); sort.val($('.finna-filters .checkbox').hasClass('checked') ? sort.data('value') : '');" type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
          <?=$this->transEsc("basic_search_keep_filters")?>
      </label>
    </span>

    <? foreach ($checkboxFilters as $filter): ?>
      <? if($filter['selected']): ?>
        <span class="filter-value">
          <? $removeLink = isset($results) ? $results->getUrlQuery()->removeFilter($filter['filter']) : ''; ?>
          <?=$this->translate($filter['desc']) ?>
          <a href="<?=$removeLink?>">x</a>
        </span>
      <? endif ?>
    <? endforeach; ?>

    <? foreach ($filterList  as $field => $data): ?>
      <?=$this->transEsc($field)?>:
      <? foreach ($data as $index => $value): ?>
        <? $operatorChar = ($value['operator'] == 'NOT') ? '-' : ($value['operator'] == 'OR' ? '~' : ''); ?>
        <? if ($value['operator'] == 'NOT') echo $this->transEsc('NOT'); if ($value['operator'] == 'OR' && $index > 0) echo $this->transEsc('OR'); ?>
          <span class="filter-value">
            <?  ?>
            <? $removeLink = isset($results) ? $results->getUrlQuery()->removeFacet($value['field'], $value['value'], $value['operator']) : '';?>
            <?=$this->escapeHtml($value['displayText'])?>
            <a href="<?=$removeLink?>">x</a>
          </span>
      <? endforeach; ?>
    <? endforeach; ?>
  </div>
</div>
<!-- END of: finna - search/filters.phtml -->
